### ISSUE TITLE
kanidm_unixd exit codes

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#1025]
in #1024 I removed the exit code responses when `kanidm_unixd` quits during an error condition - this needs to be restored.

**Describe the solution you'd like**

Return code 1 when bad things happen 😄 

**Additional context**

Something something async tokio 🧀 🦀

**Comment by MinhPhan8803** [comment]
> in #1024 I removed the exit code responses when `kanidm_unixd` quits during an error condition - this needs to be restored.
> 
> **Describe the solution you'd like**
> 
> Return code 1 when bad things happen 😄
> 
> **Additional context**
> 
> Something something async tokio 🧀 🦀

Can we just not return ExitCode directly since `#[tokio::main]` expands to a `block_on()` that will toss the return value of the async block up?

**Comment by MinhPhan8803** [comment]
If this is feasible I will make a PR.

**Comment by MinhPhan8803** [comment]
As for returning from inside tracing, it appears there is no way to capture return using `tracing_forest`. Could we move to using `tracing_futures` instead?

**Comment by yaleman** [comment]
Sounds good to me, I can't remember why I removed it at the time, but it was some random implementation detail I didn't have time to go back for.

**Comment by Firstyear** [comment]
No we want tracing forest, because it keeps context of what happened in an async event, so removing that isn't an option.

The issue with returning the exit code is not an obvious/simple one, we likely need to store this in a queue or similar so the main thread can dequeue the error as it exits.

But also knowning when an exit triggers a quit is quite hard, since the core of this is an event loop, and I'm not sure any single task in that event loop can actually trigger a quit.

**Comment by Firstyear** [comment]
Look at https://github.com/kanidm/kanidm/blob/master/unix_integration/src/daemon.rs#L719 

This is the event loop, where every event is a new task spawn, and the task spawns aren't joined by handles so we can't grab their return values. It also means they can't trigger a quit.

So I think there are no return values to actually return here, since they can't trigger a quit outside of an actual crash.

**Comment by MinhPhan8803** [comment]
I think this issue refers to all the `return` scattered throughout the file that replaced `process::exit()` in #1024 . 
Thinking about it, they all deal with argument parsing and initialization, meaning they do not necessarily need to exist in async context. Could we move them out of async, expands `#[tokio::main]` manually for the task loops, and use a separate subscriber for the them?

**Comment by Firstyear** [comment]
Consistency of how we message our users is more important IMO, so keeping tracing-forest is important here.

A better option could be to wrap the synchronous startup checks into a single function, then check the result of that. We can then use that to set a return / error code instead.

But also I don't think tokio::main allows return with an error does it?

**Comment by MinhPhan8803** [comment]
It does https://tokio.rs/tokio/tutorial/hello-tokio. 
If I'm not mistaken `tokio::main` should allow you to return anything since [block_on()](https://docs.rs/tokio/latest/tokio/runtime/struct.Runtime.html#method.block_on) just captures the return value of the async block, and `tokio::main` expands to return the value from `block_on()` directly.

**Comment by Firstyear** [comment]
Ahh okay, but like I said, we'll still need tracing-forest here. So I think we need to work within that (or we can submit changes to tracing-forest, the maintainer of that is very happy for changes).

**Comment by MinhPhan8803** [comment]
I will try to explore this approach first, and then if it still proves inadequate then we probably need to submit changes to tracing-forest.

> A better option could be to wrap the synchronous startup checks into a single function, then check the result of that. We can then use that to set a return / error code instead.

**Comment by Firstyear** [comment]
Sounds good :)

**Comment by MinhPhan8803** [comment]
Wait, the deamon main already does some logging for initialization stuff outside of the worker tasks, couldn't we just do the same for the rest of them?

**Comment by MinhPhan8803** [comment]
> I think this issue refers to all the `return` scattered throughout the file that replaced `process::exit()` in #1024 .
> Thinking about it, they all deal with argument parsing and initialization, meaning they do not necessarily need to exist in async context. Could we move them out of async, expands `#[tokio::main]` manually for the task loops, and use a separate subscriber for them?

Essentially a modified version of my suggestion here with tracing_forest only handling the task loop and all initialization stuff logged outside of it, since this is already somewhat the case in existing code.

**Comment by Firstyear** [comment]
I think that could be okay?
