### ISSUE TITLE
Provide TLS toggle for LDAP and HTTP separately

### ISSUE THREAD

**Issue by kittywitch** [kanidm/kanidm#1064]
**Is your feature request related to a problem? Please describe.**
My issue is that I do not have the capacity to reverse proxy the HTTP part of the application when it becomes HTTPS because I also want LDAPS.

**Describe the solution you'd like**
A description of what you'd expect to happen.
I would like a toggle in the config to turn HTTPS and LDAP off separately from one another.

**Describe alternatives you've considered**
Are there any alternative solutions or features you've considered.

**Additional context**

**Comment by Firstyear** [comment]
Sorry I don't quite understand the problem. Do you want Kanidm to serve HTTP traffic (no TLS) and also LDAPS (with TLS) from the same configuration? Or are you trying to disable LDAP?

**Comment by kittywitch** [comment]
I would like Kanidm to serve HTTP traffic (no TLS) while serving LDAPS (with TLS) in the same configuration, yes.

**Comment by kittywitch** [comment]
I would not like to disable LDAP.

**Comment by Firstyear** [comment]
hey there,

We had a chat about this, and it comes at an interesting time that you raised this issue. we've run into multiple issues with users either NOT configuring TLS properly, or wanting it in some ways like you want where you have more toggles. A major concern for us is "more configuration == more things that can go wrong == more support requests".

So we are going to propose and make a change that TLS on the server is ALWAYS required, even if behind a load balancer. Loadbalancers can still terminate TLS and then forward via a self-signed cert to the server itself. We may even make it such that Kanidm can self-sign and generate in-memory certificates at start up to make this easier. 

As a result, we won't implement this, because TLS will always be required on in the future, even if it's invalid self-signed certs between the LB and the Kanidm server. For example haproxy can service this with:

```
backend webservers
   server web1 10.0.0.5:443 ssl verify none
```

but all major loadbalancers can connect via TLS to their pool servers.

Sorry about that,

If you have any other questions, please let us know!
