### ISSUE TITLE
Develop a method for setting up a dev/test environment full of expected config

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#1131]
**Is your feature request related to a problem? Please describe.**

It'd be handy to have a way of yeeting in a load of configuration elements to have a test/dev environment full of things.

To be clear, this is for *development* purposes, not for demo/real usage.

- [x] groups
- [x] persons
 - [ ] with SSH keys
 - [ ] various auth methods
- [ ] service accounts
- [x] oauth2 rp's
- [ ] RADIUS config/users
- [ ] 🦀🔪 

**Describe the solution you'd like**

An automated/documented process for creating them so we have a way to have a ready-to-go environment.

**Describe alternatives you've considered**

Donating my old socks to fast food megacorps to help supply their feedstock.

**Additional context**

**Comment by Firstyear** [comment]
I actually think we need to clamp down on "you can only upgrade one version at a time", that way we can

* trim all the old migration code
* test from currest stable -> dev when issues come up

Generally I think it would be hard to say "we have all these test db's" because they'd need configured oauth2 apps etc.

**Comment by yaleman** [comment]
While logging it, the reality of it kinda sunk in - hence the "process for creating example data" snuck in. 

The "set up an environment and yeet in a load of config" thing is still a task for me, so devs can make sure the various UIen look right from a variety of directions.

**Comment by yaleman** [comment]
Original issue text, for posterity:

> **Is your feature request related to a problem? Please describe.**
> Upgrades break sometimes and it'd be handy to have "this is a DB from version x"
> 
> **Describe the solution you'd like**
> 
> Either test files with "example.com" domains and some config, or a known process for creating them so we have a way to reproduce issues.
> 
> 
> **Describe alternatives you've considered**
> 
> Donating my old socks to fast food megacorps to help supply their feedstock.
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.
>

**Comment by tumbl3w33d** [comment]
In what kind of environment do you want to run this?
* local workstation (which OS?)?
* containerized?
* script language matters (python + ansible)?
* some cloud provider?
* some CI?

Asking because some of these things I already have automated ( @yaleman has access to a snapshot of that) and the data is defined in yaml structures. Maybe you can recycle some of that.

**Comment by yaleman** [comment]
Preferably local, mac/linux - there's already a large chunk of it done in [setup_dev_environment.sh](https://github.com/kanidm/kanidm/blob/master/scripts/setup_dev_environment.sh)

**Comment by tumbl3w33d** [comment]
I see we are back to the fundamental discussion of whether the CLI tool should be used for scripting. 😁 And this just assumes that some kanidm instance magically comes from somewhere outside. You want to keep it like that or move to something more self-contained?

**Comment by yaleman** [comment]
Near any CLI tool can be used for scripting things, but if the ones in Kanidm break your workflow then too bad, that's on you for not using the available APIs and tooling 😄 .

**Comment by yaleman** [comment]
There's testkit, which does a load of live-server testing with internal automation methods, but the intention of #1131 is for doing further integration testing with things outside the build tooling, like:

- UI testing, 
- ensuring the kanidm CLI tools work (because clap fails at runtime sometimes even if it compiles), 
- `pykanidm`, 
- RADIUS-related things, 
- webauthn authenticators 
- etc etc.

At the moment I'm happy with the Shell Script That Does Things because it's simple, and tests the existing tooling, and gets me to where I need to be to test PRs and such, but if there's a better way that works as fast (because devs do this over and over during dev cycles) then I'm happy to take it.

- no docker
- no big orchestration things
- rust/shell only

To be clear, this is for DEV things, not demo, let alone live environments.

**Comment by Firstyear** [comment]
We may need some checklists or procedures we can follow before a release to ensure this surface area is covered too. :)

**Comment by yaleman** [comment]
That's what the test I added to CI which runs `scripts/test_run_release_server.sh` is for, more integration testing things 😄 Once I'm happier with how it runs, I'll add it to the release checklist.

**Comment by TheRealGramdalf** [comment]
> That's a good idea, I think rather than committing the DB's, the ability to "setup and load a bunch of sample data" is probably better because then we can also drive and test that too, and it gives us options to debug issues.

I think a good way to implement this would be a client utility that takes a YAML file as input, and "converts" it into the necessary API calls. [Authelia](https://www.authelia.com/integration/openid-connect/grafana/#authelia) uses this for some of it's configuration, and it could open the door for easier import of existing configs to Kanidm.

As an implementation detail, something I see relatively often is people confusing Traefiks' dynamic yml config with the docker compose.yml - one way to differentiate the two would be to use a `.kml` file - use all standard YAML syntax, but just to help differentiate the two.


This deviates from the idea of it being only for development, but I could see it being quite useful to have the ability to create a definition in yml so that it can be easily shared - for example, a yaml file that defines some groups, an Oauth2 RS, and stuff like that. You would have to take care to make sure this would be very hard to break - validating that there aren't any conflicts before applying anything to the server, thus making the operation atomic would be one example. 
The benefits of something like this is that it becomes much easier to visualize - in the current absence of a UI (which is for good reason), YAML would make it much easier to plan out a deployment before actually applying it to your server.

Additionally, you could even add a tag - perhaps take a hash of the input .yml and link that to anything the operation creates, which then allows you to "undo" an operation.

But I digress. Just a thought, and perhaps it requires it's own bug report/feature request, but it seemed to fit here. I also recognize that Kanidm has specific and intentional design choices, and that this might go against them - I don't pretend to know all the details, and as always it's up to you whether you want to implement it or not.

**Comment by yaleman** [comment]
Yep, that's a sensible plan. As long as it's anything but YAML. 😄

**Comment by TheRealGramdalf** [comment]
> However, doing it for "live" config is something folks should build providers for terraform/other dedicated config tools - don't reinvent the world - integrate with it.

It may still make sense to have some form of integration that makes this simpler - as far as I know it would be hard to undo something without the ability to figure out what changes were made by e.g. terraform, so with a simple request (i.e. `undo kopid`) kanidm can take the necessary steps to revert changes, or throw a more helpful error if it cant (i.e. if users have been added to a group since it was added by terraform).

Or maybe the Kanidm API already exposes enough that this could be done with API requests alone - I just think integration would make it more usable and scalable (since most use cases of automation like that are likely at scale) if it had the bulk of the logic happen within Kanidm - sort of like server side copy with SMB.

**Comment by yaleman** [comment]
Undo would require an internal transaction log which would have to work across replication, and I'm not sure I really see the utility for that functionality. "Accidental" changes shouldn't happen in a secure identity management system.

Otherwise the API endpoints allow for managing things and SCIM (#2315) will target more industry-standardised APIs.

Either way, these points are all outside the scope of *this* issue.
