### ISSUE TITLE
LDAP Bind to service account with non-empty bind dn

### ISSUE THREAD

**Issue by 9SMTM6** [kanidm/kanidm#1208]
**Is your feature request related to a problem? Please describe.**
Despite solving how to generally read mail attributes as described in https://github.com/kanidm/kanidm/issues/1207, it still doesnt work in Authelia, and perhaps also gitea with ldap.

First of all, were speaking about binding with access token from a service account to LDAP.

Unsure about gitea - what I'm noticing there is that searches etc get logged coming from anonymous - but empty bind dn is accepted in the form and appears to correctly bind. 

Authelia REQUIRES a non-empty bind dn, at least Ive not been able to get it to accept some variant of empty in the config. 

I've not had enough time to test all possible avenues, but I've experimented a decent bit, and havent got it to work.

Thus I would ask If it would be possible to also allow to provide the dn of the serviceaccount when using a token to log in with it.

I've not tried it with service account PWs as these are deprecated, but perhaps that would be a reason to keep it if the above is not possible. (EDIT: Right, that credential is also not allowed to access LDAP, at least thats what the help text on the command says).

I've now also tried all kinds of variations with ldapsearch and yet to find a way to make tokens work with a non empty bind dn.

EDIT2: Puh that was barely comprehensible, fixed a few things and highlighted that were speaking about access tokens, yaleman got it but that makes it clearer for others. 

**Describe the solution you'd like**

-

**Describe alternatives you've considered**

-

**Additional context**

https://www.authelia.com/configuration/first-factor/ldap/#user

**Comment by yaleman** [comment]
Keycloak also forces a non-empty bind DN, maybe we can do one of:

- ignore entered bind DNs 
- use them as an additional filter on authentication
- allow/require the use of the token id as the username, similar to how providers like AWS or OAuth require both the id and secret when authenticating. That'd allow an indexed token lookup instead of a table scan for tokens, too?

**Comment by 9SMTM6** [comment]
All of these look fine to me as an enduser. I would actually prefer the last variant, I can imagine that this might make it easier to identify the token to remove should one such have leaked. A bit more work when rotating should it be required, but oh well.

**Comment by Firstyear** [comment]
I think we need the key id as the username here. We can't just ignore the bind dn because we use then we affect the logic of unix password checks via ldap.

The way we currently do this is with "" binds, if there is a value in PW set, then we are extracting the JWS keyid and using that to determine the service-account that is attempting the login.

We could just allow the keyid as the binddn instead here which resolves the problem, since we can use that instead.

**Comment by Firstyear** [comment]
Actually, you're right, token as the binddn makes more sense.

**Comment by yaleman** [comment]
so to validate my understanding, LDAP auth will use:

- username: the value of `token_id` (which is visible in `kanidm  service-account api-token status <username>`)
- password: the token

The token id probably needs to be shown on create then

**Comment by Firstyear** [comment]
I think your suggestion to pass the token as the dn is better, since we can just ignore the pw field then.

**Comment by Firstyear** [comment]
Aaaaaaaaaaaaa true. Okay I'll re-do the pr, that's a really good point.

**Comment by yaleman** [comment]
And it helps with "hey which token has been stolen and we need to disable it" since bind username's logged etc 😄
