### ISSUE TITLE
Resolve TLS without kanidm

### ISSUE THREAD

**Issue by NPCDW** [kanidm/kanidm#1227]
**Is your feature request related to a problem? Please describe.**
I want to manage all ssl certificates through `nginx` instead of handing over to each application in the `nginx` backend.

I tried to configure ssl in both `nginx` and `kanidm` and sure enough got an error.
![image](https://user-images.githubusercontent.com/32638459/203504769-723a8f95-04b4-4a18-9e49-ecb5ced5e178.png)
![image](https://user-images.githubusercontent.com/32638459/203504944-bdc10555-b77a-4e29-9187-2e3b5ba4e085.png)
```
bindaddress = "[::]:8443"
tls_chain = "/data/chain.pem"
tls_key = "/data/key.pem"
domain = "auth.0520.site"
origin = "https://auth.0520.site"
```
![image](https://user-images.githubusercontent.com/32638459/203504674-1c063da7-0974-45d5-9222-3fc5f0e4d5d5.png)

![image](https://user-images.githubusercontent.com/32638459/203502227-de863f9f-8460-409c-b67e-91eb7465426b.png)
![image](https://user-images.githubusercontent.com/32638459/203502269-f0c0b8bc-ed0d-400f-be7b-f86ee01c2cff.png)

It can be run if it is forwarded through nginx tcp
![image](https://user-images.githubusercontent.com/32638459/203507186-bee06fcc-421f-4aa3-ae52-aa111ebb0b18.png)

**Describe the solution you'd like**
Only judge whether it is an ssl link, without parsing ssl, like [vaultwarden](https://github.com/dani-garcia/vaultwarden/wiki/Proxy-examples),

**Comment by Firstyear** [comment]
We have specifically chosen to enforce that load balancers / reverse proxies to kanidm must require TLS on that connection. 

This was due to multiple cases of user confusion where they did not know where or how TLS should be linked between the proxy and kanidm. The assumption that the network connection between the proxy and kanidm is secure is also not guaranteed to be true.

We consider that  having a singular, correct, secure configuration requirement, is more important that configuration flexibility and the risk of user mistakes.

**Comment by yaleman** [comment]
Aside from user confusion, running TLS between the load balancer and the service is best practice, especially for an identity management platform.

**Comment by ashkitten** [comment]
> This was due to multiple cases of user confusion where they did not know where or how TLS should be linked between the proxy and kanidm.

This seems like an issue with user education. The docs are rather vague when it comes to this point, and it took me a while to figure out that this feature was missing at all. I'm very used to configuring services to listen on HTTP with a reverse proxy terminating TLS in front; it's one of the most common configurations you see for webapps.

> The assumption that the network connection between the proxy and kanidm is secure is also not guaranteed to be true.

This is obviously something to point out when detailing security practices, but a properly educated system administrator should understand this distinction. I would even go so far as to assert that a system administrator that doesn't understand this distinction should not be trusted to properly deploy an identity management system.

> Aside from user confusion, running TLS between the load balancer and the service is best practice, especially for an identity management platform.

Why should I encrypt connections to localhost? In case someone pwns my virtual interfaces? Such an attacker would already have root access, or at least `CAP_NET_ADMIN|CAP_NET_RAW` and local execution. TLS isn't free, and it shouldn't be considered best practice to use it everywhere just because you can.

Besides that, using TLS gives me another certificate to manage (or reuse the same certificate as NGINX). Am I meant to use a self-signed certificate? Or copy the NGINX certs? (It's a good thing my distro has automated tooling for customizing the user/group permissions of ACME-generated certificates, but not all distros do this and it adds another route for user error.) Is it best practice to pin the upstream certificate in NGINX, so it won't connect to someone's man in the middle probe on my loopback interface?

As a compromise, maybe this could be changed to allow HTTP connections, but only if binding to a loopback interface. While this doesn't account for proxying over VPNs (which have their own encryption; no need to bring our own), it would at least work for my simple use-case. Alternately, NGINX supports proxying to UNIX domain socket upstreams, which have even lower overhead than TCP.

**Comment by Firstyear** [comment]
> > This was due to multiple cases of user confusion where they did not know where or how TLS should be linked between the proxy and kanidm.
> 
> This seems like an issue with user education. The docs are rather vague when it comes to this point, and it took me a while to figure out that this feature was missing at all. I'm very used to configuring services to listen on HTTP with a reverse proxy terminating TLS in front; it's one of the most common configurations you see for webapps.

It's rather vague *now* because we made a lot of changes to the docs after we had all these issues.

> 
> > The assumption that the network connection between the proxy and kanidm is secure is also not guaranteed to be true.
> 
> This is obviously something to point out when detailing security practices, but a properly educated system administrator should understand this distinction. I would even go so far as to assert that a system administrator that doesn't understand this distinction should not be trusted to properly deploy an identity management system.

We would rather have defaults that are *impossible* to get wrong, rather than rely on someone to "know what they are doing".

> 
> > Aside from user confusion, running TLS between the load balancer and the service is best practice, especially for an identity management platform.
> 
> Why should I encrypt connections to localhost? In case someone pwns my virtual interfaces? Such an attacker would already have root access, or at least `CAP_NET_ADMIN|CAP_NET_RAW` and local execution. TLS isn't free, and it shouldn't be considered best practice to use it everywhere just because you can.

If someone on localhost has root and cap-net then you are so far pwned that nothing we do would matter anyway btw. 

> 
> Besides that, using TLS gives me another certificate to manage (or reuse the same certificate as NGINX). Am I meant to use a self-signed certificate? Or copy the NGINX certs? (It's a good thing my distro has automated tooling for customizing the user/group permissions of ACME-generated certificates, but not all distros do this and it adds another route for user error.) Is it best practice to pin the upstream certificate in NGINX, so it won't connect to someone's man in the middle probe on my loopback interface?

That's for your to decide. There is no issue with self signed certs provided that the client (nginx here) pins the self-signed CA which would prevent MITM etc. 

Or as you say, re-use the nginx cert. I see no issue there with that either. 

> 
> As a compromise, maybe this could be changed to allow HTTP connections, but only if binding to a loopback interface. While this doesn't account for proxying over VPNs (which have their own encryption; no need to bring our own), it would at least work for my simple use-case. Alternately, NGINX supports proxying to UNIX domain socket upstreams, which have even lower overhead than TCP.

First, while the VPN may be encrypted, http only via localhost here wouldn't be a secure context because the browser would be using http not https so this would still need some other layers to actually add TLS anyway. 

Second, we have had unix socket requested before and we are currently thinking about it, but right now it's also not a compelling feature either. 

For now, our view is that TLS is a hard requirement for TCP based connections, both HTTPS and LDAPS, and that were we to allow a non-TLS connection, it would likely be extremely limited (ie the unix domain socket). I don't think allowing localhost to have "special rules" is worth us pursuing.

**Comment by ashkitten** [comment]
> We would rather have defaults that are impossible to get wrong, rather than rely on someone to "know what they are doing".

> That's for your to decide. There is no issue with self signed certs provided that the client (nginx here) pins the self-signed CA which would prevent MITM etc.

These two statements seem to conflict with one other. How can it be that the defaults are impossible to get wrong if it also requires NGINX to be correctly configured to make it optimally secure? And if NGINX needs to be correctly configured, why not kanidm?

Depending on correct NGINX configuration also seems risky when there is currently no documentation in kanidm for setting it up with NGINX. Are reverse proxies considered second-class? Most servers I run host multiple services on the same DNS name/IP address, so a reverse proxy is necessary.

> First, while the VPN may be encrypted, http only via localhost here wouldn't be a secure context because the browser would be using http not https so this would still need some other layers to actually add TLS anyway.

My point was meant to be about browser -> NGINX -> VPN -> kanidm, but indeed if you are using HTTP over a VPN (browser -> VPN -> kanidm) then you shouldn't need TLS either because the connection can't be MITM'd, as long as there is never a HTTP-only connection over the public internet (unless there is privileged malware on the user's machine, which to refer to your own words again would mean they are so far pwned there's nothing we can do anyways).

> For now, our view is that TLS is a hard requirement for TCP based connections, both HTTPS and LDAPS, and that were we to allow a non-TLS connection, it would likely be extremely limited (ie the unix domain socket). I don't think allowing localhost to have "special rules" is worth us pursuing.

Referring to your point earlier about defaults, I don't see how having secure defaults necessarily excludes the possibility of escape hatches for people who want greater control and understand the risks.

It did just occur to me while writing this that another option could be to only allow unencrypted connections if `X-Forwarded-For` is set (and trusted). What do you think of this?

**Comment by Firstyear** [comment]
> > We would rather have defaults that are impossible to get wrong, rather than rely on someone to "know what they are doing".
> 
> > That's for your to decide. There is no issue with self signed certs provided that the client (nginx here) pins the self-signed CA which would prevent MITM etc.
> 
> These two statements seem to conflict with one other. How can it be that the defaults are impossible to get wrong if it also requires NGINX to be correctly configured to make it optimally secure? And if NGINX needs to be correctly configured, why not kanidm?

How do they conflict? 

TLS is required for secure communication. Kanidm always requires TLS. Nginx then must configure TLS between itself and Kanidm in some fashion. Self signed certs between nginx and Kanidm in valid/secure provided that nginix correctly pins the CA cert. 

The alternate that is insecure, is no TLS between nginix and Kanidm, and they do not reside on the same machine. 

> 
> Depending on correct NGINX configuration also seems risky when there is currently no documentation in kanidm for setting it up with NGINX. Are reverse proxies considered second-class? Most servers I run host multiple services on the same DNS name/IP address, so a reverse proxy is necessary.

I think that both @yaleman and I run Kanidm behind a reverse proxy, so I would not consider reverse proxies second class. They are a common component in enterprise networks as well, so we have considered them quite a lot actually. 

> My point was meant to be about browser -> NGINX -> VPN -> kanidm, but indeed if you are using HTTP over a VPN (browser -> VPN -> kanidm) then you shouldn't need TLS either because the connection can't be MITM'd, as long as there is never a HTTP-only connection over the public internet (unless there is privileged malware on the user's machine, which to refer to your own words again would mean they are so far pwned there's nothing we can do anyways).

You can't do this. Webauthn in browsers will only activate if the connection is considered a secure origin, which means that it must be HTTPS. Some browsers (namely safari) do NOT consider localhost a secure origin either BTW. 

This is another reason why we force TLS.

> Referring to your point earlier about defaults, I don't see how having secure defaults necessarily excludes the possibility of escape hatches for people who want greater control and understand the risks.
> 
> It did just occur to me while writing this that another option could be to only allow unencrypted connections if `X-Forwarded-For` is set (and trusted). What do you think of this?

We used to have the escape hatches. They were a source of problems. We removed them. Ever since then we have seen a sharp drop in the number of people with issues with load balancers/reverse proxies and TLS configuration/setup. We aren't going to put them back in.

The only "escape" hatch I would consider today is unix domain sockets as an alternate to TLS+TCP, since UDS are "as secure" as TLS.

**Comment by yaleman** [comment]
My setup runs both through and past a reverse proxy but shows it's not only possible but relatively simple.

- Letsencrypt cert which has both the internal and external hostnames.
- "Internal" hostname points directly at the Kanidm server for system auth and LDAPS.
- External access uses a CloudFlare tunnel from another host. `cloudflared` validates the connection to the "external" hostname over SNI so host headers get passed through easily and TLS is maintained.

I previously had it running with a layer of NGINX in the middle and all it took was to point at the LetsEncrypt cert for both layers.

As far as my opinion on the topic, "secure by default" is the mantra. TLS costs nothing, and supporting more transports costs *us* time in support, testing and troubleshooting, which is also a big factor.

If someone wants to build out the UNIX socket support and include a full client/test suite then reach out and we can help make that happen, but an implementation by the project won't be a priority (there's far too many other *necessary* features!)  and HTTP is still a hard no.
