### ISSUE TITLE
LDAP search for `*` and a virtual attribute like `mail;primary` doesn't return the virtual attribute

### ISSUE THREAD

**Issue by jceb** [kanidm/kanidm#1301]
### I did this

Set up a user `dummy` with an email address + a service account that is allowed to search for virtual attributes.

Then I executed this search, however it didn't return the `mail;primary` attribute:

```bash
ldapsearch -D dn=token -y tokenfile name=dummy mail;primary '*'

# dummy@idm.41ppl.com, idm.41ppl.com
dn: spn=dummy@idm.example.com,dc=idm,dc=example,dc=com
class: account
class: memberof
class: object
class: person
displayname: Dummy user
mail: dummy@example.com
memberof: spn=idm_all_persons@idm.example.com,dc=idm,dc=example,dc=com
memberof: spn=idm_all_accounts@idm.example.com,dc=idm,dc=example,dc=com
name: dummy
spn: dummy@idm.example.com
uuid: 37c14edb-2957-41d8-9f42-9b12a84141fc
```

### I expected the following

The `mail;primary` attribute to be part of the results.

### Kanidm version (and git commit)

[kanidm(d) --version]

kanidmd 1.1.0-alpha.11-dev

### Operating System / Version

Linux kanidm-0 5.15.81 #1-NixOS SMP Fri Dec 2 16:41:12 UTC 2022 x86_64 Linux

### Any other comments

When I remove `*` from the query the virtual attribute is returned without issues. Furthermore, when I add `+` it also returns the virtual attribute + all other virtual attributes.

**Comment by Firstyear** [comment]
https://github.com/kanidm/kanidm/blob/master/kanidmd/lib/src/idm/ldap.rs#L223

Looks like its due to this code here, where when we see all-attrs, we dont process the other requested attributes. 

Per rfc4511 this would be a bug https://www.rfc-editor.org/rfc/rfc4511#section-4.5.1.8

So i think the code in this area may need some changes to fix this expression, but step 1 will be a testcase to show the problem.
