### ISSUE TITLE
External database?

### ISSUE THREAD

**Issue by stellanhaglund** [kanidm/kanidm#1306]
Is there a way to use an external database like postgres instead of the bundled SQLite?

**Comment by Firstyear** [comment]
It's not, because we don't use the database in the way a traditional application does.

We are simply using sqlite as a KV-store, and we actually implement our own database "on top". We chose sqlite due to it's reliability and portability.

To use something external like pgsql will only add complexity, won't change performance (since it's the kani cache and query layers that actually do the work) and may in fact break the system because the kanidm caches are local to a single node and if you have many kanidm to one DB you will end up with a broken inconsistent database. 

We've had this question a few times, and I think it's because people see "sqlite" in the config files and go "oh that's not a real production db, le'ts use pgsql". I think we might need to change the config options to *remove* any mention of sql at all and just call it "datastore" and keep the fact it's sqlite hidden so that this doesn't come up. @yaleman thoughts?

**Comment by yaleman** [comment]
> I think we might need to change the config options to remove any mention of sql at all and just call it "datastore" and keep the fact it's sqlite hidden so that this doesn't come up. @yaleman thoughts?

Or just make it an FAQ item and point people at it? 😃 Either way, the datastore's going to be SQLite, changing the config options aren't going to hide it *that* much?

**Comment by stellanhaglund** [comment]
For me it's not that I don't think SQLite could be used in production, I think it's more that I don't see the architecture and usually prefer to be able to run the database in a hosted service rather than hosting it myself, and also I was hoping that I would be able to run this in a serverless manner as opposed to keycloak and fusionauth for example. 

But do you have any drawing of the architecture?

**Comment by Firstyear** [comment]
@stellanhaglund The way you should think about kanidm is similar to something like pgsql, 389-ds, openldap, active directory. You can't use an external database because kanidm *is* the database. So we can't operate in a "serverless" environment, because kanidm *is* the store of state. 

There are some architecture diagrams in the developer docs, but it's more about the internals rather than "how do we connect to sqlite" since that's a trivial detail in the scope of Kanidm.

**Comment by stellanhaglund** [comment]
Ok thanks for the information! 
So the instance is self-contained into one binary then, there's no clustering needed or stuff like that?
Apart from if you need multiple instances I mean. 

Not related to the main question but I read that there is a self-service ui, but no admin-ui available if I understand it correclty?

**Comment by Firstyear** [comment]
> Ok thanks for the information! So the instance is self-contained into one binary then, there's no clustering needed or stuff like that? Apart from if you need multiple instances I mean.

Clustering will come in a future update for high availability, but otherwise it's a single binary (monolith). The reason is because I previously have worked on "microservice" IDM projects and they had significant issues with quality and testing that made it near impossible to create a reliable system. 

> 
> Not related to the main question but I read that there is a self-service ui, but no admin-ui available if I understand it correclty?

That's correct, an admin ui is "in the works" but currently disabled by default.

**Comment by Zorlin** [comment]
Would love to see clustering/HA, it's the only reason I wanted to use anything but SQLite. Thanks!

**Comment by Firstyear** [comment]
@Zorlin It's being worked on! :)

**Comment by Zorlin** [comment]
awesome! Yeah, I gathered that. I was basically saying "yes please, thank you!!"

**Comment by thomasdba** [comment]
waiting for PG as external database...

**Comment by Firstyear** [comment]
@thomasdba I have explained before that this can never, and will never happen. We can never have an external DB. Please don't confuse our use of sqlite with "we can just drop in another sql database".  Kanidm *is* the database. It has it's own caches and query layer. It can not "shared" sql backends for multiple servers. That would fundamentally corrupt and destroy your data. It would be horrendously slow. 

We use sqlite as a k-v store because of sqlites excellent consistency guarantees. That's all. 

The correct way to think about this is not that we use sqlite, but that we have a "custom backing store" where we have our own database and query system on top. You can't just swap out that backing store.

**Comment by thomasdba** [comment]
that is different, for the whole infrastructure, i don't want another kind of db to maintain.

**Comment by yaleman** [comment]
@thomasdba, if having an SQLite storage layer included in the product at all is a blocker, then this might not be a suitable system for your needs.
