### ISSUE TITLE
Rework default access controls

### ISSUE THREAD

**Issue by Firstyear** [kanidm/kanidm#1481]
Our current access controls were good as an initial baseline, but they have shown that the original model isn't really what we want to stick with - it has a fair few rough edges and will limit our ability to change acp's in the future.

I think we should rework our default access controls such that the current privilege groups retain their meaning but we have better seperation of system admin elements vs bootstrap/emergency access admin. This will allow better separation of privilege by default which users in smaller deployments can "merge" if they wish.

**Comment by tumbl3w33d** [comment]
I had a conversation with @Firstyear about the fact that currently you can list existing groups and their users without having any special privilege. I consider this problematical from a data privacy perspective, especially for use within the scope of GDPR (European Union + friends). Rationale:

Imagine a company (i. e., a party hosting kanidm) with a mixed user base – employees, freelancers, partners, customers etc. Any of these users is currently able to get a list of all customers of that company (bad) and their respective members' names (ugly). In my view this should not be the default (data avoidance/minimization) but it must at least be configurable.

The general idea of the GDPR as simplified summary: You need to actively inform your users what data you store, where you store it, who has access to it and why you store it. While it is perfectly valid to tell my customer that I store his name and relationship to his company in order to give him access, e. g., to our common communication platform, it would be awkward (and in fact not justifiable) to tell the customer A that customer B can see this information to without any reason that would justify it (implementation shortcomings of an application don't count, unfortunately).

@Firstyear 's first thought on it was that it's probably not necessary to expose this information, because "a lot of access control is calculated by memberof". He expects problems with the unix client that reads posix groups and relies on anonymous access. I am not familiar enough with this aspect, but my spontaneous question would be – why can't this client use a service account with appropriate privilege assignment?

Btw: if you feel like want to earn the "100% GDPR-compliant" badge, this [checklist](https://gdpr.eu/checklist/) might help. In fact, nobody in EU may legally process data without adhering to these requirements, so this is a very relevant USP, especially for commercial use.

**Comment by Firstyear** [comment]
> why can't this client use a service account with appropriate privilege assignment?

Because today we haven't added support for that - we have been trying to avoid "domain joining" of machines with service-accounts for a long time, but there are some upcoming features that will need them, so we have to do it eventually.

**Comment by Firstyear** [comment]
> their respective members' names (ugly).

This isn't true, legalname is hidden by default :)

**Comment by Firstyear** [comment]
So I want to cover in a longer form what the issue is here.

Currently the access controls we have are very good - but they are not easy to *administer*. This leaves people often using our defaults without the ability to easily add/remove themself from the roles needed. This was an issue in the past for a user wanting to expose mail addrs to service accounts, but also @tumbl3w33d here has noted their own use cases. It's also not clear to admins what the access controls are by default either. 

Part of this is that a number of the access rules we have at the moment are too coarse. An example is E_IDM_ALL_ACP_READ_V1 which really is encompassing multiple roles - the ability to read posix attributes for service accounts, the ability for users to query a directory for persons / groups, and for anonymous to make a certain number of queries to assist in pre-auth steps. Similar rules like PEOPLE_MANAGE are too coarse by not only allowing creation but also write and delete, which prevents the creation of service accounts that can just create users (think self-sign up portal which has a service account that's allowed to do a one-time create of a user - it only needs to create and then move on).

So the goal here is to make these access rules more finegrained. We can then assemble the "coarser" roles by combining the memberships via group memberships due to our nested memberof implementation.

The second goal is to improve the default "coarse" roles out of the box. Currently I believe a lot of sites are likely using admin/idm_admin "too much" when these are probably intended as setup-only or break-glass accounts. This is again because we haven't advertised well how to add users to access groups to grant them the rights they need.

Currently if we were to draw this:

```
                  ┌────────────┐              ┌────────────┐
                  │            │              │            │
       ┌──────────│   Admins   │───Manages───▶│ IDM Admins │
       │          │            │              │            │
       │          └────────────┘              └────────────┘
       │                 │                           │      
   Manages               │                           │      
       │             Manages                     Manages    
       │                 │                           │      
       ▼                 ▼                           ▼      
┌────────────┐    ┌────────────┐              ┌────────────┐
│            │    │            │              │            │
│   Groups   │    │   System   │              │  Persons   │
│            │    │            │              │            │
└────────────┘    └────────────┘              └────────────┘
```

We can also see here that system admins are a bit unbounded today, they can manage and change any group and so can always priv esc to anything they want. This is less true of idm_admins at least. 


To improve this, the coarse roles I have in mind are

* admins - users who can administer the kanidm instance and it's settings / integrations including service-accounts
* idm_admins - users who can administer all persons in the directory
* helpdesk - users who can assist other users with credential resets and view information about these accounts. Must not be able to alter users who have system/high privileges. Can't view PII
* person-helpdesk - similar to above, but for helping manage PII related attributes on users. *can* view and read PII of high priv accounts.
* posix-service-account - service account rights to read posix users and groups
* directory-search - ability for users to search for other users / groups in the system (think phone book). Doesn't include PII.
* posix-admin - ability to extend and manage users/groups to support posix attributes.
* radius-servers - can read user information and radius secrets
* mail servers - can read user information and mail addrs
Each of these will be built from smaller rules.

I think an important coarse-role I am omitting here is "group admin". This is because I want to remove the blanket group admin roles in favour of "managed by" style rules. This will change how we create groups because we will need to have group creates always declare a "managed by" group during the create. We may still need a group-admin rule for "break-glass" though. 

The reason I want managed by rules is to prevent access control proliferation where we have an access control - per - group we make to define who controls it. It also is to limit target proliferation too. If done properly the result should be:

```
┌────────────┐    ┌────────────┐                   
│            │    │            │                   
│   Admins   │    │ IDM Admins │────────────┐      
│            │    │            │            │      
└────────────┘    └────────────┘            ▼      
       │                 │           ┌────────────┐
       │                 │           │            │
   Manages           Manages         │  HelpDesk  │
       │                 │           │            │
       ▼                 ▼           └────────────┘
┌────────────┐    ┌────────────┐            │      
│            │    │            │            │      
│   System   │    │  Persons   │◀───────────┘      
│            │    │            │                   
└────────────┘    └────────────┘                   
```

I want admins of the system to be seperate from idm admins to prevent this kind of side stepping. 

I think to proceed here we need:

* #249  
* A migration to create managed by attrs on all groups by default. 
* possibly #1118 will be involved in managed by.
* #117 will be nice here too to help admins with working out how access controls eval.
* Write some tests to assume a malicious user in various roles to check they can't side step.

This will also hopefully resolve #1222 since we'll be more clearly documenting our acis here.

**Comment by Firstyear** [comment]
Saying this, I think this will have to happen in august because it's a big change that will touch a lot of the code base :)

**Comment by tumbl3w33d** [comment]
I'd like to add some anecdotes of my break-glass journey.

>  So the goal here is […] We can then assemble the "coarser" roles

Yes, loving that part and I had the same idea before reading it here.

> The second goal is to improve the default "coarse" roles out of the box. Currently I believe a lot of sites are likely using admin/idm_admin "too much" when these are probably intended as setup-only or break-glass accounts. This is again because we haven't advertised well how to add users to access groups to grant them the rights they need.

The last part it what matters here to me. My biggest obstacle leaving the break-glass accounts behind was the overwhelming amount of privileges in combination with the separation between `hp`-things and regular privileges. On top there's the differentiation `read`, `write`, `manage` and `extend` in the current ACPs and while the first two feel intuitive to me, I have no idea what the other two are for. The roles you proposed would help with this a lot though, because I probably don't need to know these details. There is also a confusing naming involved with `people` probably targeting `persons` and `account` probably targeting `service-account`s, but I think this confusion could be avoided.

Additional idea: Wouldn't it make sense to hide privileges (i.e., discourage accounts being assigned straight to privileges) as much as possible and push people towards using/creating roles? I could even imagine an API behavior like getting a 400 when I try to assign an account straight to a privilege, unless the requester adds a `force_because_I_know_better` flag (payload attribute/query parameter). In the CLI you could add an interactive "you sure?"-warning. For the pros you could offer completely disabling this safety net via app config. It's a bit like what you currently do with the `raw` approach.

Another thing I was afraid of when creating my own successors of `admin` and `idm_admin` was that I was actually aware that you make a difference for reasons and I was afraid I would accidentally break this separation. So what I did was adding my new accounts to the existing `system_admins` and `idm_admins`, actually just replicating the default accounts not knowing if I win anything. I'm personally planning to move from there once I have a better understanding OR there are these roles available.
For the way I configure kanidm (declarative via ansible/yaml) I actually want a quite powerful account and the separation between the two made my logic more complicated (which is fine if I actually win anything here), but I solved it by sticking with the break-glass idea (the default accounts bootstrap the system with my successors) and then the play yells at the operator there are default accounts in use and they should stop doing that. Apart from that I just need the role you called `helpdesk`/`person-helpdesk` for my operator crew.

> We can also see here that system admins are a bit unbounded today

In a way yes, but then there is this weird behavior that you cannot, for example, reset credentials of a service account with regular privilege level (i.e., non-hp). The more I think about it, the more it feels like a bug to me, because of the hierarchical experience (will describe below) I am used to from other applications.

> idm_admins - users who can administer all persons in the directory

I think the naming is unfortunate. If all the `idm_admin` can do, or let's say if that is their purpose, why is it not called `person_admin`? And the other `admin` naming causes a super-admin feeling in my head (based on experience), although it can actually not touch persons, but is meant for configuring the system, so it should probably be named `system_admin` instead. That it's currently used for modifying groups might make `site_admin` more appropriate, but you have a better language feeling as native speaker.


> we will need to have group creates always declare a "managed by" group during the create. We may still need a group-admin rule for "break-glass" though

Would there be the option to flag a group as managed by `self`? I've put my (`idm_`)`admin` successors in a group called `idam_management` which I use as target for the `idm_all_acp_read` ACP and when we think of (`idm_`)`admin` being deleted/disabled after the break-glass moment, there's actually nothing above in the hierarchy to manage the group of my top administrative accounts.

> I want admins of the system to be seperate from idm admins to prevent this kind of side stepping

I don't understand the background of why `admin` and `idm_admin` (to stick with the current naming), or let's say `system_admins` and `idam_admins` (their "role" names) are separate administrator accounts for different purposes. There probably is a rationale, but I must admit I didn't get it from what I read so far. It for sure feels different from most/all other apps I know. Usually there's a directional hierarchy of something like a "super admin" which can do absolutely everything. Some apps limit this account to config tasks, so you cannot do everyday business like viewing regular content and working with the app, simply to avoid people using this like a normal account.

Then one step down the hierarchy you usually have some kind of "manager" role with reduced privileges, just managing assets, not touching the system config.

I'm not saying this is where kani should go. My point is that it's important to explain that it's not a hierarchy here and point out why it's not. Appropriate naming of such accounts/roles is key (see above).

---

I am not sure about two specific privileges:

1) If I want to change the mail of an account that's part of `idm_admins`, I get `requested_pres: {"mail"} !⊆ allowed: {"account_expire", "account_valid_from", "api_token_session", "class", "devicekeys", "displayname", "gidnumber", "loginshell", "name", "passkeys", "primary_credential", "ssh_publickey", "unix_password"}`, even when the executing account is part of `system_admins`. Is `idm_hp_people_write_priv` what I want? It at least avoids this problem. If so, it might be wrong that currently explicitly `admin` has this privilege by default and not `system_admins` (where I added my successor).

2) Is it a bad idea to grant my successor of `idm_admin` `idm_hp_people_read_priv`? I did that so my config playbook using my `idm_admin` successor can notice that my privileged operator persons already have their correct e-mail configured and nothing needs to be done. Without that privilege it thinks there's no mail set because it cannot see anything and tries to update which fails for obvious reasons.

It is possible that this question (that I just took off my notes) is from a time where I completely disabled the `idm_all_acp_read` default and meanwhile I've switched to not disabling it but modifying its `acp_receiver_group` to target my config management account group `idam_management`. That should achieve the same and I can possibly remove this `idm_hp_people_read_priv` again which I explicitly added earlier for that use case.

**Comment by yaleman** [comment]
If you need to be able to read their members, then you need access to *resolve* those members from UUID to name, so you'll end up with access to read that member's details - so it's essentially "read all non-private data" realistically at that point.

**Comment by Firstyear** [comment]
Yep, that's correct - to read group members you have to be able to read a certain amount about the members of that group too. So group member reading will always come with some limited ability to read non-private info about users.

Otherwise thanks for the feedback - I think you're pretty much agreeing with us. The access we have is "evolved" and the original ideas are breaking at the seams a bit and we need to step back and rethink some things.

Anyway, if you want the background on the original ideas, it's above.

For the "only add to this if you really mean it" idea, I'm not sure about that. I think the better approach would be to structure the "fine grained" rules as access-control profiles only, with multiple inheritors rather than inheriting to a group. So that way you would have all the small rules build to a "coarse" role. This has the benefit of cleaning up the "memberOf" sprawl we currently have with things like admins/idm_admins, which end up in about 20 groups because of all the different permissions they inherit.

The other approach is that rather than the access controls nominating which groups inherit them, we have groups "claim" an access control. That has some security risks though, because then the ability to modify a groups access-claims means you can priv esc to whatever you want, but we already have a similar risk with the ability to alter/modify access controls anyway.

Graphically what we have now is:

```
┌────────┐       ┌──────────┐     ┌────────────┐      ┌──────────┐
│  ACP   │──────▶│Fine Group│──┬─▶│Coarse Group│─────▶│  Member  │
└────────┘       └──────────┘  │  └────────────┘      └──────────┘
                               │                                  
┌────────┐       ┌──────────┐  │                                  
│  ACP   │──────▶│Fine Group│──┘                                  
└────────┘       └──────────┘                                     
```

We could do this as acps having multiple receivers:

```
┌────────┐     ┌────────────┐      ┌──────────┐
│  ACP   │──┬─▶│Coarse Group│─────▶│  Member  │
└────────┘  │  └────────────┘      └──────────┘
            │                                  
            │  ┌────────────┐      ┌──────────┐
            └─▶│Coarse Group│─────▶│  Member  │
               └────────────┘      └──────────┘
```

Or we have groups "claim" an access control.

```
┌────────┐     ┌────────────┐      ┌──────────┐
│  ACP   │◀─┬──│Coarse Group│─────▶│  Member  │
└────────┘  │  └────────────┘      └──────────┘
            │                                  
┌────────┐  │                                  
│  ACP   │◀─┘                                  
└────────┘                                     
```

I think in terms of "administration" having groups claim an access control makes a nice admin experience so that viewing a group shows everything that it has the access to. That's why we did fine grained groups originally to show everything in memberOf, but it makes it hard to see because of noise.

Just some more ideas here, but I think a good design doc will be needed to settle things.

**Comment by Firstyear** [comment]
The benefit of the "back link" to an ACP approach is that you can have a seperate level of privilege for "assign a member to X coarse group" compared to "assign an ACP to this coarse group". That way it naturally encourages people to assign to the correct coarse priv group, rather than assigning groups to ACP's. It also allows combination of existing ACP rules into new groups that users can control and decide on too.

**Comment by yaleman** [comment]
Separate issue asking for it to be looked at please - will need to map out the required setup for it and naming.

BTW, `idm_people_read_priv` gives *private* data access so you probably don't want that.

**Comment by favalos** [comment]
Per @Firstyear suggestion in gitter I am adding my comment.

I want to generate service accounts and use kanidm for administration, since I am planning to use kanidm I would like to the able to use the out of the box functionality that is available from admin and idm_admin to generate passwords. Looks like this is not possible currently.
