### ISSUE TITLE
Make LDAP base DN configurable

### ISSUE THREAD

**Issue by NexZhu** [kanidm/kanidm#1496]
**Is your feature request related to a problem? Please describe.**

The default LDAP base DN is derived from domain = "idm.example.com" in server.toml. So if the domain is idm.example.com then it will be dc=idm,dc=example,dc=com.

Maybe the LDAP base DN should be configurable in some extent.
I think the root domain name like `company.com` is often used for organization homepage, so a second level domain like `idm.company.com` will be used for the LDAP server. But LDAP base DN is commonly just the organization root domain name like `dc=company,dc=org`

**Describe the solution you'd like**

Add an option to configure the LDAP base DN.

**Additional context**

https://github.com/kanidm/kanidm/issues/1483

@Firstyear

**Comment by NexZhu** [comment]
I've just followed the [installation guide](https://kanidm.github.io/kanidm/stable/installing_the_server.html) to setup the server, I'm not aware of `domain config` you mentioned, aside from the `domain = "idm.example.com"` in `server.toml`, point me to some links?

**Comment by Firstyear** [comment]
It's in here https://kanidm.github.io/kanidm/master/server_configuration.html and relates to https://kanidm.github.io/kanidm/master/domain_rename.html

It's the "domain =" parameter in server.toml.

**Comment by NexZhu** [comment]
Yeah I know this one, I get what you meant by `For the dn to be part of server.toml` and I think it'll work.
I'm not sure what's the other option `Or for it to be in the domain config?` you've mentioned?
It there another configuration source for domain config aside from `server.toml`?

**Comment by Firstyear** [comment]
Storing the value into the database itself. This way it's replicated between all servers so they have the same ldap base dn :) means you only have to set it "once" into the database (same as a password badlist update). Where the server.toml you have to set on "each server".

**Comment by NexZhu** [comment]
I get it. What will happen if the `domain` configs differ between replications?

**Comment by Firstyear** [comment]
For the domain parameter we'll be blocking repl until the domain value in server.toml is consistent.

But for ldap basedn then it doesn't really matter if the servers are inconsistent, beside that it might be an annoying user experience.

**Comment by NexZhu** [comment]
I suggest LDAP basedn be set in `server.toml` along side of `domain` and should be guaranteed to be consistent jusk like `domain`.

**Comment by Firstyear** [comment]
I am honestly thinking the same. I think it will be easier for administration and still enforceable at run time by servers. I think it will also be easier to code into the server too.

**Comment by yaleman** [comment]
I think this goes back to the question we had when domain was being set in the config file - I'm not convinced the config file is the right place for it since it's a system-wide setting and needs to be static across all Kanidm hosts in the same domain.

As far as guaranteeing consistency, surely it's *harder* to guarantee this when it's in the config file?

Placement of the setting aside, what will we allow the configurations to be?
Given the domain `idm.example.com`, I believe we should *only* allow LDAP to be changed to one of `dc=idm,dc=example,dc=com` or `dc=example,dc=com` to avoid confusion/audit issues down the line - ie, only allow stripping prefixes.

**Comment by Firstyear** [comment]
> I think this goes back to the question we had when domain was being set in the config file - I'm not convinced the config file is the right place for it since it's a system-wide setting and needs to be static across all Kanidm hosts in the same domain.
> 
> As far as guaranteeing consistency, surely it's _harder_ to guarantee this when it's in the config file?

Well yes. But we ultimately chose that the domain name would be in server.toml rather than the db, and that it would have to be up to the admin to maintain that consistently. I think we still store the domain name in the db but it's reflects what's in the config of that server. 

> 
> Placement of the setting aside, what will we allow the configurations to be? Given the domain `idm.example.com`, I believe we should _only_ allow LDAP to be changed to one of `dc=idm,dc=example,dc=com` or `dc=example,dc=com` to avoid confusion/audit issues down the line - ie, only allow stripping prefixes.

well, the other thing is somepeople might just want to set dc=ldap or o=company instead. These would also be valid basedns. Even I look at mine (dc=idm,dc=blackhats,dc=net,dc=au) and I hate typing it, I'd probably change mine in a heartbeat to o=blackhats now I think about it. it would certainly make values like dn: spn=william@idm.blackhats.net.au,o=blackhats far nicer to look at / type. Plus I think the long dn's is a big turn off to many ldap users in the first place. 

I think I'm leaning toward store in the db right now because I think it's not like origin/domain which had a bootstrap issues that required server.toml. So I think having it set in the domain entry is the right place and then it's a onestop change.

But I think I'll enforce it only to be a dn (e.g. o=company or dc=foo,dc=bar). since it is valid for it to be other things outside of just dc.

**Comment by yaleman** [comment]
I've been talked down from my security-weeb ledge by @Firstyear and agree that as long as it's standard LDAP DN syntax then it'll be fine. 😄

So, default to the current format, then allow users to set a custom value in the DB?

**Comment by Firstyear** [comment]
yep, agreed. :)
