### ISSUE TITLE
Unable to retrieve data when using ldapsearch to set the memberof filter condition

### ISSUE THREAD

**Issue by ExplodingDragon** [kanidm/kanidm#1567]
Sorry, English is not my native language. My description may not be clear.

Unable to retrieve data when using ldapsearch to set the memberof filter condition

### I did this

```bash
ldapsearch -H ldaps://idm.d7z.net -b 'dc=idm,dc=d7z,dc=net' -x '(&(objectClass=posixAccount)(name=dragon))' memberof spn
```

![图片](https://user-images.githubusercontent.com/33776693/233895125-67838e67-4123-4058-8f89-39ad08345dc4.png)

![图片](https://user-images.githubusercontent.com/33776693/233895156-2dee340f-676a-4008-a12f-c2266d44e134.png)

![图片](https://user-images.githubusercontent.com/33776693/233895209-f07dcbba-317c-46c7-8c4d-0f92744205b7.png)

kanidm person list:

![图片](https://user-images.githubusercontent.com/33776693/233895307-97bc7d21-837f-457a-9b27-dba8be320eef.png)

kanidm log :

![图片](https://user-images.githubusercontent.com/33776693/233895788-6783fcbf-2c01-4b48-9406-eee38e19c900.png)

### Kanidm version (and git commit)

[kanidm(d) --version]

![图片](https://user-images.githubusercontent.com/33776693/233895504-df367d77-ad95-43ac-b2ba-a79e7f3a9e26.png)

![图片](https://user-images.githubusercontent.com/33776693/233895545-20e2fdce-9306-4cd9-a440-2b99f6d7d70a.png)

### Operating System / Version

![图片](https://user-images.githubusercontent.com/33776693/233895596-4947f960-4fa9-4ecc-9539-ba1e43c2fca1.png)

**Comment by yaleman** [comment]
Can you just try "memberOf=gitea_admin" - the full syntax looks ... wrong?

**Comment by ExplodingDragon** [comment]
> Can you just try "memberOf=gitea_admin" - the full syntax looks ... wrong?
> 
> This worked for me:
> 
> ```shell
> ldapsearch -H ldaps://example.com \
>   -b 'dc=example,dc=com' \
>   -x '(&(objectClass=posixAccount)(memberOf=posix_users))' \
>   memberof spn
> ```
> 
> Where I have a group called `posix_users`

![图片](https://user-images.githubusercontent.com/33776693/233908121-01797087-edd2-48fb-9326-a2a443b46d4d.png)

Yes it works

thanks.

**Comment by Firstyear** [comment]
@ExplodingDragon I think the issue here was the "spn=". I think that the correct syntax would have been "memberof=gitea_admin@domainname". What we present in the memberOf there is the "dn", so maybe there is a valid argument that we should accept dn's in the place where we accept reference types like this because people can - and will - copy paste like you did and it *should* work.

**Comment by Firstyear** [comment]
@yaleman So what's happening here is that when we go through the memberof=spn=foo@domain,o=domain path, we are putting that through name2uuid to try to resolve the reference to an absolute uuid which we can then search. So I think the "generic" way to fix this for all possible use cases is to have name2uuid store not just the name/spn, but also the rdn formats of these. This won't ever conflict since '=' is disallowed in names. Similar we also don't have to care about the "o=domain" part since we already have absolute names via the spn, so we can just split on ',' if it appears. I think this is actually a good thing since it lets us also be specific in kanidm level queries for spn=foo@blah or name=x. 

The only real drawback is "more data in an index" and that we need to do the ',' split on name2uuid calls which is meant to be a fast path. But I think the increase in usability and convenience is worth.

**Comment by yaleman** [comment]
I have feelings about putting LDAP-specific data in indexes for individual, but it's too rude to mention here. 🤔

**Comment by Firstyear** [comment]
I ended up not adding an index, I just strips the rdn/dn parts in the name2uuid lookup.
