### ISSUE TITLE
Install kanidm-unixd-clients on Ubuntu?

### ISSUE THREAD

**Issue by reesericci** [kanidm/kanidm#1805]
**Is your feature request related to a problem? Please describe.**

How do I install kanidm-unixd-clients for PAM auth on my Ubuntu server?

**Describe the solution you'd like**

`apt install kanidm-unixd-clients`

**Describe alternatives you've considered**

Downloading a .deb works too, or cargo

**Additional context**

There's only instructions for Fedora and OpenSUSE on the docs site

**Comment by Firstyear** [comment]
@yaleman - I think you know where the .debs are?

**Comment by yaleman** [comment]
The auto-generated .deb files based on `master` are here: https://github.com/kanidm/kanidm/releases/tag/latest

Otherwise there's scripts to generate them yourself, if you want to do so from specific Kanidm releases.

I haven't the time to fight through the politics involved in getting kanidm packages into the various distributions 😱

**Comment by reesericci** [comment]
Are the built debs still around for the latest release? (1.1.0-alpha.12)

**Comment by yaleman** [comment]
No sorry, we haven't been generating them for tagged releases as they're far too untested.

**Comment by Firstyear** [comment]
@reesericci You could checkout the .12 branch and build the .deb locally?

**Comment by Firstyear** [comment]
@reesericci How did you go with this?

**Comment by yaleman** [comment]
Feel free to reopen this or a new issue if you need additional help
