### ISSUE TITLE
Configurable session timeouts

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#1939]
**Is your feature request related to a problem? Please describe.**

Currently, session timeouts are hard-coded at compile time, 3600 seconds (1h) for a normal token, 600s (10min) for "elevated" or write access.

**Describe the solution you'd like**

Allow it to be configurable at a stystem level, changeable by admin-level users, stored as a value in the database.

**Describe alternatives you've considered**

Allow it to be set in the server config file

**Additional context**

**Comment by yaleman** [comment]
As raised by @tumbl3w33d in Matrix ❤️

**Comment by tumbl3w33d** [comment]
I want to add my (possibly flawed) understanding of the point of limiting the session lifetime to a maximum. Maybe others share it and can be enlightened as well.

Let's say I have an application that uses OAuth authentication via kanidm. My application has its own session and I can configure its timeout. Let's say it's a highly sensitive application and I set the session lifetime to 5min. After the 5 minutes my application logs the user out. If he wants to keep using the application, he would click "login via kani" again and the roundtrip would log him in again without him being force to authenticate in kani again, because the session there lives much longer.

Currently I seem to have no option to limit the kani session lifetime, when my aim is to force a reauthentication at least once per x (day, hour,…).

Another thought, which might be confusing/misleading/unrelated, but I will add it here and you are free to ignore it: Let's say I have a system that knows when and from what country my user Bob usually works with my infrastructure . Now I see Bob trying to use the infrastructure at strange times from the other end of the world. Would there be a way for my surveillance system to invalidate the kani session via API, forcing a reauth or does that somehow not make sense within the idea of OAuth?

**Comment by yaleman** [comment]
I'd definitely say it'd be a `system_config` setting rather than the other options.

**Comment by tumbl3w33d** [comment]
Thank you for your work on this @Seba-T !

**Comment by Seba-T** [comment]
My pleasure :)

**Comment by Firstyear** [comment]
> Currently I seem to have no option to limit the kani session lifetime, when my aim is to force a reauthentication at least once per x (day, hour,…).

I'm going to point out though, that this is an anti-practice to force frequent re-auths like this. A user authenticates to a device, and that device then authenticates them. There is no-longer a seperation between the "browser session" and "the device the user is on". From a security standpoint you should consider them the same. That's why Kani had long sessions is because you authenticate to the device, then the device represents "you". We can strongly create that binding with cryptographic auth for example, but machine policy/security is an org thing too. 

> 
> Another thought, which might be confusing/misleading/unrelated, but I will add it here and you are free to ignore it: Let's say I have a system that knows when and from what country my user Bob usually works with my infrastructure . Now I see Bob trying to use the infrastructure at strange times from the other end of the world. Would there be a way for my surveillance system to invalidate the kani session via API, forcing a reauth or does that somehow not make sense within the idea of OAuth?

Yes, that is a feature we have considered, but it would be separate to this.
