### ISSUE TITLE
Shortcut for authenticating with the API?

### ISSUE THREAD

**Issue by tumbl3w33d** [kanidm/kanidm#1940]
I am using the kanidm API to programatically modify the assets in there. With the latest release, the initial authentication got more complicated. Before, I just created a session by POSTing to /v1/auth (init: username). Then a second POST initiated the authentication (begin: password) and a third POST (cred: password) actually logged me in and I could start operating.

In the newest version this leaves me with a read-only session. I found out that I need to use the /v1/reauth endpoint to escalate privileges, but this means I need 2 more requests. First I POST (token: null, which I found weird). That gives me a new session ID, so the one I received a second ago is already obsolete and I continue with this one. Now I POST once more to /v1/auth (cred: password) using the new session as header.

It's the same behavior with the kanidm CLI. You login and if you want to make a write operation right after, you need to reauth, so you repeat your auth steps you did 5 seconds ago.

I understand the idea behind it and you are the experts on authentication. My question is: Is there no safe shortcut, like when initiating a session to tell the server "I'd like to start with a write session"?

Oh, and by the way: If I programmatically fire these 5 requests to initially auth, I always run into a timing error: `Ident session is not present in entry. Perhaps replication is delayed?`

I worked around that with a "sleep" statement in my script before talking to the reauth endpoint, but well…

**Comment by yaleman** [comment]
I'd agree that being able to start a "write" session from scratch should be possible at the API level, which would also avoid the session write delay issues.

From my understanding, the "session is not present" thing is because auth sessions are put into a queue to be stored, since they're not as "urgent" as more important system things, so in the grand scheme of things a write delay is OK.

**Comment by Firstyear** [comment]
Yeah, I think this is a reasonable extension/request. IMO we would bind the session expiry to the rw time though similar to what we do with admin/idm_admin today, rather than the current long session time  + short priv life. That way you can go straight to rw mode but you have a short session OR you have a long session with ro mode and possible paths to upgrade to rw.

Does that sound reasonable? I think it would work here for scripting since you don't need long sessions anyway.

**Comment by yaleman** [comment]
Yep, I'd say we could use the existing login endpoint, and allow another option in `AuthIssueSession` of `WriteToken`, since it "Allows requesting of the type of session that will be issued at the end if successful."

**Comment by Firstyear** [comment]
We'd add a new flag rather than "auth issue session" since that's an old hook for cookie vs token. :)

**Comment by Firstyear** [comment]
I think this could be good for @scabrero who wants to start to contribute to Kanidm :)
