### ISSUE TITLE
Failed to start server core

### ISSUE THREAD

**Issue by tumbl3w33d** [kanidm/kanidm#1942]
### I did this

I start kanidm as I always do locally
```bash
docker run --rm -it \
    -p 127.0.0.1:8443:8443 \
    -v ./data:/data \
    -u 1000:1000 \
    --name kanidm \
    kanidm/serve
```

### I expected the following

I expected the server to start, as it did the days/weeks before.

### What actually happened
```
1f6ae7b4-47c3-4aa4-b2e2-bdf7c106d139 INFO     ┝━ ｉ [info]: Removing expired auth session | session_id: fe9cec12-017c-4804-9fe6-7d5fc024730a
1f6ae7b4-47c3-4aa4-b2e2-bdf7c106d139 ERROR    ┝━ 🚨 [error]: UUID reference set size differs from query result size <fast path, no uuid info available> | event_tag_id: 1
1f6ae7b4-47c3-4aa4-b2e2-bdf7c106d139 ERROR    ┝━ 🚨 [error]: Post-Modify operation failed (plugin), Plugin(ReferentialIntegrity("Uuid referenced not found in database")) | event_tag_id: 1
1f6ae7b4-47c3-4aa4-b2e2-bdf7c106d139 ERROR    ┕━ 🚨 [error]: initialise_idm p3 -> result | event_tag_id: 1 | res: Err(Plugin(ReferentialIntegrity("Uuid referenced not found in database")))
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Unable to setup query server or idm server -> Plugin(ReferentialIntegrity("Uuid referenced not found in database"))
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to start server core!
```
### Kanidm version (and git commit)

kanidmd 1.1.0-beta.13

The data folder was created with the previous version.

### Operating System / Version

official container running on manjaro workstation

`Linux milkshake 6.1.41-1-MANJARO #1 SMP PREEMPT_DYNAMIC Tue Jul 25 09:17:30 UTC 2023 x86_64 GNU/Linux`

### Any other comments

I just shutdown the system in the evening, start it in the morning and get back to work. It's my local development system and I talk to it via API and CLI.

I probably wouldn't have reported it and would just blame myself for unclean shutdown or something. However, @Kranzes in Matrix ran into the same issue when upgrading from previous to latest version on his Nix system. He downgraded, I nuked my data folder and started over. But something seems broken.

Full log can be found [here](https://gist.githubusercontent.com/tumbl3w33d/94db18d62cb20cf544b0311881f0657a/raw/b993a848bb62bca8ccd516241780551807f02acc/gistfile1.txt).

P.S.: I used kani's tools to do an integrity check and executed the vacuum operation. No problems detected, issue not fixed.

**Comment by Firstyear** [comment]
I can see why this got you stuck, it's not super clear. but this is saying person with uuid `25aa4393-4e20-4cdf-a832-f1e7b30ca49c` is missing. The operation here is updating `idm_all_persons` which is an internal dyngroup, that attempts to add members from a filter, but it appears that the *dynmembers* have been incorrectly reflected into the *members* of this group. That's why you get an error. Have you done something that tries to update or reflect the members of this group manually or similar? 

Anyway, you can resolve this by hand with:

```
# STOP THE SERVER NOW.
kanidmd db-scan list-index idx_eq_name | grep -i idm_all_per
# Note the value in the array such as:
# idm_all_persons: IDLBitRange (sparse values) 1 (data) [ 147, ]
sqlite3 /tmp/kanidm/kanidm.db
sqlite> select * from id2entry where id=147;
# Confirm the json is the idm_all_persons entry.
sqlite> delete from id2entry where id=147;
sqlite> .quit
# Rebuild indexes
kanidmd database reindex
kanidmd database verify
# START the server now.
kanidm login -D anonymous
# Confirm the group was rebuilt.
kanidm group get idm_all_persons
```

I think from this we should probably consider making an entry "delete" or quarantine in the db-scan tool.

**Comment by tumbl3w33d** [comment]
I tried (twice, always starting with a fresh copy of the data folder), but that didn't do the trick and I received
```
c51a3f3e-8df3-4e64-af04-e1b625ae5077 ERROR    ┝━ 🚨 [error]: UUID reference set size differs from query result size <fast path, no uuid info available> | event_tag_id: 1
c51a3f3e-8df3-4e64-af04-e1b625ae5077 ERROR    ┝━ 🚨 [error]: Post-Modify operation failed (plugin), Plugin(ReferentialIntegrity("Uuid referenced not found in database")) | event_tag_id: 1
c51a3f3e-8df3-4e64-af04-e1b625ae5077 ERROR    ┕━ 🚨 [error]: initialise_idm p3 -> result | event_tag_id: 1 | res: Err(Plugin(ReferentialIntegrity("Uuid referenced not found in database")))
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Unable to setup query server or idm server -> Plugin(ReferentialIntegrity("Uuid referenced not found in database"))
```
when trying to reindex. The only thing I did differently from your description was the path to my sqlite, but I guess it was correct to adjust it to `/data/kanidm.db`, which is where my `data` folder is mounted in the container.

If it helps to analyze, I can upload that data folder (or just the db?) for you to have a look.

**Comment by Firstyear** [comment]
Yes, please send me the DB. This is a hell of an issue and I want to get to the bottom of it. Since the DB may have sensitive data, please email it to me at "william.brown@suse.com". If you want to encrypt it, you can use age/rage with my public key "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC2vuTtG15yYDnyXgfjY1UBzBpkxPCroVvnxSf5wb6WYffZw+N8G/I3BOz3jFg0vZsg/YsSNWwttH8jwVhyou7F+7w+jl4v/BwXcADTNIYKEr6q4nrZQ5d436SgqV0a2sUlOUGJ9G/QcVFRMEYvB7+IPOB6LvDTaBkNzJidbr3lQqaVWoRkJu4uCn6QXQmeC6M6447WO+gO+a9gVtzZYewIbCBb2bhKBUPzRSnYl8mlzshOeGLW541U9WMsboL940YzdmtCfgHX/6iZXjF2Y06qxzwR/nRxZ8WQbmSTDELFQwVeBLM/CN2IEdR2k6pSy40kD+dsOaahjAf4VKlSKUUR"
