### ISSUE TITLE
OAuth2 sign-in page should show the target RS

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#1955]
**Is your feature request related to a problem? Please describe.**

The OAuth2 flow is logging me into an application, we know the display name of the app so we should show it, rather than just the generic "sign in".

**Describe the solution you'd like**

Show the RS display name on the OAuth2 login flow. Where it currently says "Sign In", change it to "Sign in to access {}".

**Describe alternatives you've considered**

Leaving it as-is, or adding more crabs.

**Additional context**

**Comment by Firstyear** [comment]
At that point in the flow we should have access to the RS name so this should be pretty easy :)

**Comment by TheRealGramdalf** [comment]
> Leaving it as-is, or adding more crabs.

I was actually thinking about this the other day - in relation to #2056, it would be cool (though mostly eye candy) to  have a crab holding up the logo you provide. If no image (or an invalid format/size) is given, it could hold up an authstralia passport/user-specified default logo. Favicon is another possibility, but that can get messy.

If you wanted a ferris SVG I could give it a shot - I made my profile picture using inkscape, so I have a little experience.

**Comment by Firstyear** [comment]
@yaleman So past william was probably wrong here. At the point we are hitting the oauth2 page and we get the "Sign in to proceed" we *dont* have the displayname of the target client/rs. We do when we proceed and there is a consent phase, which isn't always triggered (since the user may have previously consented).

At that point we only have the "AuthorisationRequest" which is in the query parameters that were sent from the client in the redirect - that also doesn't have a displayname either. All we have is the client_id.

So we could:
* leave it as is
* add an endpoint that allows client_id -> displayname mapping
* something else?

part of me thinks "do nothing". The user *intentionally* typed into a url bar to say "take me to service X" which has now redirected you for sign in. They know what they are doing any why they are doing it. In the case they are going to an application via the app portal they already know what they clicked on as the target application. 

I guess I'm wondering now who benefits from this? When might a situation come up where the user *doesnt* know what the target of their action is? 

If we do decide to add the client-id mapping we need another round trip to get that to resolve though - perhaps we find a way to stuff a req for the client id to be resolved at the same time as we check the authentication of the user is valid? I don't think there is a harm to even make the client id to displayname api public, since we already have the well-known urls hanging off the client id anyway.

**Comment by Firstyear** [comment]
We do this now as part of the web ui rewrite :)
