### ISSUE TITLE
Inheritance rules for orphaned groups

### ISSUE THREAD

**Issue by ziQ** [kanidm/kanidm#2024]
Referring to @Firstyear in [#1481](https://github.com/kanidm/kanidm/issues/1481#issuecomment-1643046108)
> I think an important coarse-role I am omitting here is "group admin". This is because I want to remove the blanket group admin roles in favour of "managed by" style rules. This will change how we create groups because we will need to have group creates always declare a "managed by" group during the create. We may still need a group-admin rule for "break-glass" though.

It would be great if there were definable "inheritance rules". For example, if the managed-by person for "example group" leaves the company, managed-by could automatically transfer to the next hierarchy level (the person's manager). Since not all use cases will have organizational hierarchies, the group inheritance should have sane defaults while allowing group-specific overrides.

**Comment by ziQ** [comment]
Related to #249

**Comment by Firstyear** [comment]
Thinking about this, this kind of makes sense? Since if you have groups A and B. A manages B. And B has privilege X. Then A by management can add it's own members to B and gain that right. So having these rules inherit is "already the case" just by this proxy relationship. However, it also could *surprise* people that this behaviour is the case, and it would mean that admins rather than just having the ability to affect group memberships, end up having *every right in the system*. 

So I think this needs deeper thought. It could already be implemented by a user by having the group B take it's manager as a member so that the permissions pass through without needing this automatic inheritance.

**Comment by yaleman** [comment]
This'd definitely lead to some surprise when making changes without some good UI/API requirements.

The "managed by" thing has always seemed more like a flag to say "this is who to contact for management of this group" (with an inherited "write" permission), rather than a "this is the only group who can manage it... because helpdesk/IDP manager groups still typically need these roles too

**Comment by Firstyear** [comment]
I think we roll this in with the access control rework because this feature would shape how we implement that
