### ISSUE TITLE
Improve plugins naming

### ISSUE THREAD

**Issue by Seba-T** [kanidm/kanidm#2052]
**Is your feature request related to a problem? Please describe.**

The name 'plugins' isn't very descriptive of what the module is supposed to do. When I first saw it I thought there was some kind of marketplace where you could get your own plugins, and I'm afraid newcomers could be mislead as well.

**Describe the solution you'd like**

Use a more descriptive name, maybe something like 'hooks'?

**Describe alternatives you've considered**

Going back to sleep, it's 8am on Saturday here

**Comment by yaleman** [comment]
If they're digging that far into the internals of the code I'd be worried they weren't looking at the dev guide for what a plugin was 😃

**Comment by Seba-T** [comment]
I think one might get confused from the documentation itself. Although it's explained what a plugin is I feel the name itself could lead the reader to believe there are some other implicit features regarding the plugin that are not mentioned. See it from a newcomer perspective: they can't know how lazy the people who wrote the docs were, so they could think that 'plugins' refers to what is commonly associated with it [(just a random example that I believe reflects what most people think)](https://www.britannica.com/technology/plug-in) and that the writers just assumed everyone would be on the same page. We know that that's not the case but they don't necessarily do.

**Comment by Firstyear** [comment]
@Seba-T So it's actually a bit of a story. The reason they are called plugins is because I formerly worked on 389-ds and that has plugins as well. They *are* dynamic libraries in 389-ds, where you can actually make your own, and install them. They allow intercepting operations, tweaking them, generating content, etc. 

So of course, having worked on 389-ds for many years, and using some of it's internals as inspiration to Kanidm, I foolishly named them "plugins" because they did the same thing in Kanidm. (It's basically like playing where's wally, but with "find the concept william stole from 389-ds"). 

But unlike 389-ds, they aren't really ... pluggable. Or even currently, they can't be switched on/off individually because I didn't want to allow people that much room to muck up their installs. 

Saying this, like @yaleman says, they arent' in any docs or anything unless you look deep into the code. So it's not really come up yet. There are possible other names. 

* overlays - openldap's name for the same concept as 389-ds, but also dynamicly loadable. 
* transformers 
* lenses
* adapters
* Something else?

But also, I guess the other thing is "is it really a problem?"

**Comment by Seba-T** [comment]
Ohh I see I see, now it makes much more sense why they're named in that way. 
> But unlike 389-ds, they aren't really ... pluggable. Or even currently, they can't be switched on/off individually because I didn't want to allow people that much room to muck up their installs.
> 

Yeah that's what I was feeling was somehow off but I couldn't really name it. 

> But also, I guess the other thing is "is it really a problem?"

I mean I think this would probably be something one would care about once every other possible issue has already been solved, so I'd say it's a problem with the lowest possible priority, aka it will take a million years before anyone starts worrying about it

**Comment by Firstyear** [comment]
Yeah, I think we just close this as a "rainy day task". I think we'll always have other priorities.
