### ISSUE TITLE
Set custom image/icon for applications

### ISSUE THREAD

**Issue by yaakov-h** [kanidm/kanidm#2056]
**Is your feature request related to a problem? Please describe.**

It would be nice to set a custom image/icon for each app (e.g. oauth2 integrations) that shows up on the web interface to replace the default crab mascot.

This may or may not be relevant to #1996 or #1955.

**Describe the solution you'd like**

Perhaps something like:

```shell
kanidm system oauth2 set-logo appname https://example.com/image.svg
```

**Describe alternatives you've considered**

I could print the icon on a post-it note and stick it over the top of the default image on my screen. 😁

**Comment by yaleman** [comment]
The main issue I can see with specifying a third-party URL is that our existing content security policies don't allow for it - we would need to cache/store it locally for display - which I'd prefer we did for performance and consistency reasons.

There's also the matter of size/format etc which becomes its own nuisance across different user devices.

**Comment by Firstyear** [comment]
Yeah, I don't think I'd be comfortable with a third party url here. i'd rather have kani serve the blob, which would give us a lot more control about replication and serving this reliably.

**Comment by ToxicMushroom** [comment]
required args are surrounded by <>.
 
Would `kanidm system oauth2 set-image <name> </path/to/local/file.svg> <imagetype>` be a good interface to handle this ?
It think it'd just need to send the post to `/v1/oauth2/{:rs_name}/_image`.
We will need to update:
 - the user applist webui to try to show the icons 
 - the internals to advertise the `/ui/images/oauth2/{:rs_name}` endpoints inside AppLink::Oauth2 objects
 - preferably lazy load the images ? idk if it matters a *lot* since they're 128kb max.
 
 lmk if I missed something.

**Comment by yaleman** [comment]
You shouldn't have to set image type, but the CLI command matches what I'd expect.

**Comment by ToxicMushroom** [comment]
This was closed by accident, the linked PR didn't fully resolve this, I remember removing the "fixes" from the PR description but I must have forgotten to save.
