### ISSUE TITLE
OIDC flow/response types supported

### ISSUE THREAD

**Issue by starship-jr** [kanidm/kanidm#2106]
**Is your feature request related to a problem? Please describe.**

Hello, I am curious if you are supporting, OpenId Connect [Resource Owner Password Flow](https://auth0.com/docs/authenticate/login/oidc-conformant-authentication/oidc-adoption-rop-flow#oidc-conformant)

I will expose my use case and maybe my idea is terrible (: 

I have a mail server and a web mail client onto it. I would like to centralize in a standard way my authentication and authorization process. Kanidm seems really interesting for that.

So my idea was to connect these different authentication mechanisism, mail server (IMAP/SMTP connections) and web client under openId Connect.

For the web client, the authorization code flow with OIDC (code reponse type) seems perfect.
About SMTP/IMAP connection and user authentication with Kanidm I am not really sure what option do I have. The ressource owner password flow seems to be allright for what I have in mind. 
When user initiate IMAP or SMTP connection with their credentials, I would like to pass the username and password to kanidm without redirect uri and get directly the id_token on the mail server.

Maybe there are better alternatives with kandim for what I seek. 

Any advice would be really appreciate !
Thanks in advance

**Describe the solution you'd like**

Some advice :) 

**Describe alternatives you've considered**

Read the documentation and my thoughts are still not really clear

**Additional context**

None. Thanks for this beautiful project

**Comment by Firstyear** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> Hello, I am curious if you are supporting, OpenId Connect [Resource Owner Password Flow](https://auth0.com/docs/authenticate/login/oidc-conformant-authentication/oidc-adoption-rop-flow#oidc-conformant)

The problem with this flow is that it's about username/password transmission as you can see here:

https://datatracker.ietf.org/doc/html/rfc6749#section-4.3

We don't support this since we strongly believe in MFA, and authentication mechanisms like webauthn. As a result most accounts would actually not work with this flow.

> 
> Maybe there are better alternatives with kandim for what I seek.

There are!

First, IMAP/SMTP *can* do OAUTH2 as a mechanism where the MUA can do the oauth2 exchange and then use the tokens issued via the IMAP/SMTP channels. An example for dovecot is here https://doc.dovecot.org/configuration_manual/authentication/oauth2/ which can be combined with postfix. This also has a similar setup example for the two, see https://documentation.open-xchange.com/7.10.2/middleware/mail/dovecot/oauth_2.0_with_postfix_and_dovecot.html 

Second as an alternative, you want to pay attention to https://github.com/kanidm/kanidm/issues/41 which is currently being worked on. This will allow an account to provision unique passwords for IMAP/SMTP that don't require leaking the primary account credentials. Think of it as per-user-per-service tokens so that legacy applications that only support username/password still can work with a more secure experience behind the scenes.

> **Additional context**
> 
> None. Thanks for this beautiful project

No problem, thanks for asking the question. I hope this has helped.

**Comment by Firstyear** [comment]
Duplicate #41

**Comment by starship-jr** [comment]
I'd never heard of the SASL authentication mechanism, but it sounds very interesting.
I'll look into it

A big bunch of thanks for your quick reply and great advices !
