### ISSUE TITLE
Kanidm server returns unexpected results in LDAP query from OPNsense

### ISSUE THREAD

**Issue by 0xC0ncord** [kanidm/kanidm#2132]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to integrate OPNsense's LDAP authentication into Kanidm. Unfortunately, OPNsense's LDAP backend is hardcoded to search for `cn=` when looking up groups, which Kanidm does not return. The current situation is that OPNsense is able to execute a query for a user's groups, but is not able to make sense of the returned data:

```
User: concord authenticated successfully.
This user is a member of these groups:


Attributes received from server:
dn => spn=concord@idm.fuwafuwatime.moe,dc=idm,dc=fuwafuwatime,dc=moe
class => account
memberof
object
person
posixaccount
displayname => concord
gidnumber => 1688334410
loginshell => /bin/bash
memberof => spn=idm_all_persons@idm.fuwafuwatime.moe,dc=idm,dc=fuwafuwatime,dc=moe
spn=idm_all_accounts@idm.fuwafuwatime.moe,dc=idm,dc=fuwafuwatime,dc=moe
spn=sysadmins@idm.fuwafuwatime.moe,dc=idm,dc=fuwafuwatime,dc=moe
name => concord
spn => concord@idm.fuwafuwatime.moe
uuid => 14f4a2c1-4541-4018-9e7d-9b81010ece6c
```

**Describe the solution you'd like**

LDAP data for groups should also include `cn=` for applications that require it.

**Describe alternatives you've considered**

N/A

**Additional context**

I originally requested a potential solution to OPNsense: https://github.com/opnsense/core/issues/6670

Unfortunately I think my proposed solution on the OPNsense side would not suffice since the `spn=` field includes the `@` character which would pose additional problems.

**Comment by Firstyear** [comment]
This isn't true, we *do* support cn. There are hidden maps from Kanidm attributes to ldap specific ones. You can display these with:

```
ldapsearch -H ldaps://... -x -b ... '(name=idm_all_persons)' + \*
```

Note the '+' which here will show you the virtual attributes. 

Also note that provided the ldap client *requests* the attributes we also will return them. So if a client simply requests no attributes or `*` they will only get what you see there. They need to request the attributes they want specifically such as `gidnumber cn name` etc. Or they need to include `+` in their request.

**Comment by 0xC0ncord** [comment]
Ahh, that makes sense. Apologies for the confusion.

Digging into this a little more, it seems OPNsense is just searching for users and looking at the `memberOf` attribute which normally does not contain `cn=`. Is there a special query needed to have Kanidm populate `cn=` in a user's `memberOf`? Or does a follow-on request need to be performed?

**Comment by Firstyear** [comment]
That's not a Kanidm issue, that's an OPNsense issue. MemberOf per the rfc is the FQDN of the entry. OPNSense here is making assumptions about the content of that FQDN and exploding it, rather than chasing it to see the entries referred. There is nothing saying that the FQDN has to contain cn, and in fact in future when we add replication and trusts it can't since we need spn to uniquely define the entries since we don't do partitioning like AD does. 

So I think this is an OPNSense bug where they are not properly querying the LDAP provider for its content. They should be able to simply do the equivalent of

ldapsearch '(cn=idm_all_persons)'

Then they take the memberof attr and without parsing it, turn it into a filter. 

ldapsearch`(&(objectClass=group)(|(memberOf=spn ...)(memberOf=spn ...) ... ))`

Then from there they can view the contents of the group that they need (such as cn).

This issue could just as easily affect a unix ldap server if they used something else in the FDQN instead of the cn RDN here.

**Comment by 0xC0ncord** [comment]
Thanks for the explanation!

**Comment by Firstyear** [comment]
No problem. Please CC me on the OPNSense bug if/when you report it so I can help explain :)

**Comment by 0xC0ncord** [comment]
> No problem. Please CC me on the OPNSense bug if/when you report it so I can help explain :)

I'll file it right now, closing the old since it isn't entirely accurate about the problem.
