### ISSUE TITLE
OAuth2 resource server does not allow origin subdomains to authenticate.

### ISSUE THREAD

**Issue by miguelangel-nubla** [kanidm/kanidm#2135]
### I did this
Followed the docs to create a [resource server](https://kanidm.github.io/kanidm/stable/integrations/oauth2.html#create-the-kanidm-configuration) with origin `https://mydomain.tld` and configured a reverse proxy oauth2-proxy via OIDC with nginx. Login to `https://mydomain.tld` pages work as expected.
### I expected the following
Be able to make it work with `https://app1.mydomain.tld`, `https://app2.mydomain.tld` etc.
Kanidm WebUI refuses with "Invalid request". Logs show:
```
 INFO     handle_request [ 583µs | 0.00% / 100.00% ]
 INFO     ┕━ request [ 583µs | 27.87% / 100.00% ] method: POST | uri: /oauth2/authorise | version: HTTP/1.1
 INFO        ┝━ handle_oauth2_authorise [ 420µs | 72.13% ]
 INFO        │  ┝━ ｉ [info]: A valid limited session value exists for this token | event_tag_id: 10
 WARN        │  ┕━ 🚧 [warn]: Invalid oauth2 redirect_uri (must be related to origin Tuple("https", Domain("mydomain.tld"), 443)) - got Tuple("https", Domain("app1.mydomain.tld"), 443) | event_tag_id: 2 | origin: Tuple("https", Domain("mydomain.tld"), 443)
 ERROR       ┕━ 🚨 [error]: Unable to authorise - Error ID:  error: invalid_origin | event_tag_id: 1
```
### Kanidm version details

- Output of `kanidm(d) version`:
`kanidmd 1.1.0-rc.14-dev`
- Are you running it in a container? If so, which image/tag?:
`1.1.0-rc.14-dev`
- Operating System / Version (On Unix please post the output of `uname -a`):
`Linux kanimd-ix-chart-654548c995-7kzmg 5.15.107+truenas #1 SMP Tue Jul 25 00:05:02 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
### Any other comments
A exact match is evaluated:
https://github.com/kanidm/kanidm/blob/2cade8f4ac594e3a9f75a7de0f56f345ae3d4bca/server/lib/src/idm/oauth2.rs#L1263
Since WebAuthn is [already](https://kanidm.github.io/kanidm/stable/choosing_a_domain_name.html#subdomains) available to subdomains, limiting the origin to a perfect match does not seem to have any benefits over the expected behaviour.

**Comment by Firstyear** [comment]
Webauthn allowing subdomains is different though to oauth2 allowing them though. 

We allow subdomains in webauthn to account for possible geo-located instances, where you may have say:

```
qld.idm.kanidm.com
sa.idm.kanidm.com
...
```

Now we only allow a since uri on the oauth2rs because we need to display a valid uri on the app link portal page when someone first logs in. As well, from the RFC https://www.rfc-editor.org/rfc/rfc6749#section-10.6

```
   In order to prevent such an attack, the authorization server MUST
   ensure that the redirection URI used to obtain the authorization code
   is identical to the redirection URI provided when exchanging the
   authorization code for an access token.  The authorization server
   MUST require public clients and SHOULD require confidential clients
   to register their redirection URIs.  If a redirection URI is provided
   in the request, the authorization server MUST validate it against the
   registered value.
```

So generally a request to allow subdomains makes me think you are trying to do one of three things:

* You want to register a single oauth2rs, and then just copy those client id/secrets to multiple different oauth2 applications under a single subdomain. This is insecure, and I won't change kanidm to allow that.
* You want to host high available application with multiple servers. Generally you should have a load balancer in front instead of trying to have multiple nodes with unique urls. This is because the application itself will bind it's cookies to it's domain name, and if you use a.domain.com and b.domain.com then the cookies won't transparently work between nodes. So you need a single domain name, and not subdomains here. 
* You want to geo-graphically locate nodes of the same application. In this case, you need a way for users to be *routed* to the correct geographic instance of the application. You would only be able to do this by having some way to put users based on a location into a group, and then that way when a user logs in their app-link portal will show their correct geographic instance of the application. Then each geographic instance would need it's own client-id and secret anyway. 

So in all these cases, there is no valid reason that I can see to allow subdomains in oauth2. 

If your use case isn't one of these three I'd like to know more about what it is so we can discuss further about what could be possible to achieve.

**Comment by miguelangel-nubla** [comment]
I was testing the NGINX configuration in the [OAuth2-Proxy documentation](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview#configuring-for-use-with-the-nginx-auth_request-directive) and using it for multiple reverse proxies. With this setup, OAuth2-Proxy is served over a path on the domain. It effectively behaves as multiple instances, one for each reverse proxy you have configured, with its own redirection URL on each but sharing the same credentials. This is, of course, not compatible with the way Kanidm operates.

Considering all this, the solution for my use case is to change the domain where the cookies are saved and use a single domain for the OAuth2-Proxy instance. Therefore, no change is required from Kanidm.

I had hoped that sharing the same parent domain would be allowed, as generally, subdomains have access to cookies/credentials (which is why I mentioned WebAuthn, which approaches it the same way).

I understand the decision to disallow subdomains is to reduce the attack vector. However, since content on a rogue subdomain can fully access cookies (if not using the `__Host-` prefix) and WebAuthn, wouldn’t it be possible to perform a MitM attack from that subdomain anyway? What am I missing?

On the other extreme, if an exact match on origin does make sense, wouldn’t checking the full URI, including the path and everything else, also make sense?

**Comment by yaleman** [comment]
It's not about just subdomains, it's about the URL being different. OAuth2 requires an _exact_ match for the registered redirect URL. 

The spec allows for multiple URLs to be registered, but not a blanket "any subdomain based on this pattern". As yet this isn't implemented in Kanidm.

**Comment by Firstyear** [comment]
They have a point about the subdomains. Even if we exact url match, there are two applications that have authenticated with oauth2 the applications then individually issue cookies for "mydomain.com" and "app.mydomain.com". Then mydomain.com can access the cookies from app.mydomain.com. Saying this, this is only true if the cookie sets domain=, if it sets name= only then it's limited to that singular domain. 

We can't really do much about this though - we have a lot of material about domain names https://kanidm.github.io/kanidm/stable/choosing_a_domain_name.html . Maybe we need to comment about oauth2 applications in here too, but i'm not sure we have to either. It's just a fact of http application deployment that you need unique domain names, and sharing a subdomain opens up these issues.

**Comment by yaleman** [comment]
The cookie problem is a little outside Kanidm's scope in this case however - in this case it's an issue with OAuth2 authorisation/redirect value matching. 

What the user and the associated RS does with the cookies is outside our control/influence.

**Comment by Firstyear** [comment]
Yep, I agree. 

So I think in summary, this isn't an issue in Kani, and subdomains with external oauth2 applications remains up to the admin.

Should we have a warning about this in the oauth2 chapter?

**Comment by Firstyear** [comment]
@yaleman What should we do here? I think this would be good to close out.

**Comment by yaleman** [comment]
This should be covered by the other bits where we're allowing registration of multiple URLs?

**Comment by Firstyear** [comment]
I'm not allowing multiple urls, I'm allowing a boolean for localhost to be valid as a redirect on public clients. I think for subdomains to be accepted, this would also need a similar boolean. Then the question becomes if it should be on public clients only to enforce pkce

**Comment by yaleman** [comment]
I wouldn't suggest a functionality to allow subdomains, I'd suggest closer alignment with the spec and requiring _URLs_ to be registered to the RS.

**Comment by Firstyear** [comment]
The reason I didn't do that with the localhost thing is that we check the url for https and then enforce it forever, but localhost is a secure origin and can't have that. so with multiple urls, we want them all to be https.

**Comment by Firstyear** [comment]
My point is more I looked at adding multiple uris to satisfy this and localhost, but you can't because we need to ensure that origins are always secure when the registerd url is https. But you can't do that with localhost because it's normally http. So I'll have to impl a different mechanism for alternate urls.

**Comment by yaleman** [comment]
Yeah, so we can close this one and #1980 (per the title, multiple URLs) should be reopened or cloned and targeting multiple URLs
