### ISSUE TITLE
service-account credential status fails if none is set

### ISSUE THREAD

**Issue by daenney** [kanidm/kanidm#2156]
### I did this

```
$ kanidm service-account credential status test --name idm_admin
2023-09-26T17:04:08.735688Z ERROR kanidm_cli::serviceaccount: Error getting credential status -> Http(500, Some(NoMatchingAttributes), "193110b5-e9ce-404d-b87c-e62e0a0c16cd")
```

Once I set a credential, this returns:

```
---
uuid: a-long-number
generated password: set
---
```

### I expected the following

When calling status, I expect to always get a response. But if it's not set, the response should say `generated password: unset` or something like that instead of HTTP 500.

### Kanidm version details

- Output of `kanidm(d) version`: `kanidm 1.1.0-beta.13 689c7c74f6`
- Are you running it in a container? If so, which image/tag?:
- If not a container, how'd you install it: Ubuntu package built with package scripts in this repo
- Operating System / Version (On Unix please post the output of `uname -a`): `Linux idm 6.1.0-12-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.52-1 (2023-09-07) x86_64 GNU/Linux`

**Comment by Firstyear** [comment]
@yaleman Should noMatchingAttributes map to 404 here? I think that would make it a better response. 

This is a good example where we almost need to return `200: not found` :P

**Comment by yaleman** [comment]
404 would be appropriate TBH on noMatchingAttributes, 400 if you don't send a valid request (ie, missing body/username).

NOT 200! :smile:

**Comment by daenney** [comment]
I think the 404 makes sense for it to be what the server returns. The 500 definitely seems odd, since it doesn't seem anything's actually gone wrong here. It's that the account doesn't have the attribute set, which doesn't seem like an error in itself.

On the CLI I think it would be confusing if the user only got a 404/not found back. That's easily misinterpreted as a "resource not found", so the account, instead of "this particular attribute doesn't exist on the account". In that case, I think it would still be nice to get output similar to the success case, but indicating no credential has been set.

**Comment by Firstyear** [comment]
Yeah. This is the problem we have with the http status codes thing - @yaleman and I have a minor disagreement here but I think the "200: error" is actually an okay pattern because the http request succeeded, and it internally is showing you the states of the application. Where as 404 should mean the http request endpoint wasn't found. 

But when you mix these codes in with the application logic, you get situations like this - was it that the user wasn't found at that end point? Or was the attribute not there? It confuses a http request error with an application error.

So I think we need to actually consider *not* relying on http status codes here, but getting errors displayed and communicated in better ways from the application.

**Comment by yaleman** [comment]
You *can* send a "what wasn't found" in the body 😄
