### ISSUE TITLE
OAuth 2 Client Credentials Grant

### ISSUE THREAD

**Issue by adamcstephens** [kanidm/kanidm#2217]
**Is your feature request related to a problem? Please describe.**

OAuth 2.0 has support for client credentials, which can provide for machine-to-machine services to gain an access token. Please consider adding this support.

For example, Prometheus natively supports this which would allow one to scrape services behind protected endpoints: https://prometheus.io/docs/alerting/latest/configuration/#oauth2 

I think [this is the relevant RFC](https://datatracker.ietf.org/doc/html/rfc6749#section-4.4).

**Describe the solution you'd like**

I'd like to be able to configure kanidm for client credentials granting.

**Describe alternatives you've considered**

Not using kanidm, basic authentication (where possible), not protecting machine-to-machine traffic with authentication.

**Comment by yaleman** [comment]
I could see this being doable for `service_account`s with an API token.

**Comment by Firstyear** [comment]
well the issues here is that the client credentials grant is operating on behalf of the oauth2rs at that point, not a true account. So we'd need a way to tie the oauth2 client authentication to a service account to give proper access controls. I'm not sure how we'd achieve that today.

Do you have an example application that requires this?

**Comment by yaleman** [comment]
> we'd need a way to tie the OAuth2 client authentication to a service account to give proper access controls

I'd see the mapping being: 

| request field   | Kanidm equivalent |
| ---             | ---    | 
| `client_id`     | `spn` |
| `client_secret` | `api token` |
| `scope`         | an `rs_name` which has group->SA mappings to specify the access |

It fits within the RFC for Client Credentials, doesn't ... seem to have any particular downsides, and doesn't break the auth model for Kanidm and this class of account. We could put a specific filter on `client_credential` access for service accounts, which would limit potential blast radius.

**Comment by yaleman** [comment]
Funnily enough it'd be a handy auth method for brokering access to the stats endpoint that I want to put behind authentication at some point 🤔

**Comment by Firstyear** [comment]
> > we'd need a way to tie the OAuth2 client authentication to a service account to give proper access controls
> 
> I'd see the mapping being:
> request field 	Kanidm equivalent
> `client_id` 	`spn`
> `client_secret` 	`api token`
> `scope` 	an `rs_name` which has group->SA mappings to specify the access
> 
> It fits within the RFC for Client Credentials, doesn't ... seem to have any particular downsides, and doesn't break the auth model for Kanidm and this class of account. We could put a specific filter on `client_credential` access for service accounts, which would limit potential blast radius.

I think the "intent" of client credentials grant is that if you have a service like nextcloud, it can use it's client id + secret to get it's own token to do "system" tasks, where a user gets their token for their own reason. It's a bit confusing but in oauth2 "client" here means the "service" like nextcloud, *not* a user account or service account. 

i think confusing service accounts into this by hijacking the client id+secret to give the client credentials could end in tears - some applications if they have access to this grant will assume the RS client id+secret will work for a grant, and others could end up trying to use a SA+token for the authorisation which would break the auth code flow.

This is to say nothing of the actual changes needed to securely implement this, and we'd need a new scope map + supplemental scope map to auth it properly. 

The alternate is that we'd need a way to say "for this oauth2 rs, if it attempts a client grant then map to this service account / privs". Or we'd need to roll oauth2 RS into a service account (which opens it's own risks), since then possesion of the clientid+secret can allow PII disclosure (today it doesn't because you have to have a users token to retrieve PII).

I think the better question here is "what is @adamcstephens trying to achieve". Is there a specific application you have in mind that requires this flow? Or do you want a way for service accounts to retrieve a token?

**Comment by Firstyear** [comment]
PS: If we were doing service-account token grant issuance, we'd use https://datatracker.ietf.org/doc/html/rfc6749#section-4.3 and use a token instead of the password here. We wouldn't allow normal users to carry out this flow however.

**Comment by yaleman** [comment]
In your Nextcloud example why wouldn't those credentials map to a Service Account in Kanidm? The flow needs an identifier and a secret credential... and I'd want to be able to provision multiple credentials per service account, since that's how other IDP's work (AWS, Google, etc)

The flowchart from "[what kind of client are you building](https://developer.okta.com/docs/concepts/oauth-openid/#what-kind-of-client-are-you-building)" is a good one, CC is *the* way to do machine-to-machine auth.

Eg:

```mermaid
sequenceDiagram

participant Nextcloud
participant Kanidm
participant Some other API

Nextcloud->>Kanidm: Authenticate with Client ID + Client Secret
Kanidm->>Kanidm: Validate Client ID + Client Secret
Kanidm-->>Nextcloud: Access Token
Nextcloud->>Some other API: Do authenticated call
Some other API-->>Nextcloud: Send Response
```

I've been looking at how to do machine-to-machine authentication and it matches this flow for this, because the destination apps expect the JWT from the IDP, not a u/p to pass through to the IDP (or ugh, LDAP).

So far I'm looking at using it for Minio, and the Prometheus docs linked in OP's request include this method for authenticating with third-party services.

And password flow isn't designed for M2M auth, it's designed as a way of replacing traditional U/P auth without MFA, by passing it through an application to the IDP.

Ref:

- [Okta Implementation guide](https://developer.okta.com/docs/guides/implement-grant-type/clientcreds/main/#client-credentials-flow) 
- [Secure a Node API with OAuth2.0 CC](https://developer.okta.com/blog/2018/06/06/node-api-oauth-client-credentials#how-the-client-credentials-flow-verification-works)

**Comment by Firstyear** [comment]
But that's kind of the issue here, is you're auhtenticating with the *client id and client secret* not *a service account and its token*. So you don't have multiple service accounts, you have one account bound between an RS and an SA at that point.

I think a possible way to proceed with this could be that to do client grant, we could just have the resulting token have *no* privileges in Kani, and it just is a token that represents that client to some other api. If it were to have privs, it would need a way to link to an SA.

**Comment by yaleman** [comment]
... I'm a derp and misunderstanding the OAuth RFC's.

**Comment by Firstyear** [comment]
It's okay. The Oauth2 rfc is *not* easy to read and doesn't communicate itself very well at all.

**Comment by mikibella** [comment]
As mentioned in the community chat I would like to add some use cases I could think of.
I have kanidm running on a raspberry pi fully integrated with an LDAP Deamon. I will have several software components running on my pi. Mentioned services should act in their own behalf and therefore need the client credentials flow.
1. **Service Deployed by me**: Services A running inside the pi communicating over protocol X. Services B which I deployed should be able to get an access token, if i previously added the service B info to my authorization server (e.g. kanidm). After service B gets his access token from the authorization server it can communicate with service A. The token is retrieved under the standard oauth2 endpoints (oauth/token with shared secret and client id). The registration of the deployed app by me could happen during deploying by a script using the [kanidm client tools for creating a oauth2 client](https://kanidm.github.io/kanidm/stable/integrations/oauth2.html?highlight=scope%20maps#create-the-kanidm-configuration).
2. **External Service**:  An external service wants to communicate with a service running on the raspberry PI. Therefore it needs an access token to do that. This token is retrieved from the authorization server. Firstly the external service has to be registered at the authorization server as a client via script or the rest api. After that the token can be received with the standard flow (e.g. client credential with shared secret as in 1. or [private key jwt](https://oauth.net/private-key-jwt/).

**Comment by Firstyear** [comment]
Our implementation today covers use case 1. For use case 2 we'll need to do a seperate impl for service accounts as that changes the logic somewhat.

**Comment by philipcristiano** [comment]
Is there an issue for use case 2? 

> External Service: An external service wants to communicate with a service running on the raspberry PI. Therefore it needs an access token to do that. This token is retrieved from the authorization server. Firstly the external service has to be registered at the authorization server as a client via script or the rest api. After that the token can be received with the standard flow (e.g. client credential with shared secret as in 1. or [private key jwt](https://oauth.net/private-key-jwt/).

This would be useful for [PostgREST](https://docs.postgrest.org/en/v12/integrations/jwt_gen.html) or (more likely) [pREST](https://docs.prestd.com/). I'd love to use kanidm (service accounts?) with a client service to programatically generate the tokens required and manage access with the rest of the OAuth services I have running.

**Comment by Firstyear** [comment]
@philipcristiano We probably want to achieve this by having a way for service-accounts to get tokens directly issued, rather than credentials grant here. I think that would make more sense here for your use case.

**Comment by philipcristiano** [comment]
@Firstyear yeah that makes sense! Looking through the swagger, that is not currently possible and would require new work, right?

**Comment by Firstyear** [comment]
Yes, it would require new work. Could you open a new issue for the topic?
