### ISSUE TITLE
Suggestion: Update unixd home_alias note for Ubuntu users

### ISSUE THREAD

**Issue by kenjitamura** [kanidm/kanidm#2233]
Hello, I ran into an issue with snaps on Ubuntu using this configuration for unixd:  

```
home_attr = "uuid"
home_alias = "name"
```  
It turns out that there's a known issue with snaps and symlinked home directories due to an apparmor constraint: 

[Unable to run snap, because of home directory](https://forum.snapcraft.io/t/unable-to-run-snap-because-of-home-directory/25138)  

[when /home is somewhere else, snaps don't work ](https://bugs.launchpad.net/snapd/+bug/1620771)  

I was testing posix logins in a Kubuntu virtual machine and noticed this was the case when firefox wouldn't launch which is a snap by default in most Ubuntu distributions.   

Not a big deal for myself personally as I don't mind doing manual renames if I were to ever change the account name and my setup for Ubuntu is now:  
```
home_attr = "name"
home_alias = "none"
```  
It might be worthwhile to update either the notice on pam_and_nsswitch.md, or add it to frequently_asked_questions.md, with a mention of this for Ubuntu users as Canonical is gung-ho about defaulting as much as possible to snaps going forward.

**Comment by Firstyear** [comment]
This is a bug in ubuntu, not kanidm though. We require this linking because users can change their name at any time. 

So do we either:
* walk that back and negatively impact humans who want to change their name on ubuntu?
* Or do we have to raise the issue in ubuntu since it's their security policy that is at fault?

In my view, we always need to prioritise humans first, and if our designs have exposed a flaw in something else, we need to resolve that fundamental issue, rather than putting humans second. 

I think the only alternative we could pursue is bindmounting, but that can become very messy, very fast, since unlike a symlink, we have to recreate them every startup *and* clean them all up correctly once we are done. Symlinks work very naturally here, but they aren't perfect.

**Comment by kenjitamura** [comment]
I didn't mean to imply there's a bug in kanidm with this or that the recommendation of using symlinks for the homedirectory should be walked back.  I do think it would be good to have the documentation reference in some way that using the recommended configuration of a symlinked home directory is not compatible with snaps.  

It looks like this has been a known issue with snaps for 7+ years and I've checked a few threads and not seen any mention of work in progress to resolve it.

Also, Ubuntu distributions are increasingly pre-loaded with snaps and set the snap store as the default install source for new software so I wouldn't think I'm the only person who will run into this.  

This information being visible at the time the configuration is being decided on would let people decide in advance if they'd rather not distribute the symlink unixd configuration for Ubuntu users or purge their Ubuntu's of snaps.

**Comment by yaleman** [comment]
As @kenjitamura noted, this feels like the kind of thing we could put a quick "hey if you're using Ubuntu or a distro with snaps, check here" link in the PAM docs, which links to a longer explanation in the FAQ about.

**Comment by yaleman** [comment]
Having read some of the related threads was rather... enlightening.

**Comment by Firstyear** [comment]
Do you want to do this change or should I?
