### ISSUE TITLE
Add kanidm_tools to APT package repository

### ISSUE THREAD

**Issue by sbordeyne** [kanidm/kanidm#2264]
**Is your feature request related to a problem? Please describe.**

The documentation doesn't mention installing via APT on a Debian (or debian-like) machine. This is very surprising since the tools are built for seemingly random linux distros (especially for server use, I understand the need for CentOS and MacOS but NixOS has like 0.03% market share), but not, by far, the most popular one. The cargo install is also not straightforward, because you not only have to install the tooling to build the `kanidm` CLI, but also, the command specified in the documentation (`cargo install kanidm_tools`) is not correct, I had to specify the version to install in my case `cargo install kanidm_tools@1.1.0-beta.13`.

**Describe the solution you'd like**

Simply add `kanidm_tools` to either the official repository (ideal) or host your own repo.

**Describe alternatives you've considered**

Running in docker, or use cargo to build the tool. Other alternatives include being able to configure everything in the web UI if logged in with sufficient permissions.

**Additional context**

I'm running debian 12 on my servers, I remote in from SSH using a Macbook, but having the tool on the master node of my kube cluster is more convenient for administration, not to mention more secure (if SSH is configured properly, which it is)

**Comment by yaleman** [comment]
Packaging information for folks who want to spin it up [is in the documentation](https://kanidm.github.io/kanidm/master/packaging_debs.html).

> Simply add kanidm_tools to either the official repository (ideal) or host your own repo.

The word "simply" is doing a *lot* of work there. It's not simple, or easy, and packaging is done as people have time and interest. It's available on NixOS and Arch because wonderful humans in the community cared enough, and keep up with the ongoing maintenance.

I stood up [kanidm_ppa](https://github.com/kanidm/kanidm_ppa/) today as a test, so if you're interested, please look at the [existing Github actions workflow](https://github.com/kanidm/kanidm/blob/master/.github/workflows/debian_package_kanidm.yml) that builds the various packages, and ensure the extras you require are packaged as we commit to master, and they'll be published once a day.

If there's some way to keep the release branches building and in the repository too, that'd be neat.

**Comment by jinnatar** [comment]
FYI, I'm actively working on getting all the packages to end up as usable and friendly packages in the PPA. The first stage of building the `kanidm` deb is done but there's at least a few steps left that I can already see and have under works:
0. Build the deb. Done!
1. Fix the release upload pipeline to actually upload the debs. Fix done, testing it now and hope to have a PR for it today.
2. Modify the PPA repo to surface both Ubuntu & Debian packages. The Ubuntu package seems to work fine on Debian 12, but why risk it since we are building both. Still in dev on my part, I think I've got the right path to keep it user friendly but we can discuss the logic on the eventual PR if there's other opinions.
3. Making sure release and dev builds play nice long term. The current logic builds quite a bit of dev debs and that might end up being a problem at some point. Also not sure if apt has logic to prefer lower numbered stable packages vs. higher numbered dev ones. One would hope! Still thinking about this bit, or can tackle it if it becomes a problem.

**Comment by yaleman** [comment]
One *can* set masks with apt to block versions etc, but we probably should split the PPA into a "nightly" and a "stable" paths if someone's actually going to own the release process (I was just trying to make a minimal *something* work previously)

**Comment by jinnatar** [comment]
With the PRs merged on both sides, we're now at a state where `kanidm` is installable via a PPA. The guidance at https://kanidm.github.io/kanidm_ppa/ has the updated commands that autodetects debian vs. ubuntu.

Two issues remain:
1. Splitting the PPA to `nightly` & `stable`. Shouldn't be too bad, but will be a breaking change. However, since there isn't yet a stable build to test with really, this might need to be deferred until then.
2. The deb buildchain will break if not revamped a bit when GitHub forces Node 20. One of the components is built for Node 12, and surprisingly still works in compat mode with the current Node 16. It's suspected The compat mode will no longer support Node 12, or it will simply break due to age. I'll open a new issue for tackling this.

So I belive this one is fixed, for now!

**Comment by yaleman** [comment]
Thanks @jinnatar
