### ISSUE TITLE
SSSD Compatibility

### ISSUE THREAD

**Issue by LincolnBryant** [kanidm/kanidm#2320]
**Is your feature request related to a problem? Please describe.**

For server environments that do not support the kanidm unix authentication daemon, it would be nice if there were some compatibility with SSSD to work in these cases. It would also be convenient to help migrate away from LDAP/SSSD if kanidm supported SSSD as an interim solution.  

**Describe the solution you'd like**

kanidm supports SSSD in some limited fashion for platforms that don't yet support the unix daemon. 

**Describe alternatives you've considered**

If the kanidm REST api exposes username/uid/gid/ssh public key, it would be possible to build a provisioner that will populate /etc/{passwd,group} at least for my use case, but this is not a very scalable solution. 

**Additional context**

We have a mix of Enterprise Linux 7,8, and 9 hosts. We also have some FreeBSD hosts and other platforms. EL7 will go EOL in June 2024, but this solution would be valuable for other platforms.

**Comment by ThoreKr** [comment]
To chime in on this, we currently use sssd with openldap. I'm looking to replace the latter.

Would this kind of support include the option of sudo rules and host-flag checking, or could this already be coveres by the existing ldap interfaces?

**Comment by Firstyear** [comment]
> To chime in on this, we currently use sssd with openldap. I'm looking to replace the latter.

You should also replace the former. 

> 
> Would this kind of support include the option of sudo rules and host-flag checking, or could this already be coveres by the existing ldap interfaces?

No - we are adding this support as a "stepping stone" to help transition people *away* from SSSD on legacy systems that have issues running the modern pam/nss tools from Kanidm ourselves.

If we are to add sudo rules we will do it on Kanidm's terms - we will design and plan the feature carefully and correctly and then add it first. We would likely never support it via SSSD. This is also because if we were to design the feature around what SSSD did, we would forever be limited by SSSD and it's ideas and implementation.

In general, we *do not* think SSSD is a good option for long term authentication. This is because it is fragile with many inefficient, problematic and unstable elements. It uses outdated and insecure cryptography for local password storage (SHA512 single round) compared to Kanidm (Argon2id + TPM binding). And many many many more things. 

The fact we haven't support SSSD before this is not actually a flaw - it was an intentional choice. 

You should *always* use the pam/nss tools from Kanidm unixd if possible, over any other integration.
