### ISSUE TITLE
Password length complaint unclear

### ISSUE THREAD

**Issue by jyio** [kanidm/kanidm#2321]
### I did this

Attempting to set a 10-character password results in error `TooShort(10)` from the web UI and `Password too was short, needs to be at least 10 characters long` from the CLI client. An 11-character password is accepted.

### I expected the following

Kanidm should accept the 10-character password as promised or, alternatively, demand an 11-character password instead.

### Kanidm version details

- Output of `kanidm(d) version`: `kanidmd 1.1.0-rc.15`, `kanidm 1.1.0-beta.13-dev`
- Are you running it in a container? If so, which image/tag?: `kanidm/server:latest`
- Operating System / Version (On Unix please post the output of `uname -a`): `Linux $(hostname) 6.2.0-36-generic #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2 x86_64 GNU/Linux`

**Comment by Firstyear** [comment]
Sounds like a bug in a pw len check, I'll fix that asap :)

**Comment by Firstyear** [comment]
@jyio Hey there, I investigated this and added some extended test cases for this and I can't reproduce - it appears we accept the password of "min length" correctly, and "min length minus one" is rejected. I'm not 100% sure where you are seeing this behaviour as a result.

**Comment by jyio** [comment]
Thank you @Firstyear for looking into this. This is quite strange!

So, let's say I want to set my password to some 10-character string such as `JGeRqQdP9c`. Well, I'd login to the self service web UI, [Unlock Profile Settings], reauthenticate, [Password and Authentication Settings], then [Change Password]. Well, attempting this `JGeRqQdP9c` produces the following result:

![image](https://github.com/kanidm/kanidm/assets/1149895/41d891cf-3a14-4095-90f0-cfe8f794ac62)

You could count the dots 😂 Anyway, I thought `TooShort(10)` meant that a 10-character password was too short, until I tried the CLI client and received the more verbose wording.

The 11-character string `JGeRqQdP9c5` is accepted without complaint.

Is the minimum length configurable and have I perhaps misconfigured it? Would you be able to generate a throwaway 10-character password, that works for you, for me to try with my setup? Thank you again.

**Comment by yaleman** [comment]
I've seen it throw TooShort(10) when the complexity was too low, can you try `JGeRqQdP9*` ?

**Comment by Firstyear** [comment]
> I've seen it throw TooShort(10) when the complexity was too low, can you try `JGeRqQdP9*` ?

Yeah I just remembered this. This is already a solved issue, it's as @yaleman says. We used to incorrectly raise "tooshort" when it was actually that you failed the *complexity* check. The next version already has improved dialogs here around this. 

So in this case, assume your password is bad and Kanidm is telling you that :)

**Comment by jyio** [comment]
> I've seen it throw TooShort(10) when the complexity was too low, can you try `JGeRqQdP9*` ?

Yeah that was also TooShort(10), and so was `JGeRqQ$P9*`, but `JGeRqQdP9*5` was acceptable.

> So in this case, assume your password is bad and Kanidm is telling you that :)

Hmm... I see [how that works](https://github.com/kanidm/kanidm/blob/master/server/lib/src/idm/server.rs#L1574) now. Is it even possible to generate a 10-character password that scores 4/4 on the zxcvbn scale? Let's see...

- `😀😁😂🤣😃😄` scores 4/4, but it cheats because it's worth 12 chars. And it sucks as a password because it's the first 6 smileys on Windows's emoji keyboard.
- How about `JGe(◕‿◕)9*`? Nope: only 3/4.
- How about some random string where each character is `chr(randint(0, 255))` such as `ß°Ë§Ç/!Ó` or `fäa<õg$¦á÷` or `íôÄ»8Yo$KÍ`? Nope: only 3/4. But are these really that easy to guess?

Any other ideas for 10-character passwords that pass muster? :)

**Comment by Firstyear** [comment]
Well, maybe we should just make the minimum length longer then :P 

Honestly, the point of the check, and the strictness that we are applying to it, is the ongoing and repeated breaches of passwords. Many sites accept frankly insecure and unacceptable passwords, and as with other things, we want to raise that bar higher. So while min policy may say length 10, we still want to push for stronger passwords as a whole because they are often the single biggest weakness on any account. 

The second part is to make passwords have "friction". We want to encourage people to say "wow, the effort to make a secure password sucks, maybe I should just use a password manager or a webauthn passkey instead". By making the bar for passwords higher, we push people away from using them. In a way, we have implemented a "dark pattern" to help push people toward more secure authentication strategies.

And in the case of things like the unix password, since these are a true single factor for things, we have even more reason to demand they are stronger - or to push people toward ssh keys.

**Comment by Firstyear** [comment]
To extend this, on a more personal note, I take it very seriously the faith and trust people put into kanidm to secure their systems - so I want to always make sure that we deliver the very best in a secure, opensource idm. Sometimes that may have some surprising elements like this, but I want to raise the bar for everyone who ever uses Kanidm, so that their accounts are always protected and secure.

**Comment by jyio** [comment]
Clever way to encourage people to change their behavior :)

Weak passwords, when used as single factor, are definitely unacceptable. Would the addition of TOTP sufficiently augment a moderately-strong password and add enough friction to serve Kanidm's purpose? The implementation would be complicated, though. And I'm not sure how one might extend TOTP to the use case in which Kanidm is an LDAP backend for Unix authentication.

Maybe I'm suggesting that the 10-character check is moot... zxcvbn takes care of that already! But it would certainly help to give a hint that passwords shorter than 11 characters would likely (definitely?) fail zxcvbn.

Thank you for all your patience today.

**Comment by Firstyear** [comment]
> Clever way to encourage people to change their behavior :)
> 
> Weak passwords, when used as single factor, are definitely unacceptable. Would the addition of TOTP sufficiently augment a moderately-strong password and add enough friction to serve Kanidm's purpose? The implementation would be complicated, though. And I'm not sure how one might extend TOTP to the use case in which Kanidm is an LDAP backend for Unix authentication.

The problem we have is that in the current design of the account system, you set a password *first*, then you have to add the TOTP. You can then subsequently remove the TOTP.  Because of this, we have to assume the password a sole factor until the TOTP is added - and second, if the TOTP is added and we'd weakened the PW reqs, we'd have to force the user to change their PW again. 

So it's simpler to just force it to be "password must be good". 

Even with TOTP, having the extra factor doesn't mean we should *weaken* other factors. That's the point of MFA - each factor is additive, it doesn't allow us to back-off other factors. 

Finally the design of Kani allows long lived sessions, meaning that PW rentry should be uncommon. And of course, if you are keen to improve usability, we have probably the best opensource implementation of passkeys around  :) 

> 
> Maybe I'm suggesting that the 10-character check is moot... zxcvbn takes care of that already! But it would certainly help to give a hint that passwords shorter than 11 characters would likely (definitely?) fail zxcvbn.

This is fixed in the next version already :) We have better output from this situation when it comes up. 

> 
> Thank you for all your patience today.
