### ISSUE TITLE
Security Keys not enrolled for a PIN can fail in unhelpful ways

### ISSUE THREAD

**Issue by jinnatar** [kanidm/kanidm#2370]
### I did this
- Added a new user: `kanidm person create demo Demo`
- Started passkey enrollment: `kanidm person credential create-reset-token demo --name idm_admin`
- Attempted on Firefox ESR 115.4 on Debian 12.4 to register 2 different models of Token2 security keys that did not have a PIN set.

### I expected the following
- A successful enrollment or helpful user facing error about a lack of a PIN / other verification method.
- Instead a generic failure is reported in the web interface (forgot to copy it while I still had unenrolled keys handy).
- It would be better if a more specific user facing error were given suggesting that either the passkey device or browser do not support adequate verification, such as with a pin.

### Kanidm version details

- Output of `kanidm(d) version`: `kanidmd 1.1.0-rc.15`
- Are you running it in a container? If so, which image/tag?: Yes, `kanidm/server:latest` aka `f01d2fa548e9`

### Any other comments
- The server side logs an error which is not mentioned in current documentation, which could also be more helpful:
```
[error]: Unable to start passkey registration | eclass: UserNotVerified | emsg: The user verified bit is not set, and required by policy
[error]: Failed to begin credential_passkey_init | event_tag_id: 1 | err: Webauthn
```

- The latest Firefox ESR 115.5 still has lacking PIN support and is in ways even worse than 115.4.
- While the keys do support setting a PIN, Firefox ESR fails to propose an enrollment for it when requested. If enrolled in Chrome, they function well in ESR 115.4, fail in ESR 115.5 and work great again in non-ESR 120.0.1. So ultimately a new ESR release will improve my specific situation, it would be great if kanidm was more helpful in pointing the blame in the right direction.

**Comment by yaleman** [comment]
We should be able to expose this to the user via the webUI returns

**Comment by Firstyear** [comment]
Well the bigger issue here is firefox not offering to set the PIN on first use. Is there a mozilla bug about that somewhere? Ive had a look and see a few old ones, but I probably need to re-try this and open a new issue if it's on going.

**Comment by yaleman** [comment]
Oh, no doubt - but us throwing "oh no" in the UI (mentioned in chat) when we know it's a U-not-V'd issue is unhelpful

**Comment by illode** [comment]
It seems to be broken again on Firefox 121.0, at least for me. I haven't tried any other versions. Chromium seems to work.

I assume the PIN is required because of https://github.com/kanidm/kanidm/issues/2274#issuecomment-1788259112? From the wording, it sounds like it goes from MFA (Biometrics / Laptop Password / whatever else as verification + Passkey) to effectively SFA (Passkey + click).

If that's the case, a solution might be to allow `userVerification` to be disabled only in combination with a password, perhaps as an alternative to TOTP in the Password / TOTP option. Unless I'm missing something, that would also have better worst-case security since kanidm requires decent passwords, while the Passkey + PIN is dependent on security key / OS / browser and can be something stupid like `1234`. At the very least, my Yubikey 5C nano allows `1234`.

**Comment by Firstyear** [comment]
> If that's the case, a solution might be to allow `userVerification` to be disabled only in combination with a password, perhaps as an alternative to TOTP in the Password / TOTP option. Unless I'm missing something, that would also have better worst-case security since kanidm requires decent passwords,

This makes the whole thing much more complicated. It also trains people the userVerification is optional. Especially true when most sites don't even check UV is set properly allowing MFA bypass to be trivially executed. 

Additionally it's confusing - it's hard enough to teach people to trust webauthn, let alone if the pin is sometimes there sometimes not.

I'd rather Firefox just fix their implementation at this point. It's been *years* since webauthn was introduced, let alone passkeys. It's been the direction of authentication for the industry for a while. There really isn't an excuse for them to be so asleep at the wheel right now. I'm not going to add in work arounds just because they can't seem to get it together.

**Comment by illode** [comment]
> This makes the whole thing much more complicated.

> I'd rather Firefox just fix their implementation at this point. It's been years since webauthn was introduced, let alone passkeys. It's been the direction of authentication for the industry for a while. There really isn't an excuse for them to be so asleep at the wheel right now. I'm not going to add in work arounds just because they can't seem to get it together.

Understandable. It _is_ absurd that they don't support setting a PIN after so long.

> It also trains people the userVerification is optional. Especially true when most sites don't even check UV is set properly allowing MFA bypass to be trivially executed.

> Additionally it's confusing - it's hard enough to teach people to trust webauthn, let alone if the pin is sometimes there sometimes not.

I was going to say I agree, but it occured to me that the average user probably has no idea what any of these words even mean. I'd honestly be surprised if they knew a single on of the OTP / Passkey / WebAuthn. Simply referring to the existing method as Passkeys and the workaround as WebAuthn or FIDO or something like that would probably be more than enough to separate them in the minds of users, even if they're basically the same under the hood.

This also made me think of a few improvements that could be made to the Credential Reset / Update page, namely around the usage of authentication-related terms, which I'll file a separate issue for.

**Comment by Firstyear** [comment]
> > I'd rather Firefox just fix their implementation at this point. It's been years since webauthn was introduced, let alone passkeys. It's been the direction of authentication for the industry for a while. There really isn't an excuse for them to be so asleep at the wheel right now. I'm not going to add in work arounds just because they can't seem to get it together.
> 
> Understandable. It _is_ absurd that they don't support setting a PIN after so long.

We are painfully aware. We assisted with development of the feature and it was painful for it to be accepted. We believe that at this point mozilla is relying on platform webauthn libraries (such as macos/windows libs) rather than develop their own. This will generally limit the issue to linux users, which likely means they will continue to ignore the issue ... :( 

> 
> > It also trains people the userVerification is optional. Especially true when most sites don't even check UV is set properly allowing MFA bypass to be trivially executed.
> 
> > Additionally it's confusing - it's hard enough to teach people to trust webauthn, let alone if the pin is sometimes there sometimes not.
> 
> I was going to say I agree, but it occured to me that the average user probably has no idea what any of these words even mean. 

Correct - https://github.com/kanidm/webauthn-rs is a library we made, and unlike any of the major vendors, we actually did human tests with non-tech people. One person when prompted for webauthn on their android phone thought they were being hacked. Most people think you're sending your fingerprint over the internet and so don't trust it. The whole thing is so fraught with user trust issues it's beyond a joke. 

> I'd honestly be surprised if they knew a single on of the OTP / Passkey / WebAuthn. Simply referring to the existing method as Passkeys and the workaround as WebAuthn or FIDO or something like that would probably be more than enough to separate them in the minds of users, even if they're basically the same under the hood.

That's why we call them passkeys in kanidm because it helps to distinguish them, and we want them to be associated with a replacement to user passwords, not a supplement to them. 

> This also made me think of a few improvements that could be made to the Credential Reset / Update page, namely around the usage of authentication-related terms, which I'll file a separate issue for.

**Comment by spacekitteh** [comment]
It's still an issue; trying to add a Yubikey in Firefox on Linux just redirects to a page saying

```
Error

An unrecoverable error occurred. Please contact your administrator with the details below.

Error Code: InvalidRequestState

Operation ID: <the id>
```

**Comment by Firstyear** [comment]
@spacekitteh what version please?

**Comment by spacekitteh** [comment]
@Firstyear 1.4.4

**Comment by yaleman** [comment]
Please update and check, there's been changes since that patch

**Comment by Firstyear** [comment]
Specifically https://github.com/kanidm/kanidm/pull/3403 which is part of 1.5.0
