### ISSUE TITLE
Orca setup script is broken 

### ISSUE THREAD

**Issue by Seba-T** [kanidm/kanidm#2437]
### I expected the following: 
Orca to setup the dev env and run as usual. 

### Kanidm version details
kanidm 1.1.0-rc.15-dev cf87993a1c
2024-01-18T19:30:50.278831Z DEBUG kanidm: Using 20 worker threads
Linux sebastiano-XPS-15-9520 6.2.0-39-generic #40-Ubuntu SMP PREEMPT_DYNAMIC Tue Nov 14 14:18:00 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Any other comments
Basically it always fails the authentication bit as the admin password variable is always blank since the command supposed to set it: `ADMIN_PW=$(grep -E "^admin password" "${KANI_TEMP}/kanifile" | awk '{print $NF}')` doesn't behave as it used to do. Basically in 0e504517159ab0d6eb325ce38e0cc2320b7394c7 this happened in setup_dev_environment.sh: 
```diff
- echo "admin password:     ${ADMIN_PASS}"
```
and since `kanifile` comes from: `../../scripts/setup_dev_environment.sh | tee "${KANI_TEMP}/kanifile"`) that's what broke it. My first instinct was adding the admin password thing back but gate it behind a flag in to make it run only when required by orca. On the other hand I don't really know why it was removed in the first place, so I figured @yaleman has a better understanding on what is going on there and I might ask for some feedback before doing anything :)

**Comment by Seba-T** [comment]
(I just realized I linked the wrong commit, I'm gonna fix when I get home)

**Comment by Firstyear** [comment]
We might want to consider converting this to ansible rather than a shell script so we could coordinate vms for benchmarking?

**Comment by yaleman** [comment]
Yeah I removed admin_pass from setup_dev_environment because it wasn't needed after `idm_admin` permissions changed. I've never really gotten orca to work so getting it some love would be handy.

**Comment by Seba-T** [comment]
> Yeah I removed admin_pass from setup_dev_environment because it wasn't needed after `idm_admin` permissions changed. I've never really gotten orca to work so getting it some love would be handy.

So I shouldn't do any harm if I just add it back right?

**Comment by yaleman** [comment]
Add it specifically to the orca script because it's needed there.

**Comment by Seba-T** [comment]
> Add it specifically to the orca script because it's needed there.

Sounds like a plan :) I already got that patched somehow but now it won’t let orca make admin an idm_admins, and I really don’t know how to override that

**Comment by yaleman** [comment]
Don't do that then, it's not necessary

**Comment by Seba-T** [comment]
So I can just remove the bit that tries to add admin to idm_admins

**Comment by yaleman** [comment]
I'd say look at all the actions that things are doing and go from there, rather than just one-off troubleshooting. Orca hasn't really been maintained/tested as often as the rest of the tooling.

**Comment by Seba-T** [comment]
Uh I'm noticing it now, thanks!

**Comment by Firstyear** [comment]
I probably need to look into a cleanup of this with @Seba-T first then :)

**Comment by Seba-T** [comment]
I actually just started poking around it again, what a perfect timing :D

**Comment by Firstyear** [comment]
@Seba-T I'm suspecting we could re-write it as I have some new and better ideas this time ....

**Comment by Seba-T** [comment]
Yeah I mean I'd gladly redo it from scratch rather than endlessly struggle against something that hasn't been maintained in ages (which has been my experience so far :p)

**Comment by Firstyear** [comment]
Well, mostly I was thinking about the way I approached orca in the past was "benchmark" and I modelled a lot of things on ldclt from 389-ds which is their benchmark tool. 

But recently @jinnatar pointed out she wanted to see an "enterprise simulator". Where the benchmark isn't just "sterile" kind of do-searches like ldclt was doing, but should be about simulating user actions.

Then that got me thinking about a way to potentially use that as a basis to not only do an enterprise simulator, but also how to potentially model a more controlled test mode.

Currently the design has workers that take a task queue and then execute the tasks and report on the stats. That ends up with a thread-per-worker and each worker just shoves out tasks etc. But it's hard to see how the tasks the correspond to a user, or different things, and it's hard to do other kinds of interactions. 

Instead, I think we could do it like erlang. Instead of workers, we spawn a task for each "person". Then each of these tasks has a little schedule, like "login, click about, idle for some time, then do some more etc". It models how a person would interact. At the start of the test, we can have each "task" create it's own user/password etc, rather than the crazy batch thing we have now. It also allows easier interleaving of things naturally based on user interactions. 

We still need a centralised stats-collector but that model already exists, so we can time operations for each task.

This also then makes it easier to do different kinds of tests later like the high-search load tests (direct each "person" to just search) etc. 

I think for now we drop the LDAP support too, we can add that back later,

**Comment by Firstyear** [comment]
So thinking about it, I think actually https://github.com/kanidm/kanidm/issues/1131 has overlap to this - both this issue and the mentioned one "need a way to setup a db of expected content" so I think we can roll these up together.

**Comment by Seba-T** [comment]
> So thinking about it, I think actually #1131 has overlap to this - both this issue and the mentioned one "need a way to setup a db of expected content" so I think we can roll these up together.

In this instance wouldn't we just need to create some users account and then take it from there? Or is #1131 about implementing a setup tool that allows to specify what you want to fill the db with, i.e. "generate 10k users and put them in x group"

**Comment by Firstyear** [comment]
Well it turns out they're the same problem.

We need a way to setup a db full of expected content.

We need a way to setup a db full of expected content *AND* then we do a load test against that content.

**Comment by Seba-T** [comment]
Mhh makes sense. We'll have a way to setup a db full of expected content then :p
