### ISSUE TITLE
error message are horrible

### ISSUE THREAD

**Issue by LuckyTurtleDev** [kanidm/kanidm#2444]
I try to setup kanidm and get the following error:
```
🚨 [error]: Failed to configure TLS parameters -> ErrorStack([Error { code: 2147483661, library: "system library", function: "file_ctrl", file: "crypto/bio/bss_file.c", line: 297, data: "calling fopen(/keys/ssl.crt, r)" }, Error { code: 268959746, library: "BIO routines", function: "file_ctrl", reason: "system lib", file: "crypto/bio/bss_file.c", line: 300 }, Error { code: 168296450, library: "SSL routines", function: "use_certificate_chain_file", reason: "system lib", file: "ssl/ssl_rsa.c", line: 448 }])
```
This is an horrible error message. It give me no useful information why configure TLS parameters  has failed.

**Comment by yaleman** [comment]
Indeed, could you please share your config/setup so we can try and figure out how to help you with it? Getting to that point normally indicates something's gone messily wrong.

**Comment by yaleman** [comment]
(and it's partially because we get bad info back from the various system libraries, different versions of openssl throw different errors, etc)

**Comment by Firstyear** [comment]
Yes, this message is rough because it's from openssl. Not tons we can do there. Saying that, it does have the required information: `data: "calling fopen(/keys/ssl.crt, r)" }` - This indicates an error reading `/keys/ssl.crt`. I would expect that either this path is invalid (doesn't exist) or is missing permissions. 

I'll add some extra bits to help though for future.
