### ISSUE TITLE
gidnumber can fall into systemd container ranges

### ISSUE THREAD

**Issue by 0xC0ncord** [kanidm/kanidm#2601]
When creating a user in Kanidm and enabling a posix account for them, the associated user's GID number can fall into the systemd container UID range 524288-1879048191 (https://systemd.io/UIDS-GIDS/).

The immediately noticeable effect of this is if the user logs on through `pam_kanidm`, they cannot view their own user journal because systemd considers their UID to be a systemd container user and will not create dedicated journal files for them (https://github.com/systemd/systemd/blob/main/src/journal/journald-server.c#L447 https://github.com/systemd/systemd/blob/main/src/basic/uid-classification.h#L18-L20).

```
$ id
uid=1688334410(concord) gid=1688334410(concord) groups=1688334410(concord),2029292874(posix_users),3982434320(sysadmins) context=unconfined_u:unconfined_r:unconfined_t:s0

$ journalctl --user
Hint: You are currently not seeing messages from the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
No journal files were opened due to insufficient permissions.
```

Additionally, the gidnumber can fall into the range 2147483648-4294967294 which systemd considers to be dangerous to use:
>Note that the range 2147483648…4294967294 (i.e. 2^31…2^32-2) should be handled with care. Various programs (including kernel file systems — see devpts — or even kernel syscalls – see setfsuid()) have trouble with UIDs outside of the signed 32-bit range, i.e any UIDs equal to or above 2147483648. It is thus strongly recommended to stay away from this range in order to avoid complications. This range should be considered reserved for future, special purposes.

Finally, it looks like it may be technically possible for the gidnumber to land on 2^32-1, which appears to be reserved:
>4294967295, aka “32-bit (uid_t) -1” → This UID is not a valid user ID, as setresuid(), chown() and friends treat -1 as a special request to not change the UID of the process/file. This UID is hence not available for assignment to users in the user database.

**Comment by Firstyear** [comment]
*sigh*. Great to know that systemd just claims most of the UID number space for itself with reckless abandon. 

We already cap our uid numbers at a minimum of 65536. So we are safe on that side. Going over i32max (2147483648) I can understand in a way, but it's a wonderful display of linux's terrible history of uid/gid modelling. 

But systemd claiming 524288 through 1879048191? That's a *huge* chunk of ids. 1878523903 infact. That leaves us with 65536 through 524287 and 1879048192 through 2147483647.

Because we allocate the gid as a random set of bits from the tail of the uuid, we have to also consider the birthday problem too. Currently because we used 65536 through u32 max, it gave us the ability to recommend that for sites with >9000 users, they consider manual uid allocation as that only had a 1% chance of collision. Given this is logarithmic, this leaves us with 24 bits of usable space, we need to revise this down to (I think) ~2000. 

For now the easy fix is to just mask on the uid generator to always ensure it starts with `0x70000000` since `0x70000000` to `0x7fffffff` is the range left to us.

**Comment by Firstyear** [comment]
It gets better. FreeIPA allocates straight into the nspawn range. So I need to also come up with a way to handle that now ....

**Comment by yaleman** [comment]
systemd's container allocations *should* help solve for that whole discussion about how we allocate ids for container workflows doesn't it?

**Comment by Firstyear** [comment]
Yes and no. FreeIPA stomps that whole range by default, so if you sync from freeipa, then you have to contend with that.

But otherwise, yes it should I think? Because we have to partition off a huge chunk which can then be used.

**Comment by yaleman** [comment]
Oh yeah, I was trying to ignore FreeIPAs drunkenness

**Comment by Firstyear** [comment]
I can't really throw too much shade, we made the same mistake though. Difference is we can fix it ....
