### ISSUE TITLE
Add kinda "published" attribute to oauth2 apps

### ISSUE THREAD

**Issue by dvv** [kanidm/kanidm#2654]
The rationale is to develop/test applications while not showing it under '/ui/apps'.
TIA

**Comment by Firstyear** [comment]
I'm confused about this. Applications only show up if you are a member of a group that is allowed to access the group. You could have say "oauth2 app access" as a group and make it's member "oauth application testers". Then only test users see it. Once you're ready to go, you add your users to the oauth2 app access group, or you add idm_all_persons or whatever.

**Comment by dvv** [comment]
I see. Perfectly valid.

**Comment by Firstyear** [comment]
It would certainly be nicer if there is an easier way to admin groups though. :)

**Comment by dvv** [comment]
Well, I agree. It's just sad. An excellent robust access rules system of idm can not be used by an oauth2 app (due to idm is locked to use own localStorage tokens) while idm per se not exposing friendly means to manage identities (admin ui pages are nearly useless, self-service allows only managing credentials, not name/displayname/email or authorized group-membership).
And when using a high-privilege service account as actor for own crafted admin panel (an oauth2 app) it is necessary to reinvent access rules.

**Comment by Firstyear** [comment]
Yes, because today we assume that users are comfortable with the cli. If we invested all our time in the cli and webui, we'd end up not getting as far, especially because I'm not a web developer at all. We need help to improve that, and it takes people to step up and contribute. It's just the reality as well that web development takes forever too and it's much harder to actually make progress.

Right now we have other priorities. Do we want a web admin ui? Absolutely. Do we have lots of people asking for lots of competing things all the time? Also yes. So right now we have to do the things that will benefit the most users at once. Today that's getting replication coordination working, which is what I'm working on. It's then implementing better apis to manage users and groups like scim so that a web ui is easier to develop, and scripts and batch operations are easier to perform. 

I know you have things you want to achieve, and I assume achieve them "very soon", but we are trying to do a lot of things with an eye to long term future support. And the things we are doing now are the ground work for what you want to achieve.

**Comment by dvv** [comment]
off
That's why I'm sad, yeah.
Windows people (99% of ours) won't use cli as they hardly know what it is.
Managers won't use cli to manage their groups as they as not paid for such knowledge.
Admins could be using cli but they insist to offload daily user' tasks to user' self-service.
Frontend developers can implement UI but not in WASM.
The rest is me sole who's trying to explain the above people the virtue of idm' cli usage )
/off

Still thank you for the great product!

**Comment by Firstyear** [comment]
I know, I'm sorry it's taken so long. I wish I could make it happen immediately but I don't have magic powers :(

**Comment by dvv** [comment]
Wish you those powers!

**Comment by dvv** [comment]
Still I want to stand tall.

I've managed the following "solution" to transfer idm bearer to oauth2 app:
1. login to idm and elevate to update profile
2. go to admin, groups. Here a _soft navigation_ to /ui/admin/groups is performed
3. have a traefik to serve custom /ui/admin/groups page which redirects to oauth2 app passing localStorage bearer. That page shall store that bearer in cookie and redirect to app's group management page
4. app's backend should honor the bearer from cookie from 3 when requesting kanidm

This works but requires to hit browser refresh after 2 (to reload custom page because of soft navigation) -- bad UX.

So if I solved the 2 to 3 transition seamlessly I'd have enough means to cope with UI in parallel.

Wonder how to do that? )
