### ISSUE TITLE
Restrict client login by IP

### ISSUE THREAD

**Issue by boogiewoogit** [kanidm/kanidm#2813]
If I'm only ever using kanidm's `admin` and `idm_admin` accounts locally through SSH, I assume there is no reason to expose them and make them brute-forceable from anywhere.

Can I restrict access to accounts/groups by IP, so I can, for example, make them only accessable from the host kanidm is running on?

**Comment by yaleman** [comment]
Not currently. 

There are very small rate limits to password guesses and large entropy enforced when the passwords are generated, which provide a high level of brute force protection, but if you're concerned I'd suggest monitoring logins with those accounts.

**Comment by Firstyear** [comment]
Those accounts can only have 100 pw attempts per day, and the password has 48 characters from the readable set of 55 chars, which yields more than 256bits of entropy. It would be easier for an attacker to attempt to bruteforce AES keys than the admin/idm_admin passwords. 

PS: The admin and idm_admin accounts *aren't* accessible via SSH by defalut because they aren't posix accounts, and they also need posix passwords configured for SSH which is distinct and separate from their service account passwords.

**Comment by yaleman** [comment]
> PS: The admin and idm_admin accounts _aren't_ accessible via SSH by defalut because they aren't posix accounts, and they also need posix passwords configured for SSH which is distinct and separate from their service account passwords. Use of the posix account passwords also doesn't allow granting of the RW privs associated to the admin and idm_admin users.

Pretty sure they mean "while SSH'd to the Kanidm instance" rather than "as ssh users" (well, I sure hope so! 😄)

**Comment by boogiewoogit** [comment]
Thanks for the details, I overestimated the risk. :slightly_smiling_face: 

> > PS: The admin and idm_admin accounts _aren't_ accessible via SSH by defalut because they aren't posix accounts, and they also need posix passwords configured for SSH which is distinct and separate from their service account passwords. Use of the posix account passwords also doesn't allow granting of the RW privs associated to the admin and idm_admin users.
> 
> Pretty sure they mean "while SSH'd to the Kanidm instance" rather than "as ssh users" (well, I sure hope so! 😄)

Yes, that's what I meant. 😄

**Comment by Firstyear** [comment]
Well part of the problem here is linux/container security - or rather, lack there of. 

Linux systems have a boundary which is the network for ssh and a tty to login. Once you are past that, generally you use the same credentials to sudo to become root, or you can just privesc to get root even when you aren't supposed to. The time of introduction to time of fix for a standard kernel vuln is 7 years (per kees cook). Container developers famously say "containers don't contain". I'm sure there are more examples.

So when we look at it like this, then the centre of your network authentication isn't a machine you should be allowing everyone to access. It should be constrained to people who require access to that machine to perform their job function, or recover the system in an emergency. Any access to that machine, should be considered equivalent to root, or in the kanidmd case, idm_admin/admin. 

There is a single exception to this though - that is, if you have SELinux on your machines, with SELinux confined users for all logins. This actually enforces a proper set of controls on the machine and can confine and limit priv esc damage. The damage here is only possible with users who can sudo to root because they can just then disable and bypass selinux.

**Comment by yaleman** [comment]
Getting back on topic, I'd say the ability to limit the source IPs for a user/group to access the API would be an interesting feature request, but not yet in planning.

**Comment by Firstyear** [comment]
We already have ip access limits as a request, so I'm closing this in favour of the other issue.
