### ISSUE TITLE
kanidm pw-sync inside an account

### ISSUE THREAD

**Issue by Firstyear** [kanidm/kanidm#287]
In some cases we split passwords between roles (login, posix, radius). We could consider for accounts with few privileges to have these auto-synced.

**Comment by Firstyear** [comment]
I actually think this should be closed - once we have ldap application passwords, then there isn't a point to have pw sync. If anything we want unix pw to always be different to the main pw if set.

**Comment by Firstyear** [comment]
Closing in favour of application passwords, and because we now support this on the sync tool side for those environmnets.

**Comment by ds-sebastian** [comment]
From a self-hosting and user perspective I like this idea, despite it being less secure. One password for my family to remember when they see the crab :) 

This would allow me to not have to setup a separate LDAP instance just to use the sync tool.

**Comment by yaleman** [comment]
What specific use case are you talking about in this instance? A service which relies on LDAP for authentication?

**Comment by ds-sebastian** [comment]
Yes, so I understand the default expectation is separate passwords for LDAP(/Posix) and Login(OIDC Auth), correct? I have apps that still rely on LDAP and others that use OIDC. I'd find it convenient for non-technical users to be able to sync the same password for both options, simplifying usage. Especially since they might not know which is which if they have to reset one.

**Comment by CEbbinghaus** [comment]
I know for a fact that all of my users are going to set their POSIX password to their regular password if I force them to set 2. So we don't gain much security since the second copy of the password will be the weakest link so this feature does nothing to improve security and everything to worsen user experience. The only way this could help is if we forced the two passwords to be different but that would in turn be taking an active step to make the user experience worse. 

Another thing to consider is the accessibility aspect. while yes 1 shared password is not secure it is accessible especially to those with bad memory. I have a bunch of users that will call up my site once or twice a fortnight and to them even just 1 password can be a challenge. Having to remember 2 different passwords and know which to use when will certainly discourage a lot of them to use any of my services. 

I would much rather see some kind of brute force protection for LDAP (if that is even possible) rather than something that has an active hand in worsening the UX.

As a last point I wanted to raise something I had already raised in the GC which is that I would prefer a config option (something like `insecure_ldap_password_fallback`) which would first try the POSIX password and if not defined then fall back to the regular password. Tgat way I can set a POSIX password for myself which is different but other users will just have their regular password work.

**Comment by Firstyear** [comment]
There already is bruteforce protections: https://github.com/kanidm/kanidm/blob/master/server/lib/src/idm/server.rs#L1410 

The problem here is that generally when the topic comes up for ldap passwords, the use case is generally better solved by application passwords. I'd be open to re-consider if you can describe in detail the use case you have and why app passwords can't solve them.

**Comment by CEbbinghaus** [comment]
Sorry it took me so long to respond. Haven't had time to dedicate to my home server. As I understand it application passwords (more like service account credentials) are used for authenticating applications to query the ldap server, They serve to give a way to list the users but not a way to authenticate any one given user. For that a bind is required to make sure that the password the user entered is valid for the username. All we want is for the POSIX password used for authentication binds to default to the regular user password if no specific POSIX password has been set

**Comment by CEbbinghaus** [comment]
After digging through the code it seems to me that application is an entirely different feature that looks to instead enable different passwords to be defined per application? There doesn't seem to be much documentation about it so I will have to know more before being able to judge whether it is a suitable alternative or not

**Comment by CEbbinghaus** [comment]
Created a draft PR to help drive conversation. Keen to hear what the application passwords are that you were referring to, Just wanted to learn more about the kanidm codebase and implement the feature I was asking for

**Comment by CEbbinghaus** [comment]
PR has migrated to a full PR and should be merged some time this week with any luck
