### ISSUE TITLE
Allow unix-tasks to create symlinks in another directory

### ISSUE THREAD

**Issue by antonl** [kanidm/kanidm#2891]
I'd like to implement an NFS home directory mounting structure where the user's home is automounted at eg `/u` and the
tasks daemon would create the appropriate symlink in `/home`. I think this is currently impossible. Are there security implications for allowing this? If not, could I try my hand at a PR?

**Comment by Firstyear** [comment]
Yep that sounds fine to me. I've considered also making this capable of bind mounting as well actually because it may be nicer than the symlinks ...

The reason for the limit right now with /home and the symlinks is to prevent the daemon from ever trying to "break out" or stomp on system files. So I think provided there is some kind of control like "the home dirs are in /home but symlinks are made to /u" then it's fine. Currently I think we make this "home prefix" and it assumes the home dir and link are in the same dir, but I'd suggest something like an optional "home_mount_prefix" or something and when set it causes the symlink to go from /home/name to /u/uuid or similar. Does that seem reasonable?

**Comment by antonl** [comment]
Yes, that is exactly what I had in mind. Cool, I'll give it a shot! I'm new to rust, so I'll see if I can accomplish something useful.

**Comment by Firstyear** [comment]
Feel free to PR any works in progress you may have. We're happy to help. https://github.com/kanidm/kanidm/blob/master/unix_integration/resolver/src/bin/kanidm_unixd_tasks.rs is the file you'll need to look at :)
