### ISSUE TITLE
LDAP query wildcard matching doesn't work with prefix/suffix

### ISSUE THREAD

**Issue by SinnySupernova** [kanidm/kanidm#2978]
### I did this
`ldapsearch -x -b "dc=id,dc=example,dc=com" "(&(|(objectClass=posixAccount)(objectClass=posixGroup))(mail=*@example.com))"`

### I expected the following
it shows properly matched results that are present when using
`ldapsearch -x -b "dc=id,dc=example,dc=com" "(|(objectClass=posixAccount)(objectClass=posixGroup))"`

### This happened instead
0 matched results

### Kanidm version details

- Output of `kanidm(d) version`: kanidmd 1.4.0-dev (up to date)
- Are you running it in a container? If so, which image/tag?: docker, kanidm/server:devel

### Any other comments
`*` works, while `prefix*` `*suffix` `prefix*suffix` don't work

**Comment by Firstyear** [comment]
Okay, there was a bug here, but there is a second detail here you need to understan. *mail is not visible as anonymous*.

This is because mail count as PII, so to access the mail attribute, you need to use an api-token with ldap https://kanidm.github.io/kanidm/stable/accounts/service_accounts.html#api-tokens-with-ldap and give the service account the needed access to read idm_people_pii_read such as mail https://kanidm.github.io/kanidm/stable/access_control/intro.html#default-permission-groups

**Comment by Firstyear** [comment]
Also I'm going to add a dedicated mail server access control group now, because this has come up a few times and pii read is a bit too broad.
