### ISSUE TITLE
REST API: SSH key tags not gettable

### ISSUE THREAD

**Issue by yaakov-h** [kanidm/kanidm#2983]
Using Kanidm 1.3.0:

Looking at the Swagger docs and Nginx request logs, the APIs for SSH public keys seem to be:

`/v1/person/{name}/_ssh_pubkeys` - returns all SSH public key values as a JSON array
`/v1/person/{name}/_attr/ssh_publickey` - returns all keys as a JSON array of strings formatted as `"<tag>: <value>"`
`/v1/person/{name}/_ssh_pubkeys/{tag}` - returns a single SSH public key value if you know it's "tag".

There appears to be no way to programmatically get a SSH public key's tag.

I would have expected one of `/_ssh_pubkeys` or `/_attr/ssh_publickey` to return a JSON object along the lines of:

```json
{
  "tag1": "type base64 user@host",
  "tag2": "type base64 user@host"
}
```

however that only current result I can get, which then requires string parsing, is:

```json
[
  "tag1: type base64 user@host",
  "tag2: type base64 user@host"
]
```

As an aside, it would also be nice to have an API that just returns the `authorized_keys` file's expected format, without JSON.

**Comment by yaleman** [comment]
It'll likely be a HashSet/Btree being serialized which is... fun to unpick

**Comment by yaleman** [comment]
Actually it's ... even harder to unpick, because of how it all works internally. I'm poking around to see what can be done about it.

**Comment by yaleman** [comment]
this will have to wait for #2315

**Comment by yaakov-h** [comment]
Why does separating keys and values depend on SCIM?

**Comment by yaleman** [comment]
Because @Firstyear's going to sort a bunch of internal state-getting stuff on the way to it. There's no simple "oh just pull out keys and values" magic, I tried for a few hours today and couldn't find the way to sort it.

... that and we have to add endpoints for this, because changing the existing ones would break all existing clients.

**Comment by Firstyear** [comment]
@yaakov-h Internally Kanidm attributes are all strongly typed and contain maps. So something like ssh-key is internally represented as:

```
key: label
value: SshPubKey {
    type
    public
    comment
}
```

The problem though is how we *format* these for presentation. 

Currently, the code for rendering these out as a "protocol value" aka something our (very aging and not good) REST API exposes also shares the same path with *LDAP*. 

This means that currently, SSH keys are in an awkward spot where they have to be presented the same way that LDAP expects them to be - which then limits us based on how SSSD behaves.

This means that either we need to:

* Add an LDAP value render here in this case.
* Add a special case for SSH keys
* Expose the SSH key in it's internal map form via some other api.

It turns out we need to do the latter (and I'm working on it today) because of SCIM. That way the current proto-string behaviour stays for LDAP, and we move to the better SCIM interface.

**Comment by Firstyear** [comment]
I believe this is what we call "tech debt" and "growing pains" :)

**Comment by Firstyear** [comment]
As an update here, I'm just about to wrap up the last major PR which was blocking SCIM, so we should have a way to get this data shortly.
