### ISSUE TITLE
How to set scopes given_name and family_name?

### ISSUE THREAD

**Issue by EHEX-schildt** [kanidm/kanidm#2993]
### Is your feature request related to a problem? Please describe
context:
We currenty want to connect a SAML webapp with kanidm and are useing SATOSA as a OIDC proxy for that.
The webapp want a "First Name Attribute" and "Last Name Attribute" to map them into a UserProfile.

But this could also be needed by a Non-SAML webapp - so lets assume i have a **OIDC Resource Server that want the given_name and family_name scopes**.

In the UserInfo that kanidm returns some [scopes from "profile"](https://kanidm.github.io/kanidm/stable/integrations/oauth2.html#create-the-kanidm-configuration) like "name" and "preferred_username" are included, but family_name, given_name are not.

If i look at the User Object in kanidm - i can't find them:
`kanidm person get test.user`

And there is no Option to set them:
`kanidm person update -h`

I also looked at the posix Attribut Options – with the same result:
```
kanidm person posix show test.user
kanidm person posix set -h
```

### Describe the solution you'd like

I  would like to have the Option to set values for the oidc scopes given_name and family_name via `kanidm person update` or similar

### Describe alternatives you've considered
Workaround with [custom_claims](https://kanidm.github.io/kanidm/stable/integrations/oauth2/custom_claims.html)
for each Resource Server:
```
kanidm system oauth2 update-claim-map-join <Resource Server> given_name ssv
kanidm system oauth2 update-claim-map-join <Resource Server> family_name ssv
kanidm system oauth2 update-scope-map <Resource Server> <group> given_name family_name profile openid email
```

for each user and Resource Server – **This is pain for 100+ Users multiplied by the number of Resource Servers**:
```
kanidm system oauth2 update-claim-map <Resource Server> family_name test.user User
kanidm system oauth2 update-claim-map <Resource Server> given_name test.user Test
```
And this is also Pain in case of a name change.

**Comment by yaleman** [comment]
These are attributes we can look into adding, it's not currently possible.

**Comment by Firstyear** [comment]
We had a pretty long chat about this in the matrix channel with @tumbl3w33d so I want to summarise it over here to help.

What you're running into here is a pretty big piece of "systemic tech debt". Names historically have been centred around british-derived culture, especially give the history of a lot of this tech is american. This has caused a lot of american-isms to be baked into standards and expectations.

If we look at https://www.w3.org/International/questions/qa-personal-names.en we can see that names aren't quite so simple though. This is why kanidm breaks tradition and defines two fields - displayName which is how you want to be addressed and known by others, and legalName which is a private/hidden field that only should be known by limited numbers of persons when explicitly needed.

This conflicts to things like firstName/lastName - this is not only based highly in american cultural norms, but also the idea that a legalName combo is how you want to be publicly known. I can list many examples where people would *not* want their legalName to be their public identity! 

As a result of this, this is why you are running into this problem - we've made choices to protect user's data from situations like this. we certainly don't believe that PII should be given out to SAML/OIDC without consent and without need.

But certainly this doesn't avoid the problem - there are a lot of broken systems out there that expect firstName/lastName.

The question here is "what can we do"?

- Disable the attribute map in Satosa

Satosa allows you to disable the attribute mapping. Since mattermost at the other end does not require the given/last name, then this should resolve the issue https://github.com/IdentityPython/SATOSA/blob/master/doc/README.md#custom-attribute-release

- Map something else

The best candidate here would be to map displayName to givenName (firstName). That way we still show how the user wants to be know in an appropriate field.

- add OtherNames

As above, but also add a "displayOtherNames" which maps in to the lastName location. If not set, we can default to something like "-" since some broken clients expect a non-empty str value to be set.

- add a separate displayGivenName and displayOtherNames field.

Rather than map things through, we give the user the ability to set these two fields in the way that they wish. This does have some risks re the w3c document since client applications are liable to display these incorrectly for some cultures.

**Comment by EHEX-schildt** [comment]
Thanks for your explanation.

We adjusted our Mattermost setup:
* **family_name** and **given_name** are **not mapped**
* **nickname** (aka displayName) **mapped** to Nickname
* preferred_username and email mapped to Username and Email

This means:
* "First Name" and "Last Name" are empty for new Users
* Users can set "First Name" and "Last Name" on there own, if wanted.
* User Profile looks OK and Functions like User mentions works fine without "First Name" and "Last Name".

No changes in kanidm needed.

**Comment by Firstyear** [comment]
Glad you solved it!
