### ISSUE TITLE
[BUG]: Creating a new Public client causes server to fail to start up

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#3097]
### I did this

```shell
kanidm system oauth2 create-public foo foo https://foo
```

Then restarted the server

### I expected the following

The server to start

### This happened instead

It failed to start

```
45a380e7-74eb-44f5-8800-8ba79cedeecd INFO     system_initialisation [ 124ms | 38.77% / 100.00% ]
45a380e7-74eb-44f5-8800-8ba79cedeecd INFO     ┝━ initialise_schema_core [ 60.1ms | 48.51% ]
45a380e7-74eb-44f5-8800-8ba79cedeecd INFO     ┝━ ｉ [info]: Prepare to re-migrate from 7 -> 8
45a380e7-74eb-44f5-8800-8ba79cedeecd INFO     ┕━ migrate_domain_7_to_8 [ 15.8ms | 12.73% ]
45a380e7-74eb-44f5-8800-8ba79cedeecd ERROR       ┝━ 🚨 [error]: Unable to proceed. Not all oauth2 clients have strict redirect verification enabled.
45a380e7-74eb-44f5-8800-8ba79cedeecd ERROR       ┕━ 🚨 [error]:  | missing_oauth2_strict_redirect_uri: foo@localhost
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Unable to setup query server or idm server -> MG0007Oauth2StrictConstraintsNotMet
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to start server core!
```

### Kanidm version details

- Output of `kanidm(d) version`: v1.4.0-dev  (git commit 4e125b50434c79a707fb61075612f65430c3edf8)
- Are you running it in a container? If so, which image/tag?: no
- If not a container, how'd you install it: macos 
- Operating System / Version (On Unix please post the output of `uname -a`): macos 

### Any other comments

Derp.

**Comment by Firstyear** [comment]
Hmm  that's a weird one. It should have created it with the strict redir set?

**Comment by yaleman** [comment]
Indeed!

**Comment by gbw** [comment]
FYI this bit me when switching from `docker.io/kanidm/server:1.3.3` to `ghcr.io/kanidm/kanidmd:devel (sha256:3fcd9cf68511677f6d51d105d3bfb2e6e78e8e4e58ed5da05d0282614b4c1d57)`. I was able to resolve by switching back to `1.3.3` and explicitly setting each client with `enable-strict-redirect-url `. I suspect admins will run into this issue when upgrading.

Could the migration be changed to add the strict validation so that it is more graceful or is that considered too surprising behavior?

**Comment by Firstyear** [comment]
@gbw It won't be an issue during an upgrade from 1.3 to 1.4. The reason it's a problem on devel was a specific behaviour in how devel versions starts up and apply migrations. Effectively on a devel version it *re-runs* the 1.3 -> 1.4 migration every start up. But for release versions this *doesn't* happen. That's why it affected devel, but not stable, since stable won't re-run the migrations multiple times over.

**Comment by gbw** [comment]
Ahh thank you for the context!

**Comment by lf-** [comment]
This *does* happen on 1.3.3 -> 1.4.0 migration for me on NixOS. I don't know what happened there. However, I don't think this should have *ever* blocked server startup, since it breaks the control plane necessary to fix it if it is broken, which makes it essentially impossible to fix AFAICT?

**Comment by Firstyear** [comment]
@lf- If anything happens from 1.3.3 to 1.4.0 the transaction is aborted and rolled back and no changes are made.

Additionally, we ask you to take backups before an upgrade.

Did you run the pre-upgrade check tool to ensure the upgrade would work? On 1.3.3 `kanidmd domain upgrade-check`

**Comment by darix** [comment]
upgrading to latest Tumbleweed also broke jdsn's and my kanidmd instances. how should one recover from this error?
couldnt the code just disable the oauth2 app and not fail to start the whole server?

**Comment by jdsn** [comment]
I had to downgrade to 1.33 to be able to start the service again.
Either disabling the oath2 app or reading the config as if enable-strict-redirect-url was set (as it is enforced anyway) plus a warning in the log would be easier to deal with (fixing the issue without the need to downgrade).

**Comment by Firstyear** [comment]
If you run the pre upgrade check *it tells you* which clients were missing strict redirect uri enforcement. 

It doesn't *break* the instance either. If the upgrade fails, no changes to the db are made and you can start 1.3.3 again. 

I'm really sorry that this was not an easy experience for you, but we did provide every tool we could to assist before time to prevent these issues. We never just "break" something. We give you a whole release of advanced noticed for the pre-upgrade check in case there are administrator actions required for a successful upgrade.

**Comment by Firstyear** [comment]
If there is a bug here, it's that we aren't telling admins to run the pre-upgrade check the moment the finish an upgrade so they have as much notice as possible.

**Comment by darix** [comment]
well the pre-upgrade check isnt exactly integrated into zypper? and we are using the kanidm packages in Tumbleweed that you yourself provide.

**Comment by yaleman** [comment]
It's in the software, please feel free to PR in the required changes to make it part of the packages and I'll review

**Comment by lf-** [comment]
IMO the thing that would be helpful here is if the pre-upgrade check complains in logs on every startup of the older version. I actually would have noticed those, but I would not have thought to run a pre-upgrade check because I don't *separately* manage the versioning of kanidm so generally only notice the upgrades once they have already been run and already fail to start up. It *is* easy to revert on NixOS, but I currently don't do anything to really pay attention to the specific upgraded versions.

**Comment by Firstyear** [comment]
@lf- Then it becomes another noisy log item people ignore. That's why we chose to have an interactive tool that people have to engage with to ensure they can proceed. 

It's rare that these pre-upgrades require intervention, but when they do, we require a human admin to actually act in these cases, we can't just automate this away. There is no one size fits all answer here, because reality is we need the admin of the instance to be engaged and involved in their upgrades.

**Comment by lf-** [comment]
Maybe people will ignore the logs. But I think putting information meaningful to the administrator into there, particularly pertaining to a misconfiguration that will bite them in the future, *is* pertinent, and if it gets ignored, such as it is; it's only there if the config is about to become broken. Often when web apps do this they might show a banner on login to the admin UI. Perhaps Kani could do this with the CLI also?

My issue here isn't that upgrades require intervention, that's fine, it's that upgrades to 0.4.0 require rollback (which most package managers are bad at) 100% of the time if you didn't notice ahead of time by reading release notes, because the upgrade breaks the control plane necessary to fix it on the new version. It's also not great that the error message doesn't mention the actions necessary to remedy the problem.

The error when 0.4.0 fails to start up could mention the steps to fix the issue (rollback, apply specific actions). The startup of 0.3.3 could say there is a service degradation since it will break on the next upgrade. The 0.4.0 could fail to start up and have a temporary override that at least brings up the control plane enough to apply the admin actions while denying all other requests (for example).

There's several changes over the status quo that would make this ultimately tiny and theoretically trivial to fix breaking change less painful to administrators who are paying approximately the average amount of attention (reading service logs is perhaps even above average).

**Comment by Firstyear** [comment]
> particularly pertaining to a misconfiguration that will bite them in the future, is pertinent, and if it gets ignored, such as it is;

But by the same token, if the admin is ignoring the practices that we [clearly spell out](https://kanidm.github.io/kanidm/stable/server_updates.html#general-update-notes) and [draw attention to](https://github.com/kanidm/kanidm/blob/master/RELEASE_NOTES.md#140-important-changes) then we can't do much either. 

> The error when 0.4.0 fails to start up could mention the steps to fix the issue (rollback, apply specific actions).

We automaticaly roll back for you. The user doesn't need to do anything. If the upgrade fails, the error states:

```
Unable to proceed. Not all oauth2 clients have strict redirect verification enabled.
missing_oauth2_strict_redirect_uri = oauth2_client_name ...
```

Not a perfect error, but it's pretty descriptive about the problem, what you need to do (enable strict redirect verification), and the affected oauth2 clients that need alteration. 


But ultimately, I think you've hit the nail on the head - linux package managers are just bad for delivering applications like this where there is a possibility you need to roll back. Package managers are *especially bad* if people are yolo-upgrading their machines without paying attention. I can see how a distro like nix avoids this with parallel versions, and docker because you can run the container based on some tag X, but without a lot of extra labor and effort, something like opensuse is not good for this. 

This is a big reason we advise people to use the containers rather than packaged versions of the server - I never actually wanted to package the server for opensuse in the first place, I can't remember who but someone pressured me quite extensively to do it. Packages take control away from the user to be able to manage things like this.

I think the best thing we could do is have a better way to notify a group of users via the webui and cli tools about upcoming administrative actions and events ( #1615 ) 

We could also advise admins they need to setup monitoring of the domain upgrade check so post upgrade they get a status notification about the need to make a change. 

Outside of that, the only other future way to "avoid" this is to untie domain upgrades from *version* upgrades, so that post server upgrade, the admin has to then manually trigger the domain upgrade. But this still won't help people who are "yolo upgrading" since at some point our domain minimum won't match the version and we'll have to say "sorry, you can't startup", and they'll need to rollback the version again to do whatever upgrade fixes are needed. (NOTE: This feature will be developed at some point anyway, as it's good for handling upgrades with replication). 


Regardless - at the end of the day, we have to involve the human admin to make informed choices about *their* data and *their* users data. We can't just automate this, or delete data, or break things. The human has to be responsible for their services and what they run, and we already go further than most software to help enable admins with the needed tools to prevent upgrade issues like this.
