### ISSUE TITLE
Feature request: verify identity functionality

### ISSUE THREAD

**Issue by Charcol** [kanidm/kanidm#337]
To tackle the issues of social engineering scams (for example, over the phone), it could be useful to have a way for users to verify each other by accessing a code upon successful auth.

For example:
Someone calls person A, claiming to be person B.  Both A and B auth to kani, and kani provides the users matching codes which they can verify over the phone. 

Codes should time out, and be easy to read.

Another use case is for a company calling a customer, they can verify this isn't a scam call by logging in and the staff member who initiated the call can verify the code.  In reverse, if a customer calls a company, they can use the code to verify the customer instead of the current common method of reciting birthdays, addresses etc.

**Comment by Firstyear** [comment]
This is a really cool idea, thanks for suggesting it. It would be good to have a design document created for this feature (which can be submitted by a PR). Even if it's just a design of what the user experience should look like, that's a huge help since that can the guide any potential software/engineering solution. I'm sure you are already aware, but we need to make sure that this system/scheme works properly for people of multiple languages and backgrounds.

Another challenge that is specifically code related is how to make this work effectively in an eventually consistent environment. This means that the "challenge/response" system between the two accounts, must be able to work with the users connected to two different kanidm servers, with no cross communication. Some things that could be interesting here is a TOTP-esque system that uses a partial seed from each account to create something that each side can derive. I'm sure there are many other ideas, but this will be key to ensure that this can work "in real time" for people potentially on opposite sides of the planet.
