### ISSUE TITLE
Broken docker images

### ISSUE THREAD

**Issue by OttoHollmann** [kanidm/kanidm#388]
Seems like docker images and docker build is broken (at least for me).

```bash
$ docker pull kanidm/server:latest
$ docker run --rm -it kanidm/server:latest /bin/bash
b20736e6b4f8:/ # /sbin/kanidmd -h
Illegal instruction (core dumped)
```
And it's same for `:devel`

If I try to build own image using `make build/kanidmd`,

on SLES or Debian I get:
```
error: failed to get `base32` as a dependency of package `kanidm_proto v1.1.0-alpha.3 (/usr/src/kanidm/kanidm_proto)`

Caused by:
  failed to initialize index git repository

Caused by:
  failed to resolve path '/root/.cargo/registry/index/github.com-1ecc6299db9ec823/.git/': Operation not permitted; class=Os (2)
ls: cannot access '/usr/src/kanidm/target/release/': No such file or directory
The command '/bin/sh -c if [ "$(uname -m)" == "x86_64" ]; 		then export RUSTFLAGS='-Ctarget-cpu=haswell'; 	fi; 	if [ "$(uname -m)" == "aarch64" ]; 		then export RUSTFLAGS=''; 	fi; 	if [ "${SCCACHE_REDIS}" != "" ]; 		then 			export CC="/usr/bin/sccache /usr/bin/clang" && 			export RUSTC_WRAPPER=sccache && 			sccache --start-server; 		else 			export CC="/usr/bin/clang"; 	fi; 	export RUSTC_BOOTSTRAP=1 && 	echo $RUSTC_BOOTSTRAP && 	echo $RUSTC_WRAPPER && 	echo $RUSTFLAGS && 	echo $CC && 	cargo build 		--features=simd_support,libsqlite3-sys/bundled 		--release; 	if [ "${SCCACHE_REDIS}" != "" ]; 		then sccache -s; 	fi; 	ls -al /usr/src/kanidm/target/release/' returned a non-zero code: 2
make: *** [Makefile:28: build/kanidmd] Error 2
```

But if I run build command on Tumbleweed, it reports different error, (on another run, it will print SIGILL error for different package) e.g.:
```
error: failed to run custom build command for `syn v1.0.64`

Caused by:
  process didn't exit successfully: `/usr/src/kanidm/target/release/build/syn-27d5e4bee826a3c8/build-script-build` (signal: 4, SIGILL: illegal instruction)
warning: build failed, waiting for other jobs to finish...
error: build failed
```
and then build continues (see #389  ).

Which looks really strange, because makefile runs only `docker build` and rest of build is done inside container, so it should be independent on host.

**Comment by Firstyear** [comment]
If you are getting sigill it's likely your CPU is too old - we use haswell as the base cpu version, which is from 2013. What cpu do you have?

**Comment by vDorst** [comment]
Although I have a recent CPU, "Intel(R) Pentium(R) CPU G4560 @ 3.50GHz" is a Kabylake for a low power server, It doesn't have AVX instructions, max is sse4_2.


When creating a docker image on this server, I get an illegal instruction while compiling "proc_macro".
I tried the adjust the `RUSTFLAGS='-Ctarget-cpu=native` but that did not work.

What works for me is just remove this part from the `Dockerfile` and is compiles and runs fine.
```
if [ "$(uname -m)" == "x86_64" ]; \
		then export RUSTFLAGS='-Ctarget-cpu=haswell'; \
	fi; \
	if [ "$(uname -m)" == "aarch64" ]; \
		then export RUSTFLAGS=''; \
	fi; \
	if [ "${SCCACHE_REDIS}" != "" ]; \
		then \
			export CC="/usr/bin/sccache /usr/bin/clang" && \
			export RUSTC_WRAPPER=sccache && \
			sccache --start-server; \
		else \
			export CC="/usr/bin/clang"; \
	fi; \
```

**Comment by Firstyear** [comment]
Interesting - kabylake should all have avx2 at least? Tomorrow I may change how this works then. Can you both provide me the content of `lscpu | grep Flags`? 

How would two docker images work for you with the server? say server/simd:latest and server/minimal:latest or similar naming work? That way we can have one with and without the simd bits. I may also find a way to add a start up check for the features rather than sigill. Or maybe I'll get it to check simd before the db is opened to avoid any "corruption".

**Comment by vDorst** [comment]
I looked into the [Intel wiki](https://en.wikipedia.org/wiki/List_of_Intel_processors) and found that most even the current ones, Intel Celeron and Pertium-branded CPU don't support AVX, only till SSE4.2.

I think the Intel Celeron and Pertium-branded CPU are still very popular in low power/cost and single board pc/gateways.

Intel G4560 was very popular under low power CPU for home server setups because it was one of the cheapest 2 core CPUs with hyperthreading, and also supports ECC memory.
I am using it in combination with a low power workstation mainboard, Fujitsu/Kontron D3417-B2, which gives you a sub 10 Watt home server with ECC memory. Not the fastest but fast enough for my home server stuff.

lscpu flags part, https://ark.intel.com/content/www/us/en/ark/products/97143/intel-pentium-processor-g4560-3m-cache-3-50-ghz.html
```
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon p
                                 ebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_de
                                 adline_timer aes xsave rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust sme
                                 p erms invpcid mpx rdseed smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
```

I reed an artikal about the cpu profile they are defining in GCC and LLVM.
I can't find that artikal but I think this also is simulair. https://www.phoronix.com/scan.php?page=news_item&px=GCC-11-x86-64-Feature-Levels

```
These common levels in their initial form amount to:

    x86-64: CMOV, CMPXCHG8B, FPU, FXSR, MMX, FXSR, SCE, SSE, SSE2
    x86-64-v2: (close to Nehalem) CMPXCHG16B, LAHF-SAHF, POPCNT, SSE3, SSE4.1, SSE4.2, SSSE3
    x86-64-v3: (close to Haswell) AVX, AVX2, BMI1, BMI2, F16C, FMA, LZCNT, MOVBE, XSAVE
    x86-64-v4: AVX512F, AVX512BW, AVX512CD, AVX512DQ, AVX512VL
```

So I think you can you that scheme too and add a wiki to describe the versions and why they exists.

Also a RUST PR for this https://github.com/rust-lang/rust/issues/82024

**Comment by Firstyear** [comment]
This is really good information, thank you. I think for now I'll keep it simple. Maybe just a "minimum" which is x86-64-v2 and a "optimised" which is v3 (we don't need avx512). How does that sound?

**Comment by OttoHollmann** [comment]
Sounds good, thanks!

I'm using `Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz` (introduced in Q3 2013) and it support only avx, not avx2.

```
Flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d
```
Also I've checked on different machine (with newer CPU) and it works well.

**Comment by vDorst** [comment]
@Firstyear Sounds good.

**Comment by Firstyear** [comment]
So I've hit a similar but different issue while doing a draft of the web ui, so I am going to implement a system of "build profiles" that can be selected from that emit the various docker images etc. I'll put in the PR later today or tomorrow, I'm just testing various combinations of things now.
