### ISSUE TITLE
subid ranges sourced from the network store

### ISSUE THREAD

**Issue by vDorst** [kanidm/kanidm#393]
I tried to run an container as a user with podman.
I get this error.

```
ERRO[0000] cannot find UID/GID for user rene: No subuid ranges found for user "rene" in /etc/subuid - check rootless mode in man pages.
WARN[0000] using rootless single mapping into the namespace. This might break some images. Check /etc/subuid and /etc/subgid for adding sub*ids
Resolved "alpine" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull docker.io/library/alpine:latest...
Getting image source signatures
Copying blob ba3557a56b15 done
Copying config 28f6e27057 done
Writing manifest to image destination
Storing signatures
  Error processing tar file(exit status 1): potentially insufficient UIDs or GIDs available in user namespace (requested 0:42 for /etc/shadow): Check /etc/subuid and /etc/subgid: lchown /etc/shadow: invalid argument
Error: Error committing the finished image: error adding layer with blob "sha256:ba3557a56b150f9b813f9d02274d62914fd8fce120dd374d9ee17b87cf1d277d": Error processing tar file(exit status 1): potentially insufficient UIDs or GIDs available in user namespace (requested 0:42 for /etc/shadow): Check /etc/subuid and /etc/subgid: lchown /etc/shadow: invalid argument
```

Looking on the internet I found that this is a known issue with non local users.

See [Active issue about this problem, subid ranges sourced from the network store](https://github.com/shadow-maint/shadow/issues/154)

**Comment by Firstyear** [comment]
Honestly, I don't think this is an issue we can directly solve. I think this is an issue with podman and how it's attempting to do "non-root" containers (I certainly have no issues with docker here ....). I just manually allocate uid's to containers rather than relying on the root-remap ability.

So I'm really not sure why this error is occuring but I think it's not something I easily know how to fix because I think podman may assume some things about uid/gid that we don't. I think even without kani, other systems like freeipa can allocate high number ranges for uid/gid and that would probably cause this too (that's why there are some ipa developers on that issue you linked).

You could work around this by *manually* setting your gidNumber on your account instead. We allow you to set any value from 1000 -> 4294967295 manually, and automatically we always generate between 65535 -> 4294967295 so that we don't stomp on the system id's (your gidnumber is actually derived from the uuid of your account ...). You may find in your environment that manually configuring these values to below 65535 may avoid this issue.

https://github.com/kanidm/kanidm/blob/master/kanidm_book/src/posix_accounts.md

There is a section here on gidNumber allocation and how it's done, etc.

Anyway, I think this is likely a flaw in podman ...

**Comment by vDorst** [comment]
@Firstyear workaround works. Thanks.

I close this issue for now.
I'll reopen it when something is needed on kanidm side.

**Comment by Firstyear** [comment]
@vDorst Perhaps it's worth putting a disclaimer in the book for posix_accounts that this interaction occurs with podman, so that this knowledge isn't lost?

**Comment by bolu61** [comment]
Can we reopen this issue?

1. `nss` should now support subid range lookups:
https://github.com/shadow-maint/shadow/issues/154
https://github.com/SSSD/sssd/issues/5197
https://freeipa.readthedocs.io/en/latest/designs/subordinate-ids.html

2. The workaround doesn't apply in Ubuntu, as only users created by `useradd` and `adduser` gets automatically assigned a subid range.

**Comment by Firstyear** [comment]
@bolu61 I think the conclusion we came to before is that it will be hard to fix. I'm not 100% sure how ipa does this, but we basicly would need a way to hole punch our a range of ID's that can the be allocated as subids. 

What's the usecase you have for subids in this example? It is for a service account? Or a user to run containers?

**Comment by bolu61** [comment]
The use case is for a user to run containers. I have not investigated how IPA does this, but one solution I can think of is generating slightly smaller IDs and multiplying them by the size of the ranges we want to assign. This will obviously increase collision probabilities, but maybe we can implement probing? I assume that `gidnumber` will not be used to query users, so probing should be feasible.

**Comment by Firstyear** [comment]
> generating slightly smaller IDs 

But we can't (easily) do this. Today we generate gids from the uuid. ( https://kanidm.github.io/kanidm/stable/posix_accounts.html#gid-number-generation ) The challenge is if we reduce the pool that we can take from, we more quickly run into the birthday problem. So we either would need to constrain the subid ranges to a small number like 4 or 8 (thus limiting containers), or we make the ranges larger (16, 32, 64) and then we reduce all our birthday numbers significantly (50% at 1200 accounts, 145 for 1% chance if we did 64.). 

This also doesn't even consider migration for existing users who may have users where the subid ranges then collide and overlap. 

I don't know how freeipa does subid's, but they use a different system for uid/gid assignment where each server is allocated a pool of ids and then they can allocate sequentially. It's very error prone however, and very complex. 

But this also means they have large ranges where they can "pluck" subid's from.

**Comment by Firstyear** [comment]
Perhaps the only way to proceed here is for subid ranges to be manually configured by the user, and they have to be responsible for the gid allocation then.

**Comment by bolu61** [comment]
Yea there are definitely challenges.

But the letting user allocate gid manually will require an additional component to maintain: the user need to store states somewhere that has to be centralized and accessible from different machines.

How does kanidm resolve usernames? Maybe something similar can be done.

Of the servers could coordinate on the collision checking, then if we use probing that would workaround migration issues.

**Comment by Firstyear** [comment]
> Yea there are definitely challenges.
> 
> But the letting user allocate gid manually will require an additional component to maintain: the user need to store states somewhere that has to be centralized and accessible from different machines.

Not really, the user just needs to allocate the gid/subid ranges when they setup posix attributes on the user. At that point Kanidm will do the rest. 

> 
> How does kanidm resolve usernames? I understand that Kanidm has conflict resolution mechanisms. Maybe something similar can be done gidnumbers.

It rejects the operation and tells you to retry it if a conflict was found. 

> 
> If the servers could coordinate on the collision checking, then if we use probing that would workaround migration issues, although limiting the available ranges.

It's not quite so simple once we add in replication here, because there is a risk that two servers allocate the same id / range at the same time in isolation, then on next replication they'll trigger the conflict.

Anyway, what kind of subid ranges would be need? Like 8 ids? 16? 128? what's a reasonable expectation? Or is this something we need admins to manually do? 

Another option could be that we "carve out" a range of id numbers that kanidm guarantees we won't allocate into, then admins can use that for subid allocations.

**Comment by yaleman** [comment]
So we've got u32 UIDs to play with in modern systems, since they seem to limit it to that.

Let's try giving them 32 SUB_UIDs per user.

We limit the max POSIX UID to 1/6 of the available space, for funsies, we get the range `5000..67108863.` which is ~67 million POSIX users and at that point we've got bigger issues.

Then we can work up from max_posix_id in blocks of 32 and won't have any overlaps. This obviously scales in different directions depending on how big we want to make the allocations. 128 SUB_UIDs per account is still 16mil POSIX users...

The "allocated the same x" thing should be an issue with UIDs and usernames and every other thing on the platform during replication, so *that* problem is an issue either way.


I wrote a thing to calculate it to validate my math ^_^: https://github.com/yaleman/can_we_subuid

128 each:

```text
Using chunk size 128
sub_uid_min: 16777216
sub_uid_max: 4294967294
uid_min: 5000
uid_max: 16777215
UID: 16777215/16777215 (100.00%)
All good! You get 16,772,215 users with 128 subuids each
```

32 each:

```text
Using chunk size 32
sub_uid_min: 67108864
sub_uid_max: 4294967294
uid_min: 5000
uid_max: 67108863
UID: 67108863/67108863 (100.00%)
All good! You get 67,103,863 users with 32 subuids each
```

**Comment by Firstyear** [comment]
> So we've got u32 UIDs to play with in modern systems, since they seem to limit it to that.
> 
> Let's try giving them 32 SUB_UIDs per user.
> 
> We limit the max POSIX UID to 1/6 of the available space, for funsies, we get the range `5000..67108863.` which is ~67 million POSIX users and at that point we've got bigger issues.

The problem isn't this, the problem is that we assign gids from the last 32 bytes of the uuid, which means we encounter the birthday problem. https://en.wikipedia.org/wiki/Birthday_attack

> 
> Then we can work up from max_posix_id in blocks of 32 and won't have any overlaps. This obviously scales in different directions depending on how big we want to make the allocations. 128 SUB_UIDs per account is still 16mil POSIX users...
> 
> The "allocated the same x" thing should be an issue with UIDs and usernames and every other thing on the platform during replication, so _that_ problem is an issue either way.
> 
> I wrote a thing to calculate it to validate my math ^_^: https://github.com/yaleman/can_we_subuid
> 
> 128 each:
> 
> ```
> Using chunk size 128
> sub_uid_min: 16777216
> sub_uid_max: 4294967294
> uid_min: 5000
> uid_max: 16777215
> UID: 16777215/16777215 (100.00%)
> All good! You get 16,772,215 users with 128 subuids each
> ```
> 
> 32 each:
> 
> ```
> Using chunk size 32
> sub_uid_min: 67108864
> sub_uid_max: 4294967294
> uid_min: 5000
> uid_max: 67108863
> UID: 67108863/67108863 (100.00%)
> All good! You get 67,103,863 users with 32 subuids each
> ```

This assumes sequential allocation of the uid-min -> max. So this gives us 26 bits of random, rather than the current ~30. Which would mean the birthday numbers become:

| prob | 26b | 30b |
| --- | --- | --- |
| 1% | 1162 | 4646 |
| 10% | 3761 | 15042 |
| 50% | 9646 | 38582 |

So by doing subid's like this we greatly increase the likelihood of the collision. 

The other problem is existing uids may *already* be in the subid ranges. Either as a chunk at the "end", or if we did a method of masking the last 5 bits of all users id's to give them a range.

**Comment by bolu61** [comment]
> Not really, the user just needs to allocate the gid/subid ranges when they setup posix attributes on the user. At that point Kanidm will do the rest.

Well the user would have to lookup what ranges are available manually. If a script were to automate this step, it would at least require some counter to be stored somewhere.

> It's not quite so simple once we add in replication here, because there is a risk that two servers allocate the same id / range at the same time in isolation, then on next replication they'll trigger the conflict.

How is this conflict handled when two users are created in isolation? Is one them reverted? We could just assume the same behaviour for gidnumbers. Although  if eventual consistency would cause problems with home directories and permissions.

> The other problem is existing uids may already be in the subid ranges. Either as a chunk at the "end", or if we did a method of masking the last 5 bits of all users id's to give them a range.

We can use probing to solve this, assuming we have already solved replication issues. Old users' subid range will be cut short so that they don't contain already assigned gidnumber and new users will probe for best fitting ranges if available.

To tackle the replication problem, one solution i can think of is sharding. We define a set amount of shards >>> number of replicas. Each shard will be given a predfined disjoint range of gidnumbers. We assign some shards to each replica, where each replica can assign gidnumbers from their shards. Once they run out of gidnumbers, they request new shards. While request to new shards can not be fulfilled, operations should fail.

Say we want 2^16 subuids per user. We could for example divide the whole range of posix uids into 2^8 shards, so that each shard can be identified by the first 8 bits. that would give 2^8 unique uid ranges per shard.

2^16 subuids per user maybe a lot, but is a common value people use. The numbers can be customized to optimize for performance.

**Comment by Firstyear** [comment]
> How is this conflict handled when two users are created in isolation? Is one them reverted? We could just assume the same behaviour for gidnumbers. Although if eventual consistency would cause problems with home directories and permissions.

Both users get conflicted and moved to a hidden entry state where an admin needs to intervene. 

> 
> > The other problem is existing uids may already be in the subid ranges. Either as a chunk at the "end", or if we did a method of masking the last 5 bits of all users id's to give them a range.
> 
> We can use probing to solve this, assuming we have already solved replication issues. Old users' subid range will be cut short so that they don't contain already assigned gidnumber and new users will probe for best fitting ranges if available.

Eventually consistent replication means on any server you can never assume you have the complete state of the topology at any point in time, only that at some point you may conflict and have to handle it. So we can't probe. 

> 
> To tackle the replication problem, one solution i can think of is sharding. We define a set amount of shards >>> number of replicas. Each shard will be given a predfined disjoint range of gidnumbers. We assign some shards to each replica, where each replica can assign gidnumbers from their shards. Once they run out of gidnumbers, they request new shards. While request to new shards can not be fulfilled, operations should fail.

This is exactly how freeipa does it, and it's extremely fragile because you need to allocate a shard master who distributes shards - what ends up happening is people then delete their shard master server and at some point it just silently fails and no one can allocate ids. It's a whole mess.

This is to say nothing of the complexity and issues around shard allocation.

So I *really* do not want to pursue this as a solution. It's very error prone. 

Right now the "best" idea is to mask some bits of the end of the users uid/gid number and use those as the subids. That avoids a lot of this probing and sync issues, and naturally works with what we already have. I think that *existing* accounts will likely need manual subid allocation, or an admin to run a task, but new users can autogenerate them if we mask the id in this way.

**Comment by bolu61** [comment]
> This is exactly how freeipa does it, and it's extremely fragile because you need to allocate a shard master who distributes shards - what ends up happening is people then delete their shard master server and at some point it just silently fails and no one can allocate ids. It's a whole mess.

I don't think we need a shard master, we can manually assign shards.

**Comment by bolu61** [comment]
I'm willing to draft something for sharding when I get the time. Would you be interested?

**Comment by Firstyear** [comment]
Manual shard allocations comes with a stack of other issues. I want to think about this more, I think we need a design document first with the possible solutions, pros/cons, and that way we can talk about and think about what's best. It's annoying, but we want to get it right, so lets design something first.

**Comment by bolu61** [comment]
No worries, I agree we should have a draft design.

**Comment by bolu61** [comment]
@Firstyear This is a bit out of the scope of this discussion, but is it a hard requirement that disconnected replicas be writable?

**Comment by Firstyear** [comment]
Yes. All replicas are always writeable. We need this to track state of some webauthn attributes (device counters)  for cloning detection, and so that accounts can be locked or expired. We also need to account for disconnections in networks to satellite offices etc. 

So all replicas, must always be writeable.

**Comment by Firstyear** [comment]
I think the only options to proceed is have a new exclusion of id's above some X amount for newly created id's, or to have each generated id mask of some bits at the end for subids. I think sharding or other approaches won't work.

The only other option is subids are manually allocated as required.

**Comment by bolu61** [comment]
What if we let replicas reserve their own shards when they are connected? For example, say we have 2^8 bits for shard ID. There will be 256 shards with each 256 sub ID ranges. A replica will initially reserve say 4 shards for  itself. When it is running low of available ranges, it can reserve new shards and let other replicas know. And in the event that two disconnected replicas reserved the same shard, we let admins handle the conflict just like with usernames.

Technically, this can be an opt in feature. For existing user IDs they can just be adopted by the shard that contain the ID and set its range to only contain 1 sub ID.

I believe that letting users manually assign ID just puts the burden of handling synchronization the ranges themself.

**Comment by Firstyear** [comment]
> What if we let replicas reserve their own shards when they are connected? For example, say we have 2^8 bits for shard ID. There will be 256 shards with each 256 sub ID ranges. A replica will initially reserve say 4 shards for itself. When it is running low of available ranges, it can reserve new shards and let other replicas know. And in the event that two disconnected replicas reserved the same shard, we let admins handle the conflict just like with usernames.

This limits you to 256 maximum replicas ever, so if you were to churn servers then you need a way for a replica to also release a shard. 

> 
> Technically, this can be an opt in feature. For existing user IDs they can just be adopted by the shard that contain the ID and set its range to only contain 1 sub ID.
> 
> I believe that letting users manually assign ID just puts the burden of handling synchronization the ranges themself.

Any mature org with more than ~5000 users will have to manually assign id's anyway because of the risk of duplicate gid/uid anyway. So it's reasonable to expect that an external data source may provide the needed ids.

**Comment by bolu61** [comment]
Yea I get what you mean now, theres too many compromises to be made to accommodate all use cases.  

I'm in favour of manual range assignment. A default could be a range of 1 ID.

**Comment by Firstyear** [comment]
The other option here is we make something like a FSMO role for id assignment or use creation. I have to think some more about that.
