### ISSUE TITLE
Explicit user logout/session revocation

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#406]
From a user's perspective, the ability to end a session and/or clear the credentials from the local device is useful.

Steps to consider, perhaps?

- clear device-local session token storage
- client sends a request to terminate
  - *this* session from the IDM perspective
  - *all* sessions for the given user/linked devices
- the IDM infrastructure needs to work amongst themselves to sync this session revocation

**Comment by Firstyear** [comment]
To expand a bit more.

1. The client indicates intent to logout to a kanidm server
2. After the intent to logout is sent, the client removes it's local session storage
3. the kanidm server processes the intent to logout (decision about sync vs async needed here ... probably sync)
4. the account has the session id added to a revoked session id list of the account, and a time stamp of when the session id was created
5. this replicates to other servers over time.

In  addition we need to ensure this doesn't grow too unbounded so we also require similar to purgeRecycled, a purgeOldSessionExpiry that clears session revocations from 2x session length of age. IE if the session was created at time T and was valid for 8 hours, and was revoked 6 hours after T, then T + (2x8) is the age when we would remove this session revocation. This allows time for replay detection and logging. 

To enforce this, we likely need to check each operation that the current UAT is a valid session id of the entry, which can be processed during the event resolution phase, as at this point we already have access to the entry related to the uat for claim and other resolution actions. 

It is also likely a good idea to store into the account metadata about active sessions and their durations, as well as what credential they originated from and claims associated. This will allow logout of a session without access to it's original token. This will need to be added into the authentication flow, and probably necessitates a persistent async queue rather than an ephemeral one so that we don't drop session creations. (alternately, we can refactor the current async queue to be persistent). 

For the cli this would me we need to add:

```
kanidm logout 
kanidm account session list
kanidm account session get <id>
kanidm account session revoke <id>
kanidm self session list
kanidm self session get <id>
kanidm self session revoke <id>
```

@yaleman Thoughts?

**Comment by yaleman** [comment]
> the kanidm server processes the intent to logout (decision about sync vs async needed here ... probably sync)

I'd say a sync processing of the logout request would be best, given it's something you want to happen *now* in an incident situation - let alone for normal usage.

> the account has the session id added to a revoked session id list of the account, and a time stamp of when the session id was created

Given that (I think?) session lifetimes are flexible (ie, cli lifetime vs an SSO flow lifetime) would it be better to store the session expiry, or the start + lifetime?

> It is also likely a good idea to store into the account metadata about active sessions and their durations, as well as what credential they originated from and claims associated. This will allow logout of a session without access to it's original token. 

Logout should only be actionable by a currently-valid token, and likely only one with the proper claims - I'm not sure I'd want my `super neat CLI session` token to be blatted by a token which was issued with claims to `bob's company snackbar SSO`. 

It *definitely* shouldn't require the original token to terminate itself - again, IR/cleanup situations require the ability to just go "NOPE ALL MY SESSIONS PLZ".

The CLI verbs/nouns sound sensible to me :)

**Comment by Firstyear** [comment]
> > the kanidm server processes the intent to logout (decision about sync vs async needed here ... probably sync)
> 
> I'd say a sync processing of the logout request would be best, given it's something you want to happen _now_ in an incident situation - let alone for normal usage.

Yeah, I agree. But you still need to consider replication delay, so it will be async no matter what you want anyway, it's just if it's sync or async on this server in this immediate instance. 

> 
> > the account has the session id added to a revoked session id list of the account, and a time stamp of when the session id was created
> 
> Given that (I think?) session lifetimes are flexible (ie, cli lifetime vs an SSO flow lifetime) would it be better to store the session expiry, or the start + lifetime?

Some thought needs to go into the session storage timestamping mechanism :) 

> 
> > It is also likely a good idea to store into the account metadata about active sessions and their durations, as well as what credential they originated from and claims associated. This will allow logout of a session without access to it's original token.
> 
> Logout should only be actionable by a currently-valid token, and likely only one with the proper claims - I'm not sure I'd want my `super neat CLI session` token to be blatted by a token which was issued with claims to `bob's company snackbar SSO`.

Ahhh, this more meant ... if a user has lost access to a device, they can revoke the session because its part of *their* account, even though they don't have access to that original token anymore.

It doesn't mean *any one* could revoke the tokens. 

Second, it does mean there can be a privelege granted to groups allowing revocation of other peoples tokens too. 

> 
> It _definitely_ shouldn't require the original token to terminate itself - again, IR/cleanup situations require the ability to just go "NOPE ALL MY SESSIONS PLZ".
> 
> The CLI verbs/nouns sound sensible to me :)

**Comment by yaleman** [comment]
> sync vs replication delays

Replication delay's always going to be a thing, and it's always part of the expectations management I guess. From a kill-(this|all)-tokens perspective I'd argue for a sync actioning of it so you can provide positive confirmation to the requestor that it was done, at least for the server they're talking to, rather than queued in general.

Then again, with the expected performance of the platform... maybe it's not required?

> Ahhh, this more meant ... if a user has lost access to a device, they can revoke the session because its part of their account, even though they don't have access to that original token anymore.

We were thinking the same thing - I just wanted to be explicit as to the auth scope of the _individual user's_ token - I don't have a clear enough understanding of claims yet in Kanidm though :)

**Comment by Firstyear** [comment]
> > sync vs replication delays
> 
> Replication delay's always going to be a thing, and it's always part of the expectations management I guess. From a kill-(this|all)-tokens perspective I'd argue for a sync actioning of it so you can provide positive confirmation to the requestor that it was done, at least for the server they're talking to, rather than queued in general.
> 
> Then again, with the expected performance of the platform... maybe it's not required?

No I think it's best to have this as sync. The reason I'm thinking about this as an option is more about when the server is under high write load, there may be a delay in the response of the logout action, and it's a "reasonable common" user interactive process.

So the "async" variant would be that the request-to-logout is commited to a persistent (stable) queue and then done in a write txn in the background ASAP. That way the persistent queue can be lower write latency than waiting on a transaction over the main DB. 

But really, I'm probably also over-engineering a solution to a problem that doesn't exist yet :) Keep it simple. 

> 
> > Ahhh, this more meant ... if a user has lost access to a device, they can revoke the session because its part of their account, even though they don't have access to that original token anymore.
> 
> We were thinking the same thing - I just wanted to be explicit as to the auth scope of the _individual user's_ token - I don't have a clear enough understanding of claims yet in Kanidm though :)

All good. I'm going to be writing some of these up soon to make it clearer for people are not resident to my head :)
