### ISSUE TITLE
automatic clearing of stale credentials from kanidm_tokens

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#414]
`~/.cache/kanidm_tokens` gets full of all the used tokens, is there an auto-cleanup task, or could there be one made?

Two reasons:

 1. security - it's not good to list what accounts have been used on this machine by this account - `user_a` has access to `idm_admin` - rad, target them!
 2. it's neater. uWu.

**Comment by Firstyear** [comment]
Yep, agreed. This needs to happen. I think to achieve this I need to make some changes to how sessions are current managed. Today they are encrypted with fernet, but that makes them opaque. I think to do this nicely, I need to swap to signing (ie ecdsa or ed25519) and then we can expose an expiry field so that the client also knows what time the token becomes invalid. That will allow them to be cleaned up.
