### ISSUE TITLE
Alias/virtual fields for LDAP searches

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#439]
My use case is for LDAP, there's some fields which are queried by various clients which cause filter errors and failed queries. As discussed elsewhere this is likely to be needed for mappings on things like SAML too, so ... maybe best to be something that can be configured outside the source code, either at a config-file level or in the DB?

| queried field | kanidm field | other notes
| --- | --- | --- |
| [entrydn](https://ldapwiki.com/wiki/EntryDN) | normalised spn, maybe? | "a normalized form of the entry's DN" ([RFC5020](https://datatracker.ietf.org/doc/html/rfc5020)) - Splunk looks for this |
| email/emailAddress | mail | https://ldapwiki.com/wiki/1.2.840.113549.1.9.1 |
| firstname | ? | Not sure how to map this in a way that meets kanidm's human-centric goals |
| comment | ? | possibly just a blank response? |
| keys | ssh_publickey? | |

**Comment by yaleman** [comment]
This is what happens when [Proxmox](https://www.proxmox.com/en/) tries to sync users:
```
[<kopid> admin::info] ldap_request_message 2021-05-13T04:36:56.914856852+00:00
[<kopid> admin::info] Attempt LDAP Search for anonymous@example.com
[<kopid> admin::info] LDAP Search Request Attrs -> Some({"comment", "email", "enable", "expire", "firstname", "keys", "lastname", "memberof", "name", "spn"})
[<kopid> admin::info] LDAP Search Filter -> And([And([Or([Present("keys"), Present("name"), Present("firstname"), Present("expire"), Present("comment"), Present("lastname"), Present("spn"), Present("email"), Present("enable")]), Or([Equality("objectclass", "account")])]), Not(Or([Equality("class", "classtype"), Equality("class", "attributetype"), Equality("class", "access_control_profile")]))])
[<kopid> filter::trace] filter optimised --> Filter { state: FilterValidResolved { inner: And([Eq("uuid", Uuid(00000000-0000-0000-0000-ffffffffffff), true), AndNot(Or([Eq("class", Iutf8("tombstone"), true), Eq("class", Iutf8("recycled"), true)]))]) } }
[<kopid> filter::info] filter executed plan -> AndPartialThreshold([EqIndexed("uuid", "00000000-0000-0000-0000-ffffffffffff")])
[<kopid> admin::error 🚨] failed to create search event -> SchemaViolation(InvalidAttribute("keys"))
```

Splunk doing its thing
```
[<kopid> admin::info] ldap_request_message 2021-05-13T04:46:01.147751301+00:00
[<kopid> admin::info] Attempt LDAP Search for anonymous@example.com
[<kopid> admin::info] LDAP Search Request Attrs -> Some({"displayname", "mail", "name"})
[<kopid> admin::info] LDAP Search Filter -> And([And([Equality("entrydn", "spn=yaleman@example.com,dc=example,dc=com"), Equality("memberof", "splunk_admins"), Present("displayname"), Present("name")]), Not(Or([Equality("class", "classtype"), Equality("class", "attributetype"), Equality("class", "access_control_profile")]))])
[<kopid> filter::trace] filter optimised --> Filter { state: FilterValidResolved { inner: And([Eq("uuid", Uuid(00000000-0000-0000-0000-ffffffffffff), true), AndNot(Or([Eq("class", Iutf8("tombstone"), true), Eq("class", Iutf8("recycled"), true)]))]) } }
[<kopid> filter::info] filter executed plan -> AndPartialThreshold([EqIndexed("uuid", "00000000-0000-0000-0000-ffffffffffff")])
[<kopid> admin::error 🚨] failed to create search event -> InvalidAttributeName("entrydn")
```

**Comment by Firstyear** [comment]
If you look at kanidmd/src/lib/ldap.rs line 456, this already exists (kinda). There is a way to map names to their kani version, and then reverse is done in kanidmd/src/lib/entry.rs line 1460. This is called from kanidmd/src/lib/ldap.rs line 264

The issue is that some kani attributes are ALSO valid ldap ones. IE mail. 

The other issue is that there are sometimes *many* possible input aliases. IE keys, sshPublicKey, which will both map to ssh_publickey. So we need to know "what was requested" so we know how to rename it.

So my immediate thinking is:

* If the request is "*" (all attrs), we have to_ldap() explode each kanidm attribute to *all* possible attributes that an application may expect
* If the request specifies a set of attributes, during to_ldap we take the list of requested ldap attributes, and using that we build the attribute set from what attributes are requested with the relevant lookup in ldap_attr_filter_map

This way we can handle an ldap search for things like "keys ssh_publickey sshPublicKey" because we would explode and remap all. 

You raise an excellent point re firstname - we will absolutely need to consider what is the correct way to handle this, and how we could generate or remap this.

Entry dn we can easily synthesise during to_ldap if requested. We should consider just returning the dn here. However I'm wary of applications that primary key to dn, and that today includes spn, so we may need to make dn actually pinned on uuid instead. 

WRT to the attr comment, and how to handle this. The search is failing because we only query attributes that exist in schema (and reject attempts for attrs that do not) This is to work around an issue/attack vector in current ldap servers where you can request an attribute that does not exist, forcing a full table scan. It may be "rough" in that it raises the error like this, but it also means we can then take actions to handle it correctly. 

To make this value, and to make sure that our "map" attributes can never accidentally be reused there is a concept of "phantom" attributes. These are attributes that can be searched and generated on entries, but can NEVER be persisted into the database. 

So in this case, for every attribute we add for ldap that we plan to either ignore in a search (comments) or remap (entrydn, etc), we need to add the corresponding phantoms. See kanidmd/src/lib/schema.rs 1105 for the current set of ldap masking phantoms. 

So today, with the exception of firstname, I think it's very achievable to satisfy this request. 



-- 

Wrt to firstname. My immediate thought is to just plug in displayName into firstname, and see how that goes.

But I know that in most ldap schemas, SN (surname) is required, but givenName (unix) and firstName (AD) are optional in their schemas. So I'm really not sure what's the best approach here. 

So it may be that we have to plug in displayName to SN, and then make gn/fn empty to satisfy schema?
