### ISSUE TITLE
🪵 The 🪵 Great 🪵 Log 🪵 Issue 🪵

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#453]
Logs should be:

1. Fast.
2. Timestamped.
3. JSON.
4. Correlatable.

[json_env_logger](https://lib.rs/crates/json_env_logger) seems sensible from an import-a-crate-make-go perspective, env_logger is already being used in a bunch of places and replacing it with json\_env\_logger is largely a find-and-replace matter - then the long tail of `%s/eprintln/error/g`.

It doesn't do everything, but... it might be able to once the formatting options are considered.

I have a much longer rant about logging [here](https://yaleman.org/post/2021/2021-05-22-the-great-log-post-/) if you want to read it. It got pretty long, so ... let's start with ^ that.

**Comment by yaleman** [comment]
[tracing](https://docs.rs/tracing/0.1.21/tracing/) is another option I found in a tab I didn't read while writing my rant, and seems to support a lot more things more betterer.

The article's really quite relevant - [Production-Grade Logging in Rust Applications](https://betterprogramming.pub/production-grade-logging-in-rust-applications-2c7fffd108a6) - it's got code examples and good threaded-client-server-thingie logging practices.

**Comment by Firstyear** [comment]
Yeah, tracing has been an option that I need to look at and investigate. It may be a good idea to start on some of these ideas in say the unixd daemon or the tasks daemon since they are smaller and easier to make these changes in, and we can get a feel for the differences.

**Comment by QnnOkabayashi** [comment]
Hi, I read your blog post and the article and I'd like to take a shot at this. I was digging around for unix/daemon things and `kanidm_unix_int/src/daemon.rs` looked like a good place to start, since it already uses a bit of logging. How would I specifically test this feature? Also, is this targeting a specific problem or just a general QOL change?

**Comment by yaleman** [comment]
@QnnOkabayashi it's part of a longer side-channel discussion @Firstyear and I have been having about logging in general - it's been done on an as-needs basis during dev so far with a view to cleaning it up later 🥰

Testing's probably more a "hey here's some screenshots/snippets what do people think" of how this works?

**Comment by Firstyear** [comment]
I agree here with @yaleman - testing this is about human interaction and that experience, so it's going to be a fair bit of review and collaboration and iterative improvement.

I think if we had to summarise what are the key goals

* Allow swapping between human and machine readable formats.
* Retain the "aggregation" feature currently present in auditscope in the main core
* Extend and improve profiling and performance measurement detail
* Improve tagging of log messages based on different categories.

So the question becomes a lot about different trades, what works for people, small experiments and iterations to achieve this. Tracing for example may work better in unix/tasks compared to the current env_logger setup. Where as in the server core we may need to adapt something different based on that experience. Does that help?

**Comment by QnnOkabayashi** [comment]
Yes, this helps a lot.

>     * Allow swapping between human and machine readable formats.
Is this not accomplished through JSON formatting?

>     * Improve tagging of log messages based on different categories.
Is this a best judgement thing, or is there defined criteria for each category of log?

> So the question becomes a lot about different trades, what works for people, small experiments and iterations to achieve this. Tracing for example may work better in unix/tasks compared to the current env_logger setup. Where as in the server core we may need to adapt something different based on that experience. Does that help?

I understand that the effectiveness of any changes I make would be subjective to the area and use case. But how would I approach actually running code and testing for correctness, specifically for `kanidm_unit_int/src/daemon.rs` since I've already been poking around there? Like, how do I know what to put in `#[test]`s? Do I need to initialize a Kanidm instance for myself? Thanks again for the feedback!

**Comment by QnnOkabayashi** [comment]
> EDIT: Have you setup a server instance and seen how it logs? That could give you some insight about the current state and how it's done.

Nope-
