### ISSUE TITLE
Add systemd .services files into the git repository?

### ISSUE THREAD

**Issue by cuberoot74088** [kanidm/kanidm#471]
Dear all,

thank you very much for creating kanidm :-)

I am trying to create a working package for Arch Linux ... I was wondering if it would be possible to include the systemd .service files to this repository, maybe in the examples folder together with the other config examples.

Currently, the files were taken from 
https://build.opensuse.org/package/show/home:firstyear:kanidm/kanidm
and are somewhat disconnected, I would say.

I think you would also need these service files if you build and install from source, so it might be nice to ship it with the repo?

If that makes sense and you agree, I could also include them and create a PR for that.

Thank you very much in advance for your advice.

**Comment by Firstyear** [comment]
hi @cuberoot74088 - i think there is already an Arch linux package, so have you reached out to the current maintainer to work together on this? 

However, I think it's an interesting idea to include the systemd files. @yaleman what do you think (since you're looking at debian)?

If you were going to open this @cuberoot74088 could you make  it in a folder called `platform/<distro name>/blah.service`?

**Comment by cuberoot74088** [comment]
Hi @Firstyear,
I have commented on the package (https://aur.archlinux.org/pkgbase/kanidm/) and sent patches to the maintainer soloturn as well but have not received an answer yet. It is still work in progress, as I need to find a good/clean way to build the wasm stuff for the server...

As I am using your version (opensuse?) of the systemd files, would it be necessary to create them per distro?

**Comment by Firstyear** [comment]
Thanks mate! I've pinged soloturn on the Kanidm Gitter channel ( https://gitter.im/kanidm/community ) to hopefully get their attention. I think we may need to get a bit more coordinated between distros about releasing/packaging of this.

Wasm is a special fun, and this is why we check in binaries into the repos. See also the build scripts in the kanidmd_web_ui folder, and if that's not enough, can you open a new issue for me to document that process more accurately? 

Finally, I think we should have "per distro" systemd files, but initially we can make these symlinks so that they can be shared. Initially this is why I kept the service files "out" of the repo, because each distro may have it's own quirks or needs. I think I want to check with @yaleman first before we put these in though and make a call on this :)

**Comment by yaleman** [comment]
I'm totally down for`.service` files in the main repo as it'd make packaging easier - there's *some* OS-specific things that need to be taken into account - but largely the same files can be used across all OSen if we avoid being too tricky (the existing `kanidm_unixd` CacheDir thing isn't always supported, as an example).

**Comment by cuberoot74088** [comment]
Alright, so I will try to prepare something :+1:

**Comment by soloturn** [comment]
@Firstyear made @cuberoot74088 co-maintainer of the arch package, thanks for pinging!

**Comment by Firstyear** [comment]
Thanks @soloturn for adding @cuberoot74088 to co-maintain - appreciate both of your efforts!
