### ISSUE TITLE
tumbleweed system packages errors

### ISSUE THREAD

**Issue by mslacken** [kanidm/kanidm#528]
* in `/etc/kandimd/server.toml` the `db_path` should be changed to
     `db_path = "/var/lib/kanidmd/kanidm.db"`
* in `kandimd.service` the option `DynamicUser` should be changed to `not` as with `yes` it does not work
* the `kandim-client` rpm misses a configuration file

**Comment by Firstyear** [comment]
hey there,

The default server.toml is for a container - not for a daemon like this.

As well, dynamic user should stay, because it's an important security feature for tw/systemd. 

Finally, what config file is missing?

**Comment by mslacken** [comment]
> hey there,
> 
> The default server.toml is for a container - not for a daemon like this.
> 
Still both, the container and the systems service should use the same path to the database. Having different path (`"/var/lib/kanidmd/kanidm.db"` vs `"/var/lib/kanidm/kanidm.db"` makes things unnecessary coomplicated.
> As well, dynamic user should stay, because it's an important security feature for tw/systemd.
> 
Still the dynamic should have access to the configuration.
> Finally, what config file is missing?
I just get following error:
`
Configuration option 'uri' missing, cannot continue client startup.
thread 'main' panicked at 'not implemented', kanidm_client/src/lib.rs:313:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`

**Comment by yaleman** [comment]
That'll be because you need to configure the URI for the client with the server name - there's a semi-useful debug message, but you don't see that unless you're running debug logging.

I've PR'd a change (#529) to make this a bit more obvious and terminate the client when config's missing.

**Comment by Firstyear** [comment]
> > hey there,
> > The default server.toml is for a container - not for a daemon like this.
> 
> Still both, the container and the systems service should use the same path to the database. Having different path (`"/var/lib/kanidmd/kanidm.db"` vs `"/var/lib/kanidm/kanidm.db"` makes things unnecessary coomplicated.

The bigger concern is the current documentation through out the kanidm book is intended to be "copy-paste" and all reference /data/ at this time. Changing this would break all of this.

As well in a container, /data makes it extremely clear what is "container" and what is "data". Putting this into /var/lib/kanidm only blurs this, makes it murky as to what owns what, and also actually makes it harder for users to remember the paths they need. 

In kanidm for the server especially I'll always prioritise the container experience over a packaged server experience and what our examples show, because this is what will give the best experience for the deployments of the server. 

About the only way this example will change is if we write a tool that templates out the example config based on a build profile so we can change that path at build time. 

> 
> > As well, dynamic user should stay, because it's an important security feature for tw/systemd.
> 
> Still the dynamic should have access to the configuration.
> 
> > Finally, what config file is missing?
> > I just get following error:
> > `Configuration option 'uri' missing, cannot continue client startup. thread 'main' panicked at 'not implemented', kanidm_client/src/lib.rs:313:17 note: run with`RUST_BACKTRACE=1`environment variable to display a backtrace`

Have ... you followed the kanidm book? Or are you just trying to poke around at the package? https://github.com/kanidm/kanidm/blob/master/kanidm_book/src/SUMMARY.md

I think many of your issues may be resolved here.

**Comment by mslacken** [comment]
> 
> Have ... you followed the kanidm book? Or are you just trying to poke around at the package? https://github.com/kanidm/kanidm/blob/master/kanidm_book/src/SUMMARY.md

I poked around with the package, still the kanidm book is missing a proper labeled chapter on how to setup a client. It is all there in the chapter "Interacting with the server", but I think "Client setup" would be a much better choice.

**Comment by Firstyear** [comment]
@yaleman What do you think about the chapter rename? I think it's probably a reasonable idea.

**Comment by yaleman** [comment]
It's something I've considered in the past, I'll have a poke around at docs and ... try to make it a bit clearer :)

**Comment by yaleman** [comment]
PR'd with a bunch of changes here https://github.com/kanidm/kanidm/pull/534
