### ISSUE TITLE
oauth2 - "consent to proceed" prompt

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#636]
I'm not sure if this is a debugging thing, but can this be disabled by default, or on an RS basis? It's configured, so it's allowed, and an unnecessary bump to the experience for users.

**Comment by Firstyear** [comment]
It's required by oauth actually. There is a workflow for denying the workflow, I just havent added the button yet.

**Comment by yaleman** [comment]
Oh bother, that's annoying. Maybe I'm used to people like Github/google/okta breaking spec and just logging you in...

**Comment by yaleman** [comment]
Does the spec say it has to be on every authentication flow, or is it just on first login (ever) to a system? The latter would obviously require storage of this ack by the user somewhere.

**Comment by Firstyear** [comment]
Yep, they are meant to ask for consent - the reason is that if you are already authenticated to the auth provider, then without the consent step we'll implicitly let you through, which MAY disclose your email and other personal details to the third party.

Saying this, I can see that in some cases it may not be needed with some apps in an enterprise or similar. 

It's every auth flow according to spec. Maybe some providers just do it on first use. 

I can think of two solutions here:

* A flag to mark on an application if consent is requested or implied on the app
* After first use, we can async add to the account that we've done the first-auth through this app. We can bind it by uuid to account for renames etc. I'd say if any of the scope maps change AND they *add* one of the oidc PII flags, then we invalidate the consents and you have to re-grant it. 


The first is "easier", the second seems more "correct" by the user.

**Comment by yaleman** [comment]
I like the second option, a single prompt to say "yep, yeet my deets to x app", with a slight change:

> scope maps change AND they add one of the oidc PII flags

becomes 

> scope maps change or they change any of the oidc flags

Anything changes, invalidate - it's simpler logic, should be a rare thing (other than when you first configure an RS), and any change = tell the user. Be noisy 😆
