### ISSUE TITLE
domain_name_change does not change rp_id

### ISSUE THREAD

**Issue by obel1x** [kanidm/kanidm#645]
I installed packages for opensuse 15.3, kanidm 1.1.0-alpha.7 as described and edited delivered server.toml

running the setup with my domain like this:
`kanidmd domain_name_change -c /data/server.toml -n obel1x.de`

returns:
`[admin.error]: You must change origin or domain name to be consistent. ed: "https://obel1x.de:8443" - rp_id: "example.com"`

shouldn't "-n" set the rp_id to "obel1x.de" and change the settings to match ? 

It makes no difference, if i set domain to some value in the config (it was shipped without domain setting in cfg)

**Comment by obel1x** [comment]
oh, right and many thanks!

i did read that thread, but what was missing for my second brain cell, was the information, that to change the domainname via command, the origin in the config must not be changed (!) and needs to be e.g. "idm.example.com" to do so.

Only after changing the domainname via command, the origin in the config can be changed afterwards to match.

All fine, closed this

**Comment by Firstyear** [comment]
@obel1x Thanks for reporting the issue :) glad I could help you solve it.

Don't feel bad that you missed that detail, it was a really large conversation. There are some lessons we can certainly learn here, I think a large one is that currently our docs always come from git master, where we probably need a split between latest and "release" channel. I think there is already a PR to improve that.

Otherwise please let us know if there is anything else you run into, we are happy to help and all feedback can help make Kanidm better! Thanks!
