### ISSUE TITLE
LDAP service accounts with additional permissions / Access mail attribute via LDAP for Postfix

### ISSUE THREAD

**Issue by max-privatevoid** [kanidm/kanidm#990]
**Is your feature request related to a problem? Please describe.**
I'm trying to deploy Kanidm in a self-hosting/hobbyist scenario with a handful of users, as a replacement for our exising FreeIPA installation. We run our own mail server with user authentication and mailbox mappings provided through LDAP. As the `mail` attribute in Kanidm is not readable by the anonymous user, LDAP lookups cannot read it.

**Describe the solution you'd like**
Since giving anonymous access to the `mail` attribute isn't exactly great from a security perspective, one option I've considered is the use of service accounts. Bind DNs are already usable for auth purposes in Kanidm, so maybe this could be extended to also include extra attributes the given user can read as long as the user has a "read_from_ldap" permission or something like that. This would also be useful for user federation when using IdPs like Keycloak.

**Describe alternatives you've considered**
Writing a Postfix plugin to use the Kanidm API directly? :skull:

**Comment by Firstyear** [comment]
@max-privatevoid Thanks for your interest in the project! 

The reason today why LDAP binds force anonymous access, is that they currently relate to the unix password of the account which is a single factor of authentication. If we allowed this to access attributes, then all the nice MFA we have higher up, goes out the window because ... well, single factor! 

However, that doesn't mean it's *not* possible - I think a possible way to do this could be to have the LDAP bind interface accept the unix password (anonymous privileges) OR to have it accept a token (jwt or other) which enables the full read privileges of the account. Think API token etc. Given the current structure of the LDAP backend, it actually would be pretty easy WRT to the token checking components, the main thing would be the token *issuing* that would require the most work. 

Saying this, I've been thinking about API token access for service accounts for a while, so maybe now is the time that I dig into this. :) 

PS: Federated IDPs like keycloak have the drawback here that they also can't access our MFA credentials, so probably aren't actually a good idea to use in these cases.

**Comment by Firstyear** [comment]
Relates #406 #613 session logout / tracking will be needed for this to work correctly. Which conveniently was my next "todo list" item.

**Comment by Firstyear** [comment]
@max-privatevoid I've started to work on this, but I might be slowed down a little because I sadly sustained a pretty significant injury in the last 24 hours.  But this task is a priority for me :)

**Comment by Firstyear** [comment]
@max-privatevoid This is now merged and will be in the next release. For your use case, you should be able to add your service account to the group `idm_people_read_priv` which will allow the "mail" attribute to be read. This works via api and ldap. There will be more improvements in the space for application password support too ! Also starting to improve some of the ipa migration tooling too.
